<a href="https://colab.research.google.com/github/artbrgn/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module4-makefeatures/Arturo_Obregon_LS_DS_114_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [9]:
##### Begin Working Here #####
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-09-05 20:47:49--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [                <=> ]  21.58M   806KB/s    in 28s

2019-09-05 20:48:17 (799 KB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22631049]

In [10]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [12]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","4264.17","4264.17","1891.55","1891.55","1335.83","555.72","0.0","0.0","0.0","Aug-2019","190.21","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","7655.00","7655.00","3459.26","3459.26","2345.00","1114.26","0.0","0.0","0.0","Aug-2019","346.76","Sep-2019","Aug-2019","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3807.30","3807.30","1694.53","1694.53","1192.70","501.83","0.0","0.0","0.0","Aug-2019","169.83","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","7544.75","7356.13","3261.44","3179.90","2455.25","806.19","0.0","0.0","0.0","Aug-2019","327.68","Sep-2019","Aug-2019","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","7706.67","7706.67","3551.41","3551.41","2293.33","1258.08","0.0","0.0","0.0","Aug-2019","356.08","Sep-2019","Aug-2019","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [11]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 36 months"," 10.33%","324.23","B","B1","","< 1 year","MORTGAGE","280000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","974xx","OR","6.15","2","Jan-1996","0","18","","14","0","9082","38%","23","w","8289.30","8289.30","2261.0","2261.00","1710.70","550.30","0.0","0.0","0.0","Jul-2019","324.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","671","246828","1","3","2","3","1","48552","62","1","3","4923","46","23900","2","7","1","7","17631","11897","43.1","0","0","158","275","11","1","1","11","","11","","0","3","4","7","7","10","9","11","4","14","0","0","0","4","91.3","28.6","0","0","367828","61364","20900","54912","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 23.40%","155.68","E","E1","Security","3 years","RENT","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","070xx","NJ","26.33","0","Sep-2006","4","59","","15","0","5199","19.2%","20","w","3423.38","3423.38","1081.96","1081.96","576.62","505.34","0.0","0.0","0.0","Jul-2019","155.68","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","66926","5","4","3","4","5","61727","86","6","11","1353","68","27100","4","0","4","15","4462","20174","7.9","0","0","147","118","2","2","0","2","","0","","0","5","7","9","9","8","11","12","7","15","0","0","0","9","95","0","0","0","98655","66926","21900","71555","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 17.97%","180.69","D","D1","Administrative","6 years","MORTGAGE","59280","Source Verified","Dec-2018","Late (31-120 days)","n","","","debt_consolidation","Debt consolidation","490xx","MI","10.51","0","Apr-2011","0","","","8","0","4599","19.1%","13","w","4456.17","4456.17","895.96","895.96","543.83","352.13","0.0","0.0","0.0","Jun-2019","180.69","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","110299","0","1","0","2","14","7150","72","0","2","0","35","24100","1","5","0","4","18383","13800","0","0","0","87","92","15","14","2","77","","14","","0","0","3","3","3","4","6","7","3","8","0","0","0","0","100","0","0","0","136927","11749","13800","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 60 months"," 20.89%","620.81","D","D4","Operator","5 years","RENT","68107","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","672xx","KS","0.52","0","Feb-1997","0","","","5","0","976","13%","10","w","21353.16","21353.16","4307.45","4307.45","1646.84","2660.61","0.0","0.0","0.0","Jul-2019","620.81","Sep-2019","Aug-2019","1","","1","Individual","","","","0","2693","976","0","0","0","0","36","0","","3","4","0","13","7500","2","2","4","4","195","3300","0","0","0","237","262","10","10","0","10","","9","","0","0","1","3","4","3","5","7","1","5","0","0","0","3","100","0","0","0","7500","976","3300","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 23.40%","311.35","E","E1","Manager","10+ years","OWN","43000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","357xx","AL","33.24","0","Jan-1995","0","","107","8","1","9019","81.3%","16","w","6846.83","6846.83","2163.85","2163.85","1153.17","1010.68","0.0","0.0","0.0","Jul-2019","311.35","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","169223","0","3","2","2","7","22059","69","0","0","2174","72","11100","1","1","1","2","21153","126","94.5","0","0","148","287","44","7","1","51","","7","","0","1","4","1","2","8","4","7","4","8","0","0","0","2","100","100","1","0","199744","31078","2300","32206","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","32075","32075","32075"," 60 months"," 11.80%","710.26","B","B4","Nursing Supervisor","10+ years","MORTGAGE","150000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","231xx","VA","22.21","0","Aug-2005","0","","","17","0","19077","32%","24","w","29228.12","29228.12","4940.28","4940.28","2846.88","2093.40","0.0","0.0","0.0","Jul-2019","710.26","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","272667","1","4","1","1","9","37558","47","1","1","3910","41","59600","1","2","0","3","16039","10446","47.8","0","0","160","70","4","4","2","27","","14","","0","4","10","4","4","8","12","14","10","17","0","0","0","2","100","50","0","0","360433","56635","20000","80125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","9600","9600","9600"," 36 months"," 12.98%","323.37","B","B5","","n/a","MORTGAGE","35704","Not Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","401xx","KY","0.84","0","Nov-2003","0","69","","5","0","748","11.5%","23","w","8012.51","8012.51","2287.83","2287.83","1587.49","700.34","0.0","0.0","0.0","Aug-2019","323.37","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","748","0","0","0","0","44","0","","0","3","748","12","6500","0","0","1","3","150","3452","17.8","0","0","181","100","13","13","0","16","","3","","0","1","1","2","2","16","5","7","1","5","0","0","0","0","95.5","0","0","0","6500","748","4200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 18.94%","777.23","D","D2","Postmaster ","10+ years","MORTGAGE","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","713xx","LA","26.52","0","Jun-1987","0","71","75","13","1","12315","24.2%","44","w","19969.40","19969.40","12893.26","12893.26","10030.60","2862.66","0.0","0.0","0.0","Jul-2019","777.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1208","321915","4","4","2","3","3","87153","88","4","5","998","57","50800","2","15","2","10","24763","13761","8.3","0","0","163","378","4","3","3","4","","4","","0","2","4","4","9","27","8","14","4","13","0","0","0","6","95","0","1","0","372872","99468","15000","94072","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [13]:
import pandas as pd

#set pandas display ooptions
pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)

#romoved the extra lines of text from the header using (header=1)
#romoved the estra lines of text from the footer using (skipfooter = 2)
df = pd.read_csv('LoanStats_2018Q4.csv', header=1, na_values=['n/a'], skipfooter=2)
df.head(10)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  import sys

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.000000,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.960000,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.960000,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.450000,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.850000,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,32075,32075,32075.0,60 months,11.80%,710.26,B,B4,Nursing Supervisor,10+ years,MORTGAGE,150000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,231xx,VA,22.21,0,Aug-2005,0,NaN,NaN,17,0,19077,32%,24,w,29228.12,29228.12,4940.280000,4940.28,2846.88,2093.40,0.0,0.0,0.0,Jul-2019,710.26,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,272667,1,4,1,1,9.0,37558,47.0,1,1,3910,41.0,59600,1,2,0,3,16039.0,10446.0,47.8,0,0,160.0,70,4,4,2,27.0,NaN,14.0,NaN,0,4,10,4,4,8,12,14,10,17,0.0,0,0,2,100.0,50.0,0,0,360433,56635,20000,80125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,9600,9600,9600.0,36 months,12.98%,323.37,B,B5,NaN,NaN,MORTGAGE,35704.0,Not Verified,Dec-2018,Current,n,NaN,NaN,home_improvement,Home improvement,401xx,KY,0.84,0,Nov-2003,0,69.0,NaN,5,0,748,11.5%,23,w,8012.51,8012.51,2287.830000,2287.83,1587.49,700.34,0.0,0.0,0.0,Aug-2019,323.37,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,748,0,0,0,0,44.0,0,NaN,0,3,748,12.0,6500,0,0,1,3,150.0,3452.0,17.8,0,0,181.0,100,13,13,0,16.0,NaN,3.0,NaN,0,1,1,2,2,16,5,7,1,5,0.0,0,0,0,95.5,0.0,0,0,6500,748,4200,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,30000,30000,30000.0,60 months,18.94%,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0,Jun-1987,0,71.0,75.0,13,1,12315,24.2%,44,w,19969.40,19969.40,12893.260000,12893.26,10030.60,2862.66,0.0,0.0,0.0,Jul-2019,777.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,1208,321915,4,4,2,3,3.0,87153,88.0,4,5,998,57.0,50800,2,15,2,10,24763.0,13761.0,8.3,0,0,163.0,378,4,3,3,4.0,NaN,4.0,NaN,0,2,4,4,9,27,8,14,4,13,0.0,0,0,6,95.0,0.0,1,0,372872,99468,15000,94072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,2500,2500,2500.0,36 months,13.56%,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0,Apr-2001,1,NaN,45.0,9,1,4341,10.3%,34,w,0.00,0.00,2652.765986,2652.77,2500.00,152.77,0.0,0.0,0.0,May-2019,2315.91,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,16901,2,2,1,2,2.0,12560,69.0,2,7,2137,28.0,42000,1,11,2,9,1878.0,34360.0,5.9,0,0,140.0,212,1,1,0,1.0,NaN,2.0,NaN,0,2,5,3,3,16,7,18,5,9,0.0,0,0,3,100.0,0.0,1,0,60124,16901,36500,18124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,12000,12000,12000.0,60 months,13.56%,276.49,C,C1,NaN,< 1 year,MORTGAGE,40000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,180xx,PA,19.23,0,Aug-2005,2,NaN,NaN,8,0,23195,55.5%,9,w,10979.70,10979.70,1921.870000,1921.87,1020.30,901.57,0.0,0.0,0.0,Jul-2019,276.49,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,32462,1,1,1,1,4.0,9267,103.0,2,2,9747,64.0,41800,1,0,3,3,4058.0,16601.0,54.9,0,0,4.0,149,9,4,1,10.0,NaN,4.0,NaN,0,5,6,5,5,1,7,7,6,8,0.0,0,0,3,100.0,60.0,0,0,50800,32462,36800,9000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#view the column headers of my dataset
list(df.columns)

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [16]:
#I can use the shape method to get the number of rows or columns
# by using [0] I can refer to either the column or rows of the output
#[rows, columns]
df.shape[0]

128412

In [17]:
#sorts the columns with most NaN in ascending order
df.isnull().sum().sort_values(ascending=False)

id                                            128412
desc                                          128412
member_id                                     128412
url                                           128412
orig_projected_additional_accrued_interest    128386
hardship_type                                 128385
hardship_last_payment_amount                  128385
hardship_payoff_balance_amount                128385
hardship_reason                               128385
hardship_loan_status                          128385
hardship_dpd                                  128385
hardship_length                               128385
payment_plan_start_date                       128385
hardship_end_date                             128385
hardship_start_date                           128385
hardship_amount                               128385
deferral_term                                 128385
hardship_status                               128385
settlement_percentage                         128301
settlement_term                               128301
settlement_status                             128301
settlement_amount                             128301
settlement_date                               128301
debt_settlement_flag_date                     128301
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
sec_app_collections_12_mths_ex_med            111630
dti_joint                                     111630
annual_inc_joint                              111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
mths_since_recent_bc_dlq                      103243
mths_since_last_major_derog                    99232
mths_since_recent_revol_delinq                 91630
mths_since_last_delinq                         72196
emp_title                                      20947
il_util                                        20274
next_pymnt_d                                   16123
mths_since_recent_inq                          16047
emp_length                                     11704
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
num_tl_120dpd_2m                                2859
bc_util                                         1754
percent_bc_gt_75                                1692
bc_open_to_buy                                  1691
mths_since_recent_bc                            1591
dti                                              237
last_pymnt_d                                     159
revol_util                                       156
all_util                                          37
avg_cur_bal                                       13
last_credit_pull_d                                 1
int_rate                                           0
initial_list_status                                0
out_prncp                                          0
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
total_rec_prncp                                    0
purpose                                            0
total_rec_int                                      0
total_acc                                          0
funded_amnt_inv                                    0
funded_amnt                                        0
total_rec_late_fee                                 0
recoveries                                         0
loan_amnt                                          0
collection_recovery_fee                            0
term                                               0
revol_bal                                          0
installment                                        0
pymnt_plan                                         0
loan_status                                        0
title                                              0
zip_code                                           0
addr_state                                         0
issue_d                                            0
delinq_2yrs                                        0
earliest_cr_line                                   0
verification_status                                0
annual_inc                                         0
inq_last_6mths                                     0
home_ownership                                     0
sub_grade                                          0
grade                                              0
open_acc                                           0
pub_rec                                            0
debt_settlement_flag                               0
open_il_12m                                        0
last_pymnt_amnt                                    0
num_sats                                           0
num_accts_ever_120_pd                              0
num_actv_bc_tl                                     0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_tl_30dpd                                       0
collections_12_mths_ex_med                         0
num_tl_90g_dpd_24m                                 0
num_tl_op_past_12m                                 0
pct_tl_nvr_dlq                                     0
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_old_rev_tl_op                               0
policy_code                                        0
application_type                                   0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
hardship_flag                                      0
open_il_24m                                        0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
total_cu_tl                                        0
inq_last_12m                                       0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
inq_fi                                             0
dtype: int64

In [0]:
df = df.drop(columns=['id', 'member_id','desc','url'])

In [19]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#resorted to have NaN columns in ascedning order
df.isnull().sum().sort_values(ascending=False)

orig_projected_additional_accrued_interest    128386
hardship_loan_status                          128385
hardship_dpd                                  128385
hardship_reason                               128385
hardship_status                               128385
deferral_term                                 128385
hardship_amount                               128385
hardship_start_date                           128385
hardship_end_date                             128385
payment_plan_start_date                       128385
hardship_length                               128385
hardship_type                                 128385
hardship_payoff_balance_amount                128385
hardship_last_payment_amount                  128385
settlement_percentage                         128301
debt_settlement_flag_date                     128301
settlement_status                             128301
settlement_date                               128301
settlement_amount                             128301
settlement_term                               128301
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
annual_inc_joint                              111630
sec_app_collections_12_mths_ex_med            111630
dti_joint                                     111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
mths_since_recent_bc_dlq                      103243
mths_since_last_major_derog                    99232
mths_since_recent_revol_delinq                 91630
mths_since_last_delinq                         72196
emp_title                                      20947
il_util                                        20274
next_pymnt_d                                   16123
mths_since_recent_inq                          16047
emp_length                                     11704
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
num_tl_120dpd_2m                                2859
bc_util                                         1754
percent_bc_gt_75                                1692
bc_open_to_buy                                  1691
mths_since_recent_bc                            1591
dti                                              237
last_pymnt_d                                     159
revol_util                                       156
all_util                                          37
avg_cur_bal                                       13
last_credit_pull_d                                 1
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
out_prncp                                          0
total_rec_prncp                                    0
total_rec_late_fee                                 0
initial_list_status                                0
recoveries                                         0
total_acc                                          0
collection_recovery_fee                            0
last_pymnt_amnt                                    0
total_rec_int                                      0
loan_status                                        0
revol_bal                                          0
verification_status                                0
funded_amnt                                        0
funded_amnt_inv                                    0
term                                               0
int_rate                                           0
installment                                        0
grade                                              0
sub_grade                                          0
home_ownership                                     0
annual_inc                                         0
issue_d                                            0
pub_rec                                            0
pymnt_plan                                         0
purpose                                            0
title                                              0
zip_code                                           0
addr_state                                         0
delinq_2yrs                                        0
earliest_cr_line                                   0
inq_last_6mths                                     0
open_acc                                           0
collections_12_mths_ex_med                         0
inq_last_12m                                       0
policy_code                                        0
num_tl_90g_dpd_24m                                 0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_sats                                           0
num_tl_30dpd                                       0
num_tl_op_past_12m                                 0
application_type                                   0
pct_tl_nvr_dlq                                     0
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
hardship_flag                                      0
debt_settlement_flag                               0
num_actv_bc_tl                                     0
num_accts_ever_120_pd                              0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
open_il_12m                                        0
open_il_24m                                        0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
inq_fi                                             0
total_cu_tl                                        0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
loan_amnt                                          0
dtype: int64

In [22]:
df['int_rate']

0          10.33%
1          23.40%
2          17.97%
3          20.89%
4          23.40%
5          11.80%
6          12.98%
7          18.94%
8          13.56%
9          13.56%
10         19.92%
11         17.97%
12         26.31%
13         14.47%
14         23.40%
15         23.40%
16         20.89%
17         16.91%
18         20.89%
19         14.47%
20         13.56%
21         14.47%
22         12.98%
23         23.40%
24         11.80%
25         20.89%
26         26.31%
27         16.14%
28         18.94%
29         15.02%
30         17.97%
31         13.56%
32         17.97%
33         12.98%
34         11.80%
35         10.72%
36         12.98%
37         11.80%
38         14.47%
39         10.72%
40         11.80%
41         23.40%
42         20.89%
43         19.92%
44         10.33%
45          6.46%
46         14.47%
47         11.31%
48         17.97%
49         15.02%
50          8.81%
51         15.02%
52         16.91%
53         14.47%
54         25.34%
55         14.47%
56         12.98%
57         10.72%
58         19.92%
59         17.97%
60         12.98%
61         16.14%
62         10.33%
63         20.89%
64         17.97%
65         17.97%
66         12.98%
67         23.40%
68         14.47%
69         19.92%
70         14.47%
71         16.91%
72          6.46%
73         10.33%
74         13.56%
75         14.47%
76         10.33%
77         12.98%
78         12.98%
79         16.14%
80         15.02%
81         27.27%
82         16.91%
83         14.47%
84         15.02%
85         13.56%
86         16.91%
87         12.98%
88         14.47%
89         14.47%
90         17.97%
91         16.14%
92         11.80%
93         18.94%
94         11.80%
95         11.80%
96         18.94%
97         11.31%
98          7.56%
99         18.94%
100        11.31%
101        23.40%
102        11.31%
103        10.72%
104        14.47%
105        14.47%
106        16.91%
107        22.35%
108        12.98%
109        16.14%
110        16.14%
111        17.97%
112        14.47%
113        12.98%
114        10.72%
115        11.31%
116        10.33%
117        18.94%
118        15.02%
119        16.14%
120        13.56%
121        22.35%
122        15.02%
123        14.47%
124        10.72%
125        16.14%
126        15.02%
127        19.92%
128        14.47%
129        11.31%
130        12.98%
131        27.27%
132        17.97%
133        15.02%
134        16.14%
135        12.98%
136        15.02%
137        18.94%
138        16.14%
139        11.31%
140        26.31%
141        11.80%
142        15.02%
143        27.27%
144        26.31%
145        14.47%
146        15.02%
147        14.47%
148        15.02%
149        16.14%
150        11.31%
151        27.27%
152        11.31%
153        23.40%
154        10.33%
155        18.94%
156        11.31%
157        16.14%
158        12.98%
159        10.72%
160        17.97%
161        23.40%
162        14.47%
163        13.56%
164        10.72%
165        11.80%
166        18.94%
167        13.56%
168        11.31%
169         7.56%
170        10.72%
171        11.80%
172        17.97%
173        16.14%
174        17.97%
175        12.98%
176        11.31%
177        20.89%
178         8.19%
179        20.89%
180        16.91%
181        22.35%
182         8.81%
183        23.40%
184        11.31%
185        15.02%
186        23.40%
187        16.14%
188        10.33%
189        15.02%
190        14.47%
191        23.40%
192        10.72%
193        16.14%
194        13.56%
195        14.47%
196        14.47%
197         8.81%
198        10.33%
199        18.94%
200        15.02%
201        30.75%
202         8.19%
203         6.46%
204        13.56%
205         8.19%
206        16.14%
207        10.72%
208        16.91%
209        10.72%
210        15.02%
211        14.47%
212        16.14%
213        16.91%
214        13.56%
215        11.31%
216        16.14%
217        15.02%
218        16.14%
219        15.02%
220        17.97%
221        18.94%
222        16.91%
223        11.80%
224        14.47%
225        11.31%
226        14.47%
227        16.14%
228        20.89%
229        17.97%
230        16.14%
231        10.33%
232         8.81%
233        14.47%
234        16.14%
235        13.56%
236        10.72%
237        14.47%
238        11.31%
239        17.97%
240        12.98%
241        16.14%
242        22.35%
243         8.19%
244        20.89%
245         6.46%
246        27.27%
247        12.98%
248        15.02%
249        17.97%
           ...
128162     28.72%
128163     22.35%
128164      7.21%
128165     19.92%
128166     11.55%
128167     20.89%
128168      8.46%
128169      7.84%
128170     16.91%
128171     15.02%
128172     16.14%
128173     10.08%
128174     13.56%
128175      8.46%
128176      6.11%
128177      6.67%
128178     19.92%
128179     12.73%
128180     10.08%
128181     22.35%
128182     12.73%
128183     11.55%
128184      7.21%
128185     13.56%
128186      6.11%
128187     13.56%
128188     16.14%
128189     18.94%
128190      8.46%
128191     14.47%
128192     28.72%
128193     14.47%
128194      7.84%
128195     10.08%
128196     23.40%
128197      7.21%
128198      6.67%
128199      6.11%
128200     28.72%
128201      6.67%
128202     12.73%
128203     11.55%
128204      6.67%
128205      6.11%
128206      7.84%
128207     10.47%
128208     25.34%
128209     13.56%
128210      7.21%
128211      6.11%
128212      7.21%
128213     22.35%
128214     19.92%
128215      8.46%
128216      6.11%
128217      6.67%
128218      6.11%
128219      6.11%
128220      7.84%
128221     11.55%
128222     10.47%
128223     11.06%
128224     10.47%
128225      8.46%
128226      6.67%
128227     12.73%
128228      6.11%
128229      6.11%
128230     16.14%
128231     16.91%
128232     24.37%
128233     12.73%
128234     11.06%
128235     16.14%
128236     18.94%
128237      6.11%
128238     16.14%
128239     13.56%
128240      6.11%
128241     22.35%
128242      6.11%
128243     27.27%
128244     11.55%
128245      6.11%
128246      6.11%
128247      7.21%
128248      7.21%
128249      6.11%
128250      8.46%
128251      6.11%
128252      7.84%
128253      7.21%
128254     26.31%
128255     16.91%
128256     28.72%
128257     29.69%
128258      7.21%
128259      7.84%
128260      7.21%
128261     11.06%
128262     25.34%
128263      6.11%
128264     11.06%
128265     16.91%
128266     17.97%
128267     10.08%
128268     27.27%
128269      6.67%
128270      7.84%
128271     15.02%
128272     11.06%
128273     14.47%
128274     18.94%
128275      7.21%
128276     13.56%
128277     15.02%
128278      7.84%
128279     19.92%
128280      7.21%
128281      8.46%
128282     18.94%
128283     13.56%
128284      6.11%
128285     11.06%
128286     14.47%
128287      7.21%
128288     14.47%
128289      6.67%
128290      8.46%
128291     16.91%
128292     13.56%
128293      6.67%
128294      7.84%
128295      6.67%
128296     14.47%
128297     15.02%
128298      6.11%
128299     25.34%
128300     16.14%
128301     23.40%
128302      7.21%
128303      6.11%
128304     12.73%
128305      7.84%
128306     10.47%
128307     15.02%
128308     24.37%
128309     10.08%
128310     22.35%
128311      7.84%
128312     27.27%
128313     15.02%
128314     22.35%
128315      6.11%
128316     22.35%
128317      7.84%
128318      6.11%
128319     17.97%
128320     22.35%
128321     15.02%
128322     17.97%
128323     11.55%
128324     10.08%
128325      6.11%
128326      6.11%
128327     17.97%
128328     16.14%
128329     23.40%
128330     20.89%
128331     13.56%
128332      6.11%
128333     15.02%
128334     18.94%
128335      7.84%
128336      7.21%
128337      7.84%
128338     11.55%
128339     24.37%
128340      7.21%
128341     19.92%
128342     14.47%
128343     24.37%
128344     12.73%
128345      7.84%
128346      7.21%
128347      7.84%
128348      7.84%
128349     15.02%
128350     16.91%
128351     27.27%
128352     10.08%
128353     11.55%
128354      7.21%
128355      6.11%
128356     13.56%
128357     27.27%
128358     11.55%
128359     11.06%
128360      7.21%
128361     17.97%
128362     27.27%
128363     11.55%
128364     11.06%
128365      8.46%
128366      7.84%
128367      6.11%
128368      8.46%
128369     14.47%
128370     14.47%
128371     13.56%
128372     17.97%
128373      7.84%
128374     22.35%
128375     11.55%
128376     16.91%
128377     11.06%
128378     13.56%
128379     27.27%
128380      6.67%
128381      7.84%
128382     17.97%
128383     16.91%
128384     13.56%
128385     17.97%
128386     26.31%
128387     11.55%
128388      8.46%
128389     11.55%
128390     19.92%
128391      6.67%
128392     26.31%
128393     16.91%
128394      6.11%
128395     11.55%
128396     15.02%
128397     15.02%
128398     18.94%
128399     15.02%
128400     15.02%
128401     11.55%
128402     22.35%
128403     16.14%
128404     16.14%
128405      7.84%
128406     13.56%
128407     15.02%
128408     15.02%
128409     13.56%
128410     11.06%
128411     16.91%
Name: int_rate, Length: 128412, dtype: object

In [23]:
df.dtypes

loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                       object
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                     int64
earliest_cr_line                               object
inq_last_6mths                                  int64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                        int64
pub_rec                                         int64
revol_bal                                       int64
revol_util                                     object
total_acc                                       int64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                      int64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                  int64
tot_coll_amt                                    int64
tot_cur_bal                                     int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
mths_since_rcnt_il                            float64
total_bal_il                                    int64
il_util                                       float64
open_rv_12m                                     int64
open_rv_24m                                     int64
max_bal_bc                                      int64
all_util                                      float64
total_rev_hi_lim                                int64
inq_fi                                          int64
total_cu_tl                                     int64
inq_last_12m                                    int64
acc_open_past_24mths                            int64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
delinq_amnt                                     int64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                            int64
tax_liens                                       int64
tot_hi_cred_lim                                 int64
total_bal_ex_mort                               int64
total_bc_limit                                  int64
total_il_high_credit_limit                      int64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
dtype: object

In [0]:
def remove_month_to_integer(string):
  return int(string.strip('months'))


df['term'] = df['term'].apply(remove_month_to_integer)

In [34]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_is_great
0,10000,10000,10000.0,36,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True
1,4000,4000,4000.0,36,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True
2,5000,5000,5000.0,36,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True
3,23000,23000,23000.0,60,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True
4,8000,8000,8000.0,36,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,True

In [28]:
df.dtypes

loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                            int64
int_rate                                       object
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                     int64
earliest_cr_line                               object
inq_last_6mths                                  int64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                        int64
pub_rec                                         int64
revol_bal                                       int64
revol_util                                     object
total_acc                                       int64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                      int64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                  int64
tot_coll_amt                                    int64
tot_cur_bal                                     int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
mths_since_rcnt_il                            float64
total_bal_il                                    int64
il_util                                       float64
open_rv_12m                                     int64
open_rv_24m                                     int64
max_bal_bc                                      int64
all_util                                      float64
total_rev_hi_lim                                int64
inq_fi                                          int64
total_cu_tl                                     int64
inq_last_12m                                    int64
acc_open_past_24mths                            int64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
delinq_amnt                                     int64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                            int64
tax_liens                                       int64
tot_hi_cred_lim                                 int64
total_bal_ex_mort                               int64
total_bc_limit                                  int64
total_il_high_credit_limit                      int64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
dtype: object

In [39]:
df['loan_status_is_great'] = 1
df['loan_status_is_great']

0         1
1         1
2         1
3         1
4         1
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
30        1
31        1
32        1
33        1
34        1
35        1
36        1
37        1
38        1
39        1
40        1
41        1
42        1
43        1
44        1
45        1
46        1
47        1
48        1
49        1
50        1
51        1
52        1
53        1
54        1
55        1
56        1
57        1
58        1
59        1
60        1
61        1
62        1
63        1
64        1
65        1
66        1
67        1
68        1
69        1
70        1
71        1
72        1
73        1
74        1
75        1
76        1
77        1
78        1
79        1
80        1
81        1
82        1
83        1
84        1
85        1
86        1
87        1
88        1
89        1
90        1
91        1
92        1
93        1
94        1
95        1
96        1
97        1
98        1
99        1
100       1
101       1
102       1
103       1
104       1
105       1
106       1
107       1
108       1
109       1
110       1
111       1
112       1
113       1
114       1
115       1
116       1
117       1
118       1
119       1
120       1
121       1
122       1
123       1
124       1
125       1
126       1
127       1
128       1
129       1
130       1
131       1
132       1
133       1
134       1
135       1
136       1
137       1
138       1
139       1
140       1
141       1
142       1
143       1
144       1
145       1
146       1
147       1
148       1
149       1
150       1
151       1
152       1
153       1
154       1
155       1
156       1
157       1
158       1
159       1
160       1
161       1
162       1
163       1
164       1
165       1
166       1
167       1
168       1
169       1
170       1
171       1
172       1
173       1
174       1
175       1
176       1
177       1
178       1
179       1
180       1
181       1
182       1
183       1
184       1
185       1
186       1
187       1
188       1
189       1
190       1
191       1
192       1
193       1
194       1
195       1
196       1
197       1
198       1
199       1
200       1
201       1
202       1
203       1
204       1
205       1
206       1
207       1
208       1
209       1
210       1
211       1
212       1
213       1
214       1
215       1
216       1
217       1
218       1
219       1
220       1
221       1
222       1
223       1
224       1
225       1
226       1
227       1
228       1
229       1
230       1
231       1
232       1
233       1
234       1
235       1
236       1
237       1
238       1
239       1
240       1
241       1
242       1
243       1
244       1
245       1
246       1
247       1
248       1
249       1
         ..
128162    1
128163    1
128164    1
128165    1
128166    1
128167    1
128168    1
128169    1
128170    1
128171    1
128172    1
128173    1
128174    1
128175    1
128176    1
128177    1
128178    1
128179    1
128180    1
128181    1
128182    1
128183    1
128184    1
128185    1
128186    1
128187    1
128188    1
128189    1
128190    1
128191    1
128192    1
128193    1
128194    1
128195    1
128196    1
128197    1
128198    1
128199    1
128200    1
128201    1
128202    1
128203    1
128204    1
128205    1
128206    1
128207    1
128208    1
128209    1
128210    1
128211    1
128212    1
128213    1
128214    1
128215    1
128216    1
128217    1
128218    1
128219    1
128220    1
128221    1
128222    1
128223    1
128224    1
128225    1
128226    1
128227    1
128228    1
128229    1
128230    1
128231    1
128232    1
128233    1
128234    1
128235    1
128236    1
128237    1
128238    1
128239    1
128240    1
128241    1
128242    1
128243    1
128244    1
128245    1
128246    1
128247    1
128248    1
128249    1
128250    1
128251    1
128252    1
128253    1
128254    1
128255    1
128256    1
128257    1
128258    1
128259    1
128260    1
128261    1
128262    1
128263    1
128264    1
128265    1
128266    1
128267    1
128268    1
128269    1
128270    1
128271    1
128272    1
128273    1
128274    1
128275    1
128276    1
128277    1
128278    1
128279    1
128280    1
128281    1
128282    1
128283    1
128284    1
128285    1
128286    1
128287    1
128288    1
128289    1
128290    1
128291    1
128292    1
128293    1
128294    1
128295    1
128296    1
128297    1
128298    1
128299    1
128300    1
128301    1
128302    1
128303    1
128304    1
128305    1
128306    1
128307    1
128308    1
128309    1
128310    1
128311    1
128312    1
128313    1
128314    1
128315    1
128316    1
128317    1
128318    1
128319    1
128320    1
128321    1
128322    1
128323    1
128324    1
128325    1
128326    1
128327    1
128328    1
128329    1
128330    1
128331    1
128332    1
128333    1
128334    1
128335    1
128336    1
128337    1
128338    1
128339    1
128340    1
128341    1
128342    1
128343    1
128344    1
128345    1
128346    1
128347    1
128348    1
128349    1
128350    1
128351    1
128352    1
128353    1
128354    1
128355    1
128356    1
128357    1
128358    1
128359    1
128360    1
128361    1
128362    1
128363    1
128364    1
128365    1
128366    1
128367    1
128368    1
128369    1
128370    1
128371    1
128372    1
128373    1
128374    1
128375    1
128376    1
128377    1
128378    1
128379    1
128380    1
128381    1
128382    1
128383    1
128384    1
128385    1
128386    1
128387    1
128388    1
128389    1
128390    1
128391    1
128392    1
128393    1
128394    1
128395    1
128396    1
128397    1
128398    1
128399    1
128400    1
128401    1
128402    1
128403    1
128404    1
128405    1
128406    1
128407    1
128408    1
128409    1
128410    1
128411    1
Name: loan_status_is_great, Length: 128412, dtype: int64

In [0]:


# df['loan_status_is_great'] = df['loan_status'].str.contains('Current')
# df['loan_status_is_great']

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01