<a href="https://colab.research.google.com/github/fuse999/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module4-makefeatures/Drive_LS_DS_114_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [3]:
##### Begin Working Here #####

# Get My Data
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-09-05 23:08:44--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [                 <=>]  21.58M   883KB/s    in 25s

2019-09-05 23:09:10 (874 KB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22631049]

In [4]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [5]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 36 months"," 10.33%","324.23","B","B1","","< 1 year","MORTGAGE","280000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","974xx","OR","6.15","2","Jan-1996","0","18","","14","0","9082","38%","23","w","8289.30","8289.30","2261.0","2261.00","1710.70","550.30","0.0","0.0","0.0","Jul-2019","324.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","671","246828","1","3","2","3","1","48552","62","1","3","4923","46","23900","2","7","1","7","17631","11897","43.1","0","0","158","275","11","1","1","11","","11","","0","3","4","7","7","10","9","11","4","14","0","0","0","4","91.3","28.6","0","0","367828","61364","20900","54912","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 23.40%","155.68","E","E1","Security","3 years","RENT","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","070xx","NJ","26.33","0","Sep-2006","4","59","","15","0","5199","19.2%","20","w","3423.38","3423.38","1081.96","1081.96","576.62","505.34","0.0","0.0","0.0","Jul-2019","155.68","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","66926","5","4","3","4","5","61727","86","6","11","1353","68","27100","4","0","4","15","4462","20174","7.9","0","0","147","118","2","2","0","2","","0","","0","5","7","9","9","8","11","12","7","15","0","0","0","9","95","0","0","0","98655","66926","21900","71555","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 17.97%","180.69","D","D1","Administrative","6 years","MORTGAGE","59280","Source Verified","Dec-2018","Late (31-120 days)","n","","","debt_consolidation","Debt consolidation","490xx","MI","10.51","0","Apr-2011","0","","","8","0","4599","19.1%","13","w","4456.17","4456.17","895.96","895.96","543.83","352.13","0.0","0.0","0.0","Jun-2019","180.69","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","110299","0","1","0","2","14","7150","72","0","2","0","35","24100","1","5","0","4","18383","13800","0","0","0","87","92","15","14","2","77","","14","","0","0","3","3","3","4","6","7","3","8","0","0","0","0","100","0","0","0","136927","11749","13800","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 60 months"," 20.89%","620.81","D","D4","Operator","5 years","RENT","68107","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","672xx","KS","0.52","0","Feb-1997","0","","","5","0","976","13%","10","w","21353.16","21353.16","4307.45","4307.45","1646.84","2660.61","0.0","0.0","0.0","Jul-2019","620.81","Sep-2019","Aug-2019","1","","1","Individual","","","","0","2693","976","0","0","0","0","36","0","","3","4","0","13","7500","2","2","4","4","195","3300","0","0","0","237","262","10","10","0","10","","9","","0","0","1","3","4","3","5","7","1","5","0","0","0","3","100","0","0","0","7500","976","3300","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 23.40%","311.35","E","E1","Manager","10+ years","OWN","43000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","357xx","AL","33.24","0","Jan-1995","0","","107","8","1","9019","81.3%","16","w","6846.83","6846.83","2163.85","2163.85","1153.17","1010.68","0.0","0.0","0.0","Jul-2019","311.35","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","169223","0","3","2","2","7","22059","69","0","0","2174","72","11100","1","1","1","2","21153","126","94.5","0","0","148","287","44","7","1","51","","7","","0","1","4","1","2","8","4","7","4","8","0","0","0","2","100","100","1","0","199744","31078","2300","32206","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","32075","32075","32075"," 60 months"," 11.80%","710.26","B","B4","Nursing Supervisor","10+ years","MORTGAGE","150000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","231xx","VA","22.21","0","Aug-2005","0","","","17","0","19077","32%","24","w","29228.12","29228.12","4940.28","4940.28","2846.88","2093.40","0.0","0.0","0.0","Jul-2019","710.26","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","272667","1","4","1","1","9","37558","47","1","1","3910","41","59600","1","2","0","3","16039","10446","47.8","0","0","160","70","4","4","2","27","","14","","0","4","10","4","4","8","12","14","10","17","0","0","0","2","100","50","0","0","360433","56635","20000","80125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","9600","9600","9600"," 36 months"," 12.98%","323.37","B","B5","","n/a","MORTGAGE","35704","Not Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","401xx","KY","0.84","0","Nov-2003","0","69","","5","0","748","11.5%","23","w","8012.51","8012.51","2287.83","2287.83","1587.49","700.34","0.0","0.0","0.0","Aug-2019","323.37","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","748","0","0","0","0","44","0","","0","3","748","12","6500","0","0","1","3","150","3452","17.8","0","0","181","100","13","13","0","16","","3","","0","1","1","2","2","16","5","7","1","5","0","0","0","0","95.5","0","0","0","6500","748","4200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 18.94%","777.23","D","D2","Postmaster ","10+ years","MORTGAGE","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","713xx","LA","26.52","0","Jun-1987","0","71","75","13","1","12315","24.2%","44","w","19969.40","19969.40","12893.26","12893.26","10030.60","2862.66","0.0","0.0","0.0","Jul-2019","777.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1208","321915","4","4","2","3","3","87153","88","4","5","998","57","50800","2","15","2","10","24763","13761","8.3","0","0","163","378","4","3","3","4","","4","","0","2","4","4","9","27","8","14","4","13","0","0","0","6","95","0","1","0","372872","99468","15000","94072","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [6]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","4264.17","4264.17","1891.55","1891.55","1335.83","555.72","0.0","0.0","0.0","Aug-2019","190.21","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","7655.00","7655.00","3459.26","3459.26","2345.00","1114.26","0.0","0.0","0.0","Aug-2019","346.76","Sep-2019","Aug-2019","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3807.30","3807.30","1694.53","1694.53","1192.70","501.83","0.0","0.0","0.0","Aug-2019","169.83","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","7544.75","7356.13","3261.44","3179.90","2455.25","806.19","0.0","0.0","0.0","Aug-2019","327.68","Sep-2019","Aug-2019","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","7706.67","7706.67","3551.41","3551.41","2293.33","1258.08","0.0","0.0","0.0","Aug-2019","356.08","Sep-2019","Aug-2019","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [9]:
# Finished Getting and Inspecting Data

# Next Load Data

import pandas as pd
df_Copy0 = pd.read_csv("LoanStats_2018Q4.csv.zip", header=1, skipfooter=2)
df_Copy0.head(40)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                    NaN              NaN
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN
5  NaN        NaN  ...                    NaN              NaN
6  NaN        NaN  ...                    NaN              NaN
7  NaN        NaN  ...                    NaN              NaN
8  NaN        NaN  ...                    NaN              NaN
9  NaN        NaN  ...                    NaN              NaN
10 NaN        NaN  ...                    NaN              NaN
11 NaN        NaN  ...                    NaN              NaN
12 NaN        NaN  ...                    NaN              NaN
13 NaN        NaN  ...                    NaN              NaN
14 NaN        NaN  ...                    NaN              NaN
15 NaN        NaN  ...                    NaN              NaN
16 NaN        NaN  ...                    NaN              NaN
17 NaN        NaN  ...                    NaN              NaN
18 NaN        NaN  ...                    NaN              NaN
19 NaN        NaN  ...                    NaN              NaN
20 NaN        NaN  ...                    NaN              NaN
21 NaN        NaN  ...                    NaN              NaN
22 NaN        NaN  ...                    NaN              NaN
23 NaN        NaN  ...                    NaN              NaN
24 NaN        NaN  ...                    NaN              NaN
25 NaN        NaN  ...                    NaN              NaN
26 NaN        NaN  ...                    NaN              NaN
27 NaN        NaN  ...                    NaN              NaN
28 NaN        NaN  ...                    NaN              NaN
29 NaN        NaN  ...                    NaN              NaN
30 NaN        NaN  ...                    NaN              NaN
31 NaN        NaN  ...                    NaN              NaN
32 NaN        NaN  ...                    NaN              NaN
33 NaN        NaN  ...                    NaN              NaN
34 NaN        NaN  ...                    NaN              NaN
35 NaN        NaN  ...                    NaN              NaN
36 NaN        NaN  ...                    NaN              NaN
37 NaN        NaN  ...                    NaN              NaN
38 NaN        NaN  ...                    NaN              NaN
39 NaN        NaN  ...                    NaN              NaN

[40 rows x 144 columns]

In [10]:
# Convert term column from string to integer.

# Test Def

Term_Test = "36 months"
type(Term_Test)

str

In [11]:
print(Term_Test.strip("months"))

36

In [12]:
Term_Test = Term_Test.strip("months")
print(Term_Test)
type(Term_Test)

36

str

In [13]:
Term_Test_int = int(Term_Test)
print(Term_Test_int)
type(Term_Test_int)

36

int

In [15]:
def remove_months(string):
  return int(string.strip("months"))

remove_months(Term_Test)

36

In [0]:
# Apply the function to the term column
df_Copy1 = df_Copy0
df_Copy1.term = df_Copy0.term.apply(remove_months)
df_Copy1.term

In [0]:
# Convert terms to int
df_Copy1.term = df_Copy1.term.astype('int32')
df_Copy1.dtypes

In [18]:
# Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.

df_Copy1.loan_status.value_counts(dropna=False).head(20)

Current               108584
Fully Paid             13929
Late (31-120 days)      2291
Charged Off             2194
In Grace Period          849
Late (16-30 days)        560
Default                    5
Name: loan_status, dtype: int64

In [0]:
def Loan_Status_Great_func(string):
  #string.in(["Fully Paid", "Current"])
  #return 1
  #string.in(["Late (31-120 days)", "Charged Off", "In Grace Period", "Late (16-30 days)", "Default"])
  #return 0


   if string in ["Fully Paid", "Current"]:
    return 1
   else:
    return 0

In [20]:
# This did not Work
# df_Copy1.loan_status_is_great = df_Copy1.loan_status.apply(Loan_Status_Great_func)
# This did
df_Copy1["loan_status_is_great"] = df_Copy1.loan_status.apply(Loan_Status_Great_func)
df_Copy1.head(5)

   id  member_id  ...  settlement_term  loan_status_is_great
0 NaN        NaN  ...              NaN                     1
1 NaN        NaN  ...              NaN                     1
2 NaN        NaN  ...              NaN                     0
3 NaN        NaN  ...              NaN                     1
4 NaN        NaN  ...              NaN                     1

[5 rows x 145 columns]

In [0]:
df_Copy1.head(5)

In [22]:
# Make last_pymnt_d_month and last_pymnt_d_year columns.

df_Copy1.describe(include="object")

       int_rate   grade  ... settlement_status settlement_date
count    128412  128412  ...               111             111
unique       46       7  ...                 3               7
top      13.56%       A  ...            ACTIVE        Jul-2019
freq       6974   38011  ...                99              43

[4 rows x 35 columns]

In [23]:
Month = pd.to_datetime(df_Copy1["last_pymnt_d"], infer_datetime_format=True)
print(Month)

0        2019-07-01
1        2019-07-01
2        2019-06-01
3        2019-07-01
4        2019-07-01
5        2019-07-01
6        2019-08-01
7        2019-07-01
8        2019-05-01
9        2019-07-01
10       2019-07-01
11       2019-07-01
12       2019-07-01
13       2019-07-01
14       2019-07-01
15       2019-08-01
16       2019-08-01
17       2019-07-01
18       2019-07-01
19       2019-04-01
20       2019-07-01
21       2019-07-01
22       2019-07-01
23       2019-07-01
24       2019-07-01
25       2019-07-01
26       2019-07-01
27       2019-07-01
28       2019-07-01
29       2019-07-01
            ...
128382   2019-08-01
128383   2019-08-01
128384   2019-08-01
128385   2019-08-01
128386   2019-08-01
128387   2019-08-01
128388   2019-08-01
128389   2019-03-01
128390   2019-06-01
128391   2019-01-01
128392   2019-08-01
128393   2019-08-01
128394   2019-08-01
128395   2019-08-01
128396   2019-08-01
128397   2019-08-01
128398   2019-08-01
128399   2019-08-01
128400   2019-08-01
128401   2019-08-01
128402   2019-08-01
128403   2019-08-01
128404   2019-04-01
128405   2019-08-01
128406   2019-08-01
128407   2018-12-01
128408   2019-08-01
128409   2019-08-01
128410   2019-08-01
128411   2019-08-01
Name: last_pymnt_d, Length: 128412, dtype: datetime64[ns]

In [25]:
# Adding last_pymnt_d_month to df_Copy1
df_Copy1["last_pymnt_d_month"] = Month.dt.month
df_Copy1.head(4)

   id  member_id  ...  loan_status_is_great  last_pymnt_d_month
0 NaN        NaN  ...                     1                 7.0
1 NaN        NaN  ...                     1                 7.0
2 NaN        NaN  ...                     0                 6.0
3 NaN        NaN  ...                     1                 7.0

[4 rows x 146 columns]

In [26]:
df_Copy1["last_pymnt_d_year"] = Month.dt.year
df_Copy1.head(4)

   id  member_id  ...  last_pymnt_d_month  last_pymnt_d_year
0 NaN        NaN  ...                 7.0             2019.0
1 NaN        NaN  ...                 7.0             2019.0
2 NaN        NaN  ...                 6.0             2019.0
3 NaN        NaN  ...                 7.0             2019.0

[4 rows x 147 columns]

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01