<a href="https://colab.research.google.com/github/elcoreano/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module4-makefeatures/HANK_LS_DSPT3_114_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
##### Begin Working Here #####

import pandas as pd
import numpy as np

In [0]:
url = "https://raw.githubusercontent.com/jvns/pandas-cookbook/master/data/weather_2012.csv"

In [0]:
df_weather = pd.read_csv(url)
df_weather.head()

             Date/Time  Temp (C)  ...  Stn Press (kPa)               Weather
0  2012-01-01 00:00:00      -1.8  ...           101.24                   Fog
1  2012-01-01 01:00:00      -1.8  ...           101.24                   Fog
2  2012-01-01 02:00:00      -1.8  ...           101.26  Freezing Drizzle,Fog
3  2012-01-01 03:00:00      -1.5  ...           101.27  Freezing Drizzle,Fog
4  2012-01-01 04:00:00      -1.5  ...           101.23                   Fog

[5 rows x 8 columns]

In [0]:
df_weather['Date/Time'] = pd.to_datetime(df_weather['Date/Time'])

In [0]:
df_weather.set_index('Date/Time')

                     Temp (C)  ...               Weather
Date/Time                      ...
2012-01-01 00:00:00      -1.8  ...                   Fog
2012-01-01 01:00:00      -1.8  ...                   Fog
2012-01-01 02:00:00      -1.8  ...  Freezing Drizzle,Fog
2012-01-01 03:00:00      -1.5  ...  Freezing Drizzle,Fog
2012-01-01 04:00:00      -1.5  ...                   Fog
2012-01-01 05:00:00      -1.4  ...                   Fog
2012-01-01 06:00:00      -1.5  ...                   Fog
2012-01-01 07:00:00      -1.4  ...                   Fog
2012-01-01 08:00:00      -1.4  ...                   Fog
2012-01-01 09:00:00      -1.3  ...                   Fog
2012-01-01 10:00:00      -1.0  ...                   Fog
2012-01-01 11:00:00      -0.5  ...                   Fog
2012-01-01 12:00:00      -0.2  ...                   Fog
2012-01-01 13:00:00       0.2  ...                   Fog
2012-01-01 14:00:00       0.8  ...                   Fog
2012-01-01 15:00:00       1.8  ...                   Fog
2012-01-01 16:00:00       2.6  ...         Mostly Cloudy
2012-01-01 17:00:00       3.0  ...                Cloudy
2012-01-01 18:00:00       3.8  ...                  Rain
2012-01-01 19:00:00       3.1  ...                  Rain
2012-01-01 20:00:00       3.2  ...                Cloudy
2012-01-01 21:00:00       4.0  ...                Cloudy
2012-01-01 22:00:00       4.4  ...          Rain Showers
2012-01-01 23:00:00       5.3  ...                Cloudy
2012-01-02 00:00:00       5.2  ...          Rain Showers
2012-01-02 01:00:00       4.6  ...                Cloudy
2012-01-02 02:00:00       3.9  ...         Mostly Cloudy
2012-01-02 03:00:00       3.7  ...         Mostly Cloudy
2012-01-02 04:00:00       2.9  ...         Mostly Cloudy
2012-01-02 05:00:00       2.6  ...         Mostly Cloudy
...                       ...  ...                   ...
2012-12-30 18:00:00     -12.6  ...          Mainly Clear
2012-12-30 19:00:00     -13.4  ...          Mainly Clear
2012-12-30 20:00:00     -13.8  ...                 Clear
2012-12-30 21:00:00     -13.8  ...          Mainly Clear
2012-12-30 22:00:00     -13.7  ...          Mainly Clear
2012-12-30 23:00:00     -12.1  ...         Mostly Cloudy
2012-12-31 00:00:00     -11.1  ...                Cloudy
2012-12-31 01:00:00     -10.7  ...                Cloudy
2012-12-31 02:00:00     -10.1  ...                Cloudy
2012-12-31 03:00:00     -11.8  ...         Mostly Cloudy
2012-12-31 04:00:00     -10.5  ...                Cloudy
2012-12-31 05:00:00     -10.2  ...                Cloudy
2012-12-31 06:00:00      -9.7  ...                Cloudy
2012-12-31 07:00:00      -9.3  ...          Snow Showers
2012-12-31 08:00:00      -8.6  ...          Snow Showers
2012-12-31 09:00:00      -8.1  ...                  Snow
2012-12-31 10:00:00      -7.4  ...              Snow,Fog
2012-12-31 11:00:00      -6.7  ...                  Snow
2012-12-31 12:00:00      -5.8  ...                  Snow
2012-12-31 13:00:00      -4.6  ...                  Snow
2012-12-31 14:00:00      -3.4  ...                  Snow
2012-12-31 15:00:00      -2.3  ...                  Snow
2012-12-31 16:00:00      -1.4  ...                  Snow
2012-12-31 17:00:00      -1.1  ...                  Snow
2012-12-31 18:00:00      -1.3  ...                  Snow
2012-12-31 19:00:00       0.1  ...                  Snow
2012-12-31 20:00:00       0.2  ...                  Snow
2012-12-31 21:00:00      -0.5  ...                  Snow
2012-12-31 22:00:00      -0.2  ...                  Snow
2012-12-31 23:00:00       0.0  ...                  Snow

[8784 rows x 7 columns]

In [0]:
type(df_weather['Date/Time'])

pandas.core.series.Series

In [0]:
x_list = [1,2,3]
x_arr = np.array([1,2,3])
x_series = pd.Series([1,2,3])

In [0]:
for i in x_series:
  print(i)

1
2
3

In [0]:
df_weather['Weather'].str.contains('Snow')

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
8754    False
8755    False
8756    False
8757    False
8758    False
8759    False
8760    False
8761    False
8762    False
8763    False
8764    False
8765    False
8766    False
8767     True
8768     True
8769     True
8770     True
8771     True
8772     True
8773     True
8774     True
8775     True
8776     True
8777     True
8778     True
8779     True
8780     True
8781     True
8782     True
8783     True
Name: Weather, Length: 8784, dtype: bool

In [0]:
df_weather['Weather'].str.contains('Rain')

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18       True
19       True
20      False
21      False
22       True
23      False
24       True
25      False
26      False
27      False
28      False
29      False
        ...
8754    False
8755    False
8756    False
8757    False
8758    False
8759    False
8760    False
8761    False
8762    False
8763    False
8764    False
8765    False
8766    False
8767    False
8768    False
8769    False
8770    False
8771    False
8772    False
8773    False
8774    False
8775    False
8776    False
8777    False
8778    False
8779    False
8780    False
8781    False
8782    False
8783    False
Name: Weather, Length: 8784, dtype: bool

In [0]:
is_precipitation = df_weather['Weather'].str.contains('Rain') | df_weather['Weather'].str.contains('Snow')
is_precipitation

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18       True
19       True
20      False
21      False
22       True
23      False
24       True
25      False
26      False
27      False
28      False
29      False
        ...
8754    False
8755    False
8756    False
8757    False
8758    False
8759    False
8760    False
8761    False
8762    False
8763    False
8764    False
8765    False
8766    False
8767     True
8768     True
8769     True
8770     True
8771     True
8772     True
8773     True
8774     True
8775     True
8776     True
8777     True
8778     True
8779     True
8780     True
8781     True
8782     True
8783     True
Name: Weather, Length: 8784, dtype: bool

In [0]:
df_weather['is_precipitation'] = is_precipitation

In [0]:
df_weather.head()

            Date/Time  Temp (C)  ...               Weather  is_precipitation
0 2012-01-01 00:00:00      -1.8  ...                   Fog             False
1 2012-01-01 01:00:00      -1.8  ...                   Fog             False
2 2012-01-01 02:00:00      -1.8  ...  Freezing Drizzle,Fog             False
3 2012-01-01 03:00:00      -1.5  ...  Freezing Drizzle,Fog             False
4 2012-01-01 04:00:00      -1.5  ...                   Fog             False

[5 rows x 9 columns]

In [0]:
df_weather['Visibility (mi)'] = df_weather['Visibility (km)']*0.621

In [0]:
df_weather.head()

            Date/Time  Temp (C)  ...  is_precipitation  Visibility (mi)
0 2012-01-01 00:00:00      -1.8  ...             False           4.9680
1 2012-01-01 01:00:00      -1.8  ...             False           4.9680
2 2012-01-01 02:00:00      -1.8  ...             False           2.4840
3 2012-01-01 03:00:00      -1.5  ...             False           2.4840
4 2012-01-01 04:00:00      -1.5  ...             False           2.9808

[5 rows x 10 columns]

In [0]:
# Get LendingClub data

!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-09-13 00:59:43--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [        <=>         ]  21.58M  1.69MB/s    in 13s

2019-09-13 00:59:56 (1.68 MB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22631049]

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01