<a href="https://colab.research.google.com/github/DAVIDnHANG/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/module4-makefeatures/W1_A4_LS_DS_114_Make_Features_Assignment_TurnIn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LS_DS_114_Make_Features_Assignment.ipynb
LS_DS_114_Make_Features_Assignment.ipynb


ASSIGNMENT
Replicate the lesson code.

This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
Lambda Learning Method for DS - By Ryan Herr

Convert the term column from string to integer.
Make a column named loan_status_is_great. 
It should contain the integer 1 if loan_status is "Current" or "Fully Paid." 
Else it should contain the integer 0.

Make last_pymnt_d_month and last_pymnt_d_year columns.

In [4]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
!unzip LoanStats_2018Q4.csv.zip

--2019-09-06 04:16:12--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [       <=>          ]  21.58M  1.67MB/s    in 13s

2019-09-06 04:16:25 (1.66 MB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22631049]

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [5]:
#look at beginning of file useful fo header!
!head LoanStats_2018Q4.csv
#look at the end of the file useful for footheader
!tail LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 36 months"," 10.33%","324.23","B","B1","","< 1 year","MORTGAGE","280000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","974xx","OR","6.15","2","Jan-1996","0","18","","14","0","9082","38%","23","w","8289.30","8289.30","2261.0","2261.00","1710.70","550.30","0.0","0.0","0.0","Jul-2019","324.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","671","246828","1","3","2","3","1","48552","62","1","3","4923","46","23900","2","7","1","7","17631","11897","43.1","0","0","158","275","11","1","1","11","","11","","0","3","4","7","7","10","9","11","4","14","0","0","0","4","91.3","28.6","0","0","367828","61364","20900","54912","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 23.40%","155.68","E","E1","Security","3 years","RENT","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","070xx","NJ","26.33","0","Sep-2006","4","59","","15","0","5199","19.2%","20","w","3423.38","3423.38","1081.96","1081.96","576.62","505.34","0.0","0.0","0.0","Jul-2019","155.68","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","66926","5","4","3","4","5","61727","86","6","11","1353","68","27100","4","0","4","15","4462","20174","7.9","0","0","147","118","2","2","0","2","","0","","0","5","7","9","9","8","11","12","7","15","0","0","0","9","95","0","0","0","98655","66926","21900","71555","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 17.97%","180.69","D","D1","Administrative","6 years","MORTGAGE","59280","Source Verified","Dec-2018","Late (31-120 days)","n","","","debt_consolidation","Debt consolidation","490xx","MI","10.51","0","Apr-2011","0","","","8","0","4599","19.1%","13","w","4456.17","4456.17","895.96","895.96","543.83","352.13","0.0","0.0","0.0","Jun-2019","180.69","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","110299","0","1","0","2","14","7150","72","0","2","0","35","24100","1","5","0","4","18383","13800","0","0","0","87","92","15","14","2","77","","14","","0","0","3","3","3","4","6","7","3","8","0","0","0","0","100","0","0","0","136927","11749","13800","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 60 months"," 20.89%","620.81","D","D4","Operator","5 years","RENT","68107","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","672xx","KS","0.52","0","Feb-1997","0","","","5","0","976","13%","10","w","21353.16","21353.16","4307.45","4307.45","1646.84","2660.61","0.0","0.0","0.0","Jul-2019","620.81","Sep-2019","Aug-2019","1","","1","Individual","","","","0","2693","976","0","0","0","0","36","0","","3","4","0","13","7500","2","2","4","4","195","3300","0","0","0","237","262","10","10","0","10","","9","","0","0","1","3","4","3","5","7","1","5","0","0","0","3","100","0","0","0","7500","976","3300","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 23.40%","311.35","E","E1","Manager","10+ years","OWN","43000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","357xx","AL","33.24","0","Jan-1995","0","","107","8","1","9019","81.3%","16","w","6846.83","6846.83","2163.85","2163.85","1153.17","1010.68","0.0","0.0","0.0","Jul-2019","311.35","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","169223","0","3","2","2","7","22059","69","0","0","2174","72","11100","1","1","1","2","21153","126","94.5","0","0","148","287","44","7","1","51","","7","","0","1","4","1","2","8","4","7","4","8","0","0","0","2","100","100","1","0","199744","31078","2300","32206","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","32075","32075","32075"," 60 months"," 11.80%","710.26","B","B4","Nursing Supervisor","10+ years","MORTGAGE","150000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","231xx","VA","22.21","0","Aug-2005","0","","","17","0","19077","32%","24","w","29228.12","29228.12","4940.28","4940.28","2846.88","2093.40","0.0","0.0","0.0","Jul-2019","710.26","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","272667","1","4","1","1","9","37558","47","1","1","3910","41","59600","1","2","0","3","16039","10446","47.8","0","0","160","70","4","4","2","27","","14","","0","4","10","4","4","8","12","14","10","17","0","0","0","2","100","50","0","0","360433","56635","20000","80125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","9600","9600","9600"," 36 months"," 12.98%","323.37","B","B5","","n/a","MORTGAGE","35704","Not Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","401xx","KY","0.84","0","Nov-2003","0","69","","5","0","748","11.5%","23","w","8012.51","8012.51","2287.83","2287.83","1587.49","700.34","0.0","0.0","0.0","Aug-2019","323.37","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","748","0","0","0","0","44","0","","0","3","748","12","6500","0","0","1","3","150","3452","17.8","0","0","181","100","13","13","0","16","","3","","0","1","1","2","2","16","5","7","1","5","0","0","0","0","95.5","0","0","0","6500","748","4200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 18.94%","777.23","D","D2","Postmaster ","10+ years","MORTGAGE","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","713xx","LA","26.52","0","Jun-1987","0","71","75","13","1","12315","24.2%","44","w","19969.40","19969.40","12893.26","12893.26","10030.60","2862.66","0.0","0.0","0.0","Jul-2019","777.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1208","321915","4","4","2","3","3","87153","88","4","5","998","57","50800","2","15","2","10","24763","13761","8.3","0","0","163","378","4","3","3","4","","4","","0","2","4","4","9","27","8","14","4","13","0","0","0","6","95","0","1","0","372872","99468","15000","94072","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","4264.17","4264.17","1891.55","1891.55","1335.83","555.72","0.0","0.0","0.0","Aug-2019","190.21","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","7655.00","7655.00","3459.26","3459.26","2345.00","1114.26","0.0","0.0","0.0","Aug-2019","346.76","Sep-2019","Aug-2019","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3807.30","3807.30","1694.53","1694.53","1192.70","501.83","0.0","0.0","0.0","Aug-2019","169.83","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","7544.75","7356.13","3261.44","3179.90","2455.25","806.19","0.0","0.0","0.0","Aug-2019","327.68","Sep-2019","Aug-2019","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","7706.67","7706.67","3551.41","3551.41","2293.33","1258.08","0.0","0.0","0.0","Aug-2019","356.08","Sep-2019","Aug-2019","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

# Original Data

In [6]:
import pandas as pd

#set the amount of rows/columns
pd.set_option('display.max_rows',50)
pd.set_option('display.max_columns',50)


#think about the header and the footheader
df_LoanStats = pd.read_csv('LoanStats_2018Q4.csv', header=1, skipfooter = 2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':

# Dropped ID, memberId desc and URL
and loan_status_is_great function is here

In [36]:
import pandas as pd
import numpy as np
df_LoanStatsDropped=df_LoanStats.drop(columns=['id','member_id','desc','url'])
df_LoanStatsDropped.head(25)
def remove_percent_to_float(string):
  return float(string.strip('%'))

df_LoanStatsDropped['int_rate']=df_LoanStatsDropped['int_rate'].apply(remove_percent_to_float)
df_LoanStatsDropped




#######To do using pd.np.where(df[]. str.contains)
df_LoanStatsDropped["loan_status_is_great"] = pd.np.where(df_LoanStatsDropped["loan_status"].str.contains("Current"), "1",
                                                       pd.np.where(df_LoanStatsDropped["loan_status"].str.contains("Fully Paid."),"1","0"))
                                                       
#df_LoanStatsDropped["loan_status_is_great"]
#print(df_LoanStatsDropped["loan_status"])
df_LoanStatsDropped
##When I print out the dataframe the column header name is 0?

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,...,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_is_great
0,10000,10000,10000.0,36 months,10.33,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
1,4000,4000,4000.0,36 months,23.40,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
2,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
3,23000,23000,23000.0,60 months,20.89,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
4,8000,8000,8000.0,36 months,23.40,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
5,32075,32075,32075.0,60 months,11.80,710.26,B,B4,Nursing Supervisor,10+ years,MORTGAGE,150000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,231xx,VA,22.21,0,Aug-2005,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
6,9600,9600,9600.0,36 months,12.98,323.37,B,B5,NaN,NaN,MORTGAGE,35704.0,Not Verified,Dec-2018,Current,n,home_improvement,Home improvement,401xx,KY,0.84,0,Nov-2003,0,69.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
7,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,713xx,LA,26.52,0,Jun-1987,0,71.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
8,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,109xx,NY,18.24,0,Apr-2001,1,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
9,12000,12000,12000.0,60 months,13.56,276.49,C,C1,NaN,< 1 year,MORTGAGE,40000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,180xx,PA,19.23,0,Aug-2005,2,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
10,10000,10000,10000.0,60 months,19.92,264.50,D,D3,Material Handler,10+ years,MORTGAGE,80000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,648xx,MO,20.67,0,Apr-2005,0,37.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
11,16000,16000,16000.0,60 months,17.97,406.04,D,D1,Instructional Coordinator,5 years,MORTGAGE,51000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,284xx,NC,21.91,0,Oct-2005,1,52.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
12,16000,16000,16000.0,60 months,26.31,481.99,E,E4,Financial Relationship Associate,< 1 year,RENT,33000.0,Source Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,290xx,SC,33.62,0,Sep-2010,1,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
13,15000,15000,14975.0,60 months,14.47,352.69,C,C2,NaN,NaN,MORTGAGE,30000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,756xx,TX,41.60,0,Oct-1999,0,NaN,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
14,13000,13000,13000.0,36 months,23.40,505.95,E,E1,Sale Representative,2 years,MORTGAGE,90000.0,Verified,Dec-2018,Current,n,other,Other,191xx,PA,39.73,0,May-2007,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
15,9600,9600,9600.0,36 months,23.40,373.62,E,E1,driver coordinator,9 years,RENT,65000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,265xx,WV,23.01,1,Sep-2003,0,16.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
16,3500,3500,3500.0,36 months,20.89,131.67,D,D4,gas attendant,10+ years,MORTGAGE,40000.0,Source Verified,Dec-2018,Current,n,car,Car financing,078xx,NJ,9.09,0,Oct-2004,1,24.0,...,0.0,46.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
17,25000,25000,25000.0,60 months,16.91,620.11,C,C5,Processor,10+ years,MORTGAGE,23878.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,453xx,OH,6.26,0,Oct-2010,0,NaN,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
18,16000,16000,16000.0,60 months,20.89,431.87,D,D4,Neonatal Nurse Practitioner,4 years,MORTGAGE,120000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,720xx,AR,27.57,1,Jul-2005,0,8.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
19,13000,13000,13000.0,60 months,14.47,305.67,C,C2,Stationary Engineer,10+ years,MORTGAGE,75000.0,Not Verified,Dec-2018,Fully Paid,n,debt_consolidation,Debt consolidation,741xx,OK,26.16,0,Feb-2001,1,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
20,10000,10000,10000.0,36 months,13.56,339.65,C,C1,NaN,< 1 year,MORTGAGE,65000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,937xx,CA,10.62,0,Dec-2004,1,30.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
21,13000,13000,13000.0,36 months,14.47,447.29,C,C2,Exhibits director,10+ years,MORTGAGE,55000.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,611xx,IL,10.58,0,Oct-2001,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
22,7000,7000,7000.0,36 months,12.98,235.80,B,B5,Worship Director,4 years,MORTGAGE,102500.0,Not Verified,Dec-2018,Current,n,house,Home buying,436xx,OH,15.20,0,Dec-2002,0,38.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
23,3300,3300,3300.0,36 months,23.40,128.44,E,E1,Program Manager,3 years,RENT,49700.0,Source Verified,Dec-2018,Current,n,vacation,Vacation,310xx,GA,14.32,0,Nov-2006,1,43.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
24,20000,20000,20000.0,60 months,11.80,442.88,B,B4,NaN,NaN,MORTGAGE,47590.0,Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,156xx,PA,9.53,0,Sep-1999,0,62.0,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128387,6000,6000,6000.0,36 months,11.55,198.00,B,B4,ENGINEER,2 years,RENT,90000.0,Not Verified,Oct-2018,Current,n,credit_card,Credit card refinancing,076xx,NJ,1.64,0,Sep-2010,1,53.0,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128388,20000,20000,20000.0,36 months,8.46,630.99,A,A5,Welder/Blacksmith,10+ years,MORTGAGE,97000.0,Source Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,604xx,IL,15.59,0,Jul-1999,1,64.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128389,6000,6000,5750.0,36 months,11.55,198.00,B,B4,RN Supervisor,6 years,RENT,70000.0,Not Verified,Oct-2018,Charged Off,n,medical,Medical expenses,912xx,CA,11.52,4,Dec-1993,0,17.0,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
128390,24000,24000,24000.0,36 months,19.92,890.95,D,D3,Corrections officer,10+ years,RENT,34000.0,Verified,Oct-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,344xx,FL,74.09,0,Jun-2006,0,NaN,...,1.0,75.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
128391,35000,35000,34975.0,36 months,6.67,1075.43,A,A2,NaN,NaN,MORTGAGE,85000.0,Source Verified,Oct-2018,Fully Paid,n,debt_consolidation,Debt consolidation,301xx,GA,22.15,0,Apr-1997,2,54.0,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
128392,6500,6500,6500.0,36 months,26.31,262.97,E,E4,Merchandise Team Captain,10+ years,MORTGAGE,35000.0,Verified,Oct-2018,Current,n,home_improvement,Home improvement,328xx,FL,39.51,0,Mar-2004,0,70.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128393,6500,6500,6500.0,36 months,16.91,231.46,C,C5,"Senior Accountant, Fixed Assets Acctg",7 years,RENT,74160.0,Source Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,600xx,IL,27.79,0,Jun-2006,0,38.0,...,0.0,58.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128394,5000,5000,5000.0,36 months,6.11,152.36,A,A1,Implementation Manager,9 years,MORTGAGE,82000.0,Not Verified,Oct-2018,Current,n,other,Other,750xx,TX,1.35,0,Feb-2005,0,33.0,...,0.0,13.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128395,22000,22000,22000.0,36 months,11.55,726.00,B,B4,Sr. application analyst,10+ years,MORTGAGE,72000.0,Source Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,481xx,MI,46.98,0,Jun-1999,0,26.0,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128396,24000,24000,24000.0,60 months,15.02,571.22,C,C3,Instructional Technology Specialist,10+ years,MORTGAGE,60000.0,Not Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,750xx,TX,9.72,0,Apr-1999,1,43.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128397,20000,20000,20000.0,60 months,15.02,476.01,C,C3,Technical Supvervisor,10+ years,MORTGAGE,75000.0,Verified,Oct-2018,Fully Paid,n,credit_card,Credit card refinancing,786xx,TX,24.82,0,Apr-1991,2,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
128398,12000,12000,12000.0,60 months,18.94,310.90,D,D2,Senior Business Account Executive,6 years,RENT,128000.0,Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,937xx,CA,13.32,0,Nov-2007,1,46.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128399,5000,5000,5000.0,36 months,15.02,173.38,C,C3,Tech,10+ years,MORTGAGE,35000.0,Source Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,324xx,FL,31.76,2,Jun-2003,0,15.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128400,20000,20000,20000.0,60 months,15.02,476.01,C,C3,production supervisor,10+ years,MORTGAGE,80000.0,Not Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,117xx,NY,16.94,0,Oct-2005,0,NaN,...,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128401,20000,20000,20000.0,36 months,11.55,660.00,B,B4,secondary opps/lead coater,10+ years,OWN,45000.0,Not Verified,Oct-2018,Current,n,home_improvement,Home improvement,015xx,MA,22.13,0,Dec-2003,0,41.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128402,17500,17500,17500.0,60 months,22.35,486.82,D,D5,NaN,NaN,RENT,25000.0,Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,640xx,MO,27.75,0,Oct-2001,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128403,5000,5000,5000.0,36 months,16.14,176.14,C,C4,NaN,NaN,OWN,9200.0,Source Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,365xx,AL,23.50,0,Apr-2015,1,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128404,5000,5000,5000.0,36 months,16.14,176.14,C,C4,Oncology Medical Assistant,3 years,MORTGAGE,46400.0,Source Verified,Oct-2018,Fully Paid,n,debt_consolidation,Debt consolidation,338xx,FL,16.85,0,Nov-2003,0,29.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
128405,22000,22000,22000.0,60 months,7.84,444.40,A,A4,Owner,10+ years,MORTGAGE,55000.0,Not Verified,Oct-2018,Current,n,other,Other,982xx,WA,2.18,0,Apr-1987,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128406,5600,5600,5600.0,36 months,13.56,190.21,C,C1,NaN,NaN,RENT,15600.0,Not Verified,Oct-2018,Current,n,credit_card,Credit card refinancing,836xx,ID,15.31,0,Aug-2012,0,NaN,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128407,23000,23000,23000.0,36 months,15.02,797.53,C,C3,Tax Consultant,10+ years,MORTGAGE,75000.0,Source Verified,Oct-2018,Charged Off,n,debt_consolidation,Debt consolidation,352xx,AL,20.95,1,Aug-1985,2,22.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0
128408,10000,10000,10000.0,36 months,15.02,346.76,C,C3,security guard,5 years,MORTGAGE,38000.0,Not Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,443xx,OH,13.16,3,Jul-1982,0,6.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128409,5000,5000,5000.0,36 months,13.56,169.83,C,C1,Payoff Clerk,10+ years,MORTGAGE,35360.0,Not Verified,Oct-2018,Current,n,debt_consolidation,Debt consolidation,381xx,TN,11.30,1,Jun-2006,0,21.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128410,10000,10000,9750.0,36 months,11.06,327.68,B,B3,NaN,NaN,RENT,44400.0,Source Verified,Oct-2018,Current,n,credit_card,Credit card refinancing,980xx,WA,11.78,0,Oct-2008,2,40.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1
128411,10000,10000,10000.0,36 months,16.91,356.08,C,C5,Key Accounts Manager,2 years,RENT,80000.0,Not Verified,Oct-2018,Current,n,other,Other,021xx,MA,17.72,1,Sep-2006,0,14.0,...,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1

**if else statement for goal? and apply
**

In [72]:
#for i in df_LoanStatsDropped['loan_status']:
#  print(df_LoanStatsDropped['loan_status']=="Current")
def loan_status_is_great(string):
  if ((string=="Current") | (string=="Fully Paid.")):
    return int(1)
  else:
    return int(0)
#replacing all columns with apply function
df_LoanStatsDropped['loan_status_is_greats'] = df_LoanStatsDropped['loan_status'].apply(loan_status_is_great)
df_LoanStatsDropped['loan_status_is_greats']  #added at end of row. use .insert(x,y,value) to replace at a specific spot

0         1
1         1
2         0
3         1
4         1
5         1
6         1
7         1
8         0
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        0
20        1
21        1
22        1
23        1
24        1
         ..
128387    1
128388    1
128389    0
128390    0
128391    0
128392    1
128393    1
128394    1
128395    1
128396    1
128397    0
128398    1
128399    1
128400    1
128401    1
128402    1
128403    1
128404    0
128405    1
128406    1
128407    0
128408    1
128409    1
128410    1
128411    1
Name: loan_status_is_greats, Length: 128412, dtype: int64

Convert "term" to int

In [73]:
#replace all months with empty space
def remove_months_andConvert_float(string):
  return int(string.replace('months',''))

df_LoanStatsDropped['term'] = df_LoanStatsDropped['term'].apply(remove_months_andConvert_float)
df_LoanStatsDropped['term']

0         36
1         36
2         36
3         60
4         36
5         60
6         36
7         60
8         36
9         60
10        60
11        60
12        60
13        60
14        36
15        36
16        36
17        60
18        60
19        60
20        36
21        36
22        36
23        36
24        60
          ..
128387    36
128388    36
128389    36
128390    36
128391    36
128392    36
128393    36
128394    36
128395    36
128396    60
128397    60
128398    60
128399    36
128400    60
128401    36
128402    60
128403    36
128404    36
128405    60
128406    36
128407    36
128408    36
128409    36
128410    36
128411    36
Name: term, Length: 128412, dtype: int64

In [97]:
import datetime

df_LoanStatsDropped["issue_d"] = pd.to_datetime(df_LoanStatsDropped['issue_d'], infer_datetime_format=True)
df_LoanStatsDropped["issue_d"]
#let grab year
#dt mean format the date, only grab year
df_LoanStatsDropped['issue_d'].dt.year
#dt mean format the date, only grab month
df_LoanStatsDropped['issue_d'].dt.month

#add 36 months to the issue_d to get the last payment of the month
df_LoanStatsDropped["last_pymnt_date"]=df_LoanStatsDropped['issue_d'] + datetime.timedelta(36*365/12)
df_LoanStatsDropped["last_pymnt_d_month"]=df_LoanStatsDropped['last_pymnt_date'].dt.month
df_LoanStatsDropped["last_pymnt_d_month"]
#Yes the df which has been adjusted to obtained the year.
df_LoanStatsDropped["last_pymnt_d_year"]=df_LoanStatsDropped['last_pymnt_date'].dt.year
df_LoanStatsDropped["last_pymnt_d_year"]

0         2021
1         2021
2         2021
3         2021
4         2021
5         2021
6         2021
7         2021
8         2021
9         2021
10        2021
11        2021
12        2021
13        2021
14        2021
15        2021
16        2021
17        2021
18        2021
19        2021
20        2021
21        2021
22        2021
23        2021
24        2021
          ...
128387    2021
128388    2021
128389    2021
128390    2021
128391    2021
128392    2021
128393    2021
128394    2021
128395    2021
128396    2021
128397    2021
128398    2021
128399    2021
128400    2021
128401    2021
128402    2021
128403    2021
128404    2021
128405    2021
128406    2021
128407    2021
128408    2021
128409    2021
128410    2021
128411    2021
Name: last_pymnt_d_year, Length: 128412, dtype: int64

# just some commands to help ID row/column, and DF

In [0]:
##some useful commands
#list all the columns
df_LoanStats.columns 

#give the number of 0 = rows, then 1= columns in (0,1)#
#df_LoanStats.shape

#df_LoanStats.shape[1]

#list all the columns
#list(df_LoanStats.columns)

#looks for all null
#df_LoanStats.isnull().sum()           
#looks for only na
#df_LoanStats.isna().sum()
#here is how you sort stuff
#.sort_values(ascending=False)
#df_LoanStats.isna().sum().sort_values(ascending=False)




#LIST

#df_LoanStats.dtypes

# Convert strings to float functionally

In [0]:
int_rate = '15.02 months'
int_rate[:-1] # use index
int_rate.strip('%') #remove last or first
int_rate.replace('.','')#remove removing
def remove_percent_to_float(string):
  return float(string.strip(%))
remove_precent_to_float(int_rate)

In [0]:
#int_list=['15.02%','13.56%','16.91%']
#[remove_precent_to_float(item) for item in int_list(df_LoanStatsDropped['int_rate'])]

**STRETCH OPTIONS**
You can do more with the LendingClub or Instacart datasets.
​
LendingClub options:
​
There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
Modify the emp_title column to replace titles with 'Other' if the title is not in the top 20.
Take initiatve and work on your own ideas!
Instacart options:
​
Read Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera, especially the Feature Engineering section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
Read and replicate parts of Simple Exploration Notebook - Instacart. (It's the Python Notebook with the most upvotes for this Kaggle competition.)
Take initiative and work on your own ideas!
You can uncomment and run the cells below to re-download and extract the Instacart data