_Lambda School Data Science_

# Make features

Objectives
-  understand the purpose of feature engineering
-  work with strings in pandas
- work with dates and times in pandas

Links
- [Feature Engineering](https://en.wikipedia.org/wiki/Feature_engineering)
- Python Data Science Handbook
  - [Chapter 3.10](https://jakevdp.github.io/PythonDataScienceHandbook/03.10-working-with-strings.html), Vectorized String Operations
  - [Chapter 3.11](https://jakevdp.github.io/PythonDataScienceHandbook/03.11-working-with-time-series.html), Working with Time Series

## Get LendingClub data

[Source](https://www.lendingclub.com/info/download-data.action)

In [180]:
import pandas as pd

In [181]:
#https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

In [182]:
#!unzip LoanStats_2018Q4.csv.zip

In [183]:
path = '/Users/ridleyleisy/Documents/lambda/unit_one/DS-Unit-1-Sprint-1-Dealing-With-Data/thursday-make-features/LoanStats_2018Q4.csv'

In [184]:
df = pd.read_csv(path,skiprows=1,skipfooter=2)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

FileNotFoundError: [Errno 2] No such file or directory: '/Users/ridleyleisy/Documents/lambda/unit_one/DS-Unit-1-Sprint-1-Dealing-With-Data/thursday-make-features/LoanStats_2018Q4.csv'

## Load LendingClub data

pandas documentation
- [`read_csv`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html)
- [`options.display`](https://pandas.pydata.org/pandas-docs/stable/options.html#available-options)

In [105]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2500,2500,2500.0,36 months,13.56%,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,12000,12000,12000.0,60 months,13.56%,276.49,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,15000,15000,14975.0,60 months,14.47%,352.69,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,16000,16000,16000.0,60 months,17.97%,406.04,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
df.isnull().sum().sort_values(ascending=False)

id                                            128412
member_id                                     128412
url                                           128412
desc                                          128412
hardship_loan_status                          128411
hardship_amount                               128411
hardship_start_date                           128411
hardship_end_date                             128411
payment_plan_start_date                       128411
hardship_length                               128411
hardship_dpd                                  128411
hardship_payoff_balance_amount                128411
orig_projected_additional_accrued_interest    128411
hardship_status                               128411
hardship_last_payment_amount                  128411
hardship_reason                               128411
hardship_type                                 128411
deferral_term                                 128411
settlement_percentage                         128407
settlement_term                               128407
settlement_status                             128407
debt_settlement_flag_date                     128407
settlement_amount                             128407
settlement_date                               128407
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
sec_app_num_rev_accts                         111630
annual_inc_joint                              111630
                                               ...
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
hardship_flag                                      0
num_accts_ever_120_pd                              0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
mo_sin_rcnt_rev_tl_op                              0
application_type                                   0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
open_il_12m                                        0
debt_settlement_flag                               0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
inq_fi                                             0
inq_last_12m                                       0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
mo_sin_old_rev_tl_op                               0
total_cu_tl                                        0
Length: 145, dtype: int64

## Work with strings

For machine learning, we usually want to replace strings with numbers.

We can get info about which columns have a datatype of "object" (strings)

In [107]:
df

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,2500,2500,2500.0,36 months,13.56%,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,12000,12000,12000.0,60 months,13.56%,276.49,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,15000,15000,14975.0,60 months,14.47%,352.69,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,16000,16000,16000.0,60 months,17.97%,406.04,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,9600,9600,9600.0,36 months,23.40%,373.62,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,3500,3500,3500.0,36 months,20.89%,131.67,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,9600,9600,9600.0,36 months,12.98%,323.37,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,16000,16000,16000.0,60 months,26.31%,481.99,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,30000,30000,30000.0,60 months,18.94%,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,10000,10000,10000.0,60 months,19.92%,264.50,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,32075,32075,32075.0,60 months,11.80%,710.26,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,13000,13000,13000.0,36 months,23.40%,505.95,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,35000,35000,35000.0,60 months,15.02%,833.02,C,C3,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,40000,40000,40000.0,60 months,11.31%,875.90,B,B3,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,8000,8000,8000.0,36 months,10.33%,259.38,B,B1,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,24000,24000,24000.0,60 months,27.27%,736.73,E,E5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,25000,25000,25000.0,60 months,16.14%,609.82,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,30000,30000,30000.0,60 months,26.31%,903.73,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,24000,24000,24000.0,36 months,15.02%,832.21,C,C3,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,4000,4000,4000.0,36 months,18.94%,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,28000,28000,28000.0,36 months,11.31%,920.81,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,24000,24000,24000.0,60 months,11.31%,525.54,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,12000,12000,12000.0,60 months,14.47%,282.16,C,C2,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,14000,14000,14000.0,36 months,16.14%,493.17,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,16000,16000,16000.0,36 months,14.47%,550.51,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128382,NaN,NaN,25000,25000,25000.0,60 months,26.31%,753.11,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128383,NaN,NaN,24000,24000,24000.0,36 months,13.56%,815.15,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128384,NaN,NaN,8000,8000,8000.0,36 months,16.91%,284.87,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128385,NaN,NaN,10000,10000,10000.0,36 months,17.97%,361.38,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128386,NaN,NaN,6000,6000,6000.0,36 months,11.55%,198.00,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128387,NaN,NaN,17000,17000,17000.0,60 months,17.97%,431.42,D,D1,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
128388,NaN,NaN,20000,20000,20000.0,36 months,8.46%,630.99,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128389,NaN,NaN,24000,24000,24000.0,36 months,19.92%,890.95,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128390,NaN,NaN,35000,35000,34975.0,36 months,6.67%,1075.43,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128391,NaN,NaN,6500,6500,6500.0,36 months,26.31%,262.97,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128392,NaN,NaN,6500,6500,6500.0,36 months,16.91%,231.46,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128393,NaN,NaN,5000,5000,5000.0,36 months,6.11%,152.36,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128394,NaN,NaN,6000,6000,5750.0,36 months,11.55%,198.00,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128395,NaN,NaN,22000,22000,22000.0,36 months,11.55%,726.00,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128396,NaN,NaN,24000,24000,24000.0,60 months,15.02%,571.22,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128397,NaN,NaN,20000,20000,20000.0,60 months,15.02%,476.01,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128398,NaN,NaN,12000,12000,12000.0,60 months,18.94%,310.90,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128399,NaN,NaN,5000,5000,5000.0,36 months,15.02%,173.38,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128400,NaN,NaN,20000,20000,20000.0,60 months,15.02%,476.01,C,C3,...,NaN,NaN,DirectPay,N,NaN,NaN,NaN,NaN,NaN,NaN
128401,NaN,NaN,5000,5000,5000.0,36 months,16.14%,176.14,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128402,NaN,NaN,17500,17500,17500.0,60 months,22.35%,486.82,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128403,NaN,NaN,20000,20000,20000.0,36 months,11.55%,660.00,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128404,NaN,NaN,22000,22000,22000.0,60 months,7.84%,444.40,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128405,NaN,NaN,5000,5000,5000.0,36 months,16.14%,176.14,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128406,NaN,NaN,5600,5600,5600.0,36 months,13.56%,190.21,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128407,NaN,NaN,23000,23000,23000.0,36 months,15.02%,797.53,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128408,NaN,NaN,10000,10000,10000.0,36 months,15.02%,346.76,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128409,NaN,NaN,5000,5000,5000.0,36 months,13.56%,169.83,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128410,NaN,NaN,10000,10000,9750.0,36 months,11.06%,327.68,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
128411,NaN,NaN,10000,10000,10000.0,36 months,16.91%,356.08,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

### Convert `int_rate`

Define a function to remove percent signs from strings and convert to floats

In [108]:
pd.to_numeric(df['int_rate'].str.strip('%'))

0         10.33
1         13.56
2         13.56
3         14.47
4         17.97
5         23.40
6         23.40
7         20.89
8         12.98
9         23.40
10        26.31
11        18.94
12        19.92
13        17.97
14        20.89
15        11.80
16        23.40
17        15.02
18        11.31
19        10.33
20        27.27
21        16.14
22        26.31
23        15.02
24        18.94
25        11.31
26        11.31
27        14.47
28        16.14
29        14.47
          ...
128382    26.31
128383    13.56
128384    16.91
128385    17.97
128386    11.55
128387    17.97
128388     8.46
128389    19.92
128390     6.67
128391    26.31
128392    16.91
128393     6.11
128394    11.55
128395    11.55
128396    15.02
128397    15.02
128398    18.94
128399    15.02
128400    15.02
128401    16.14
128402    22.35
128403    11.55
128404     7.84
128405    16.14
128406    13.56
128407    15.02
128408    15.02
128409    13.56
128410    11.06
128411    16.91
Name: int_rate, Length: 128412, dtype: float64

Apply the function to the `int_rate` column

### Clean `emp_title`

Look at top 20 titles

In [109]:
df['emp_title'].value_counts()

Teacher                             2090
Manager                             1773
Registered Nurse                     952
Driver                               924
RN                                   726
Supervisor                           697
Sales                                580
Project Manager                      526
General Manager                      523
Office Manager                       521
Owner                                420
Director                             402
Operations Manager                   387
Truck Driver                         387
Nurse                                326
Engineer                             325
Sales Manager                        304
manager                              301
Supervisor                           270
Administrative Assistant             269
Accountant                           268
Server                               265
Vice President                       261
Mechanic                             258
Account Manager                      254
Police Officer                       252
teacher                              249
Technician                           248
Manager                              246
Store Manager                        222
                                    ...
Senior network engineer                1
SVP Commercial Finance                 1
Bomb technician                        1
Brick Layer                            1
 Private Client Banker                 1
Driver Safety Hearing Officer          1
Clinical Services Rep                  1
SAP FICO business system analyst       1
Civil Engineering Associate            1
Dental tech                            1
Senior Test Tech                       1
Media Center Lead                      1
Employee Benefits Specialist           1
Customer Support Manager               1
Access Coordinator                     1
Shop parts Counterman                  1
regulatory                             1
Tech Order Manager                     1
Mechianist                             1
 Consultant                            1
Microwave tube generalist              1
Safety & Compliance Supervisor         1
Electromechanical technician           1
Sr. Vice President                     1
Documentation Analyst                  1
Recovery Agent                         1
Pre Sales                              1
Sales Professional                     1
recon mgr                              1
IT helpdesk                            1
Name: emp_title, Length: 43892, dtype: int64

How often is `emp_title` null?

In [110]:
df['emp_title'].isnull().sum()

20947

Clean the title and handle missing values

In [111]:
df['emp_title'] = df['emp_title'].str.lower()

### Create `emp_title_manager`

pandas documentation: [`str.contains`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.contains.html)

## Work with dates

pandas documentation
- [to_datetime](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html)
- [Time/Date Components](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#time-date-components) "You can access these properties via the `.dt` accessor"

# ASSIGNMENT

- Replicate the lesson code.

- Convert the `term` column from string to integer.

- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [178]:
pd.options.display.max_rows = 50
pd.options.display.max_columns = 50

In [123]:
df['term'] = df['term'].str.strip()
def strip_months(string):
    string = int(string[0:2])
    return string

df['term'] = df['term'].apply(strip_months)

In [161]:
def loan_status(string):
    if string == 'Current':
        string = 1
    elif string == 'Fully Paid':
        string = 1
    else:
        string = 0
    return string
df['loan_status_is_great'] = df['loan_status'].apply(loan_status)

In [167]:
df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'])

In [176]:
df['last_pymnt_d_month'] = df['last_pymnt_d'].dt.month
df['last_pymnt_d_year'] = df['last_pymnt_d'].dt.year

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [179]:

'''
Finishing up a medium article that I want to focus on. 

'''

'\nFinishing up a medium article that I want to focus on. \n\n'

In [ ]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [ ]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [ ]:
# %cd instacart_2017_05_01