<a href="https://colab.research.google.com/github/maiormarso/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/Copy_of_Maior_Marso_LS_DS_114_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
##### Begin Working Here #####

In [88]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
!unzip LoanStats_2018Q4.csv.zip
!head LoanStats_2018Q4.csv

--2019-08-09 04:45:16--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.4’

LoanStats_2018Q4.cs     [                <=> ]  21.56M   891KB/s    in 25s

2019-08-09 04:45:42 (877 KB/s) - ‘LoanStats_2018Q4.csv.zip.4’ saved [22606280]

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 36 months"," 10.33%","324.23","B","B1","","< 1 year","MORTGAGE","280000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","974xx","OR","6.15","2","Jan-1996","0","18","","14","0","9082","38%","23","w","8540.01","8540.01","1936.77","1936.77","1459.99","476.78","0.0","0.0","0.0","Jul-2019","324.23","Jul-2019","Jul-2019","0","","1","Individual","","","","0","671","246828","1","3","2","3","1","48552","62","1","3","4923","46","23900","2","7","1","7","17631","11897","43.1","0","0","158","275","11","1","1","11","","11","","0","3","4","7","7","10","9","11","4","14","0","0","0","4","91.3","28.6","0","0","367828","61364","20900","54912","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 23.40%","155.68","E","E1","Security","3 years","RENT","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","070xx","NJ","26.33","0","Sep-2006","4","59","","15","0","5199","19.2%","20","w","3510.60","3510.60","926.28","926.28","489.40","436.88","0.0","0.0","0.0","Jul-2019","155.68","Jul-2019","Jul-2019","0","","1","Individual","","","","0","0","66926","5","4","3","4","5","61727","86","6","11","1353","68","27100","4","0","4","15","4462","20174","7.9","0","0","147","118","2","2","0","2","","0","","0","5","7","9","9","8","11","12","7","15","0","0","0","9","95","0","0","0","98655","66926","21900","71555","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 17.97%","180.69","D","D1","Administrative","6 years","MORTGAGE","59280","Source Verified","Dec-2018","Late (16-30 days)","n","","","debt_consolidation","Debt consolidation","490xx","MI","10.51","0","Apr-2011","0","","","8","0","4599","19.1%","13","w","4456.17","4456.17","895.96","895.96","543.83","352.13","0.0","0.0","0.0","Jun-2019","180.69","Jul-2019","Jul-2019","0","","1","Individual","","","","0","0","110299","0","1","0","2","14","7150","72","0","2","0","35","24100","1","5","0","4","18383","13800","0","0","0","87","92","15","14","2","77","","14","","0","0","3","3","3","4","6","7","3","8","0","0","0","0","100","0","0","0","136927","11749","13800","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 60 months"," 20.89%","620.81","D","D4","Operator","5 years","RENT","68107","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","672xx","KS","0.52","0","Feb-1997","0","","","5","0","976","13%","10","w","21597.84","21597.84","3686.64","3686.64","1402.16","2284.48","0.0","0.0","0.0","Jul-2019","620.81","Jul-2019","Jul-2019","1","","1","Individual","","","","0","2693","976","0","0","0","0","36","0","","3","4","0","13","7500","2","2","4","4","195","3300","0","0","0","237","262","10","10","0","10","","9","","0","0","1","3","4","3","5","7","1","5","0","0","0","3","100","0","0","0","7500","976","3300","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 23.40%","311.35","E","E1","Manager","10+ years","OWN","43000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","357xx","AL","33.24","0","Jan-1995","0","","107","8","1","9019","81.3%","16","w","7021.26","7021.26","1852.5","1852.50","978.74","873.76","0.0","0.0","0.0","Jul-2019","311.35","Jul-2019","Jul-2019","0","","1","Individual","","","","0","0","169223","0","3","2","2","7","22059","69","0","0","2174","72","11100","1","1","1","2","21153","126","94.5","0","0","148","287","44","7","1","51","","7","","0","1","4","1","2","8","4","7","4","8","0","0","0","2","100","100","1","0","199744","31078","2300","32206","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","32075","32075","32075"," 60 months"," 11.80%","710.26","B","B4","Nursing Supervisor","10+ years","MORTGAGE","150000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","231xx","VA","22.21","0","Aug-2005","0","","","17","0","19077","32%","24","w","29646.85","29646.85","4230.02","4230.02","2428.15","1801.87","0.0","0.0","0.0","Jul-2019","710.26","Jul-2019","Jul-2019","0","","1","Individual","","","","0","0","272667","1","4","1","1","9","37558","47","1","1","3910","41","59600","1","2","0","3","16039","10446","47.8","0","0","160","70","4","4","2","27","","14","","0","4","10","4","4","8","12","14","10","17","0","0","0","2","100","50","0","0","360433","56635","20000","80125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","9600","9600","9600"," 36 months"," 12.98%","323.37","B","B5","","n/a","MORTGAGE","35704","Not Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","401xx","KY","0.84","0","Nov-2003","0","69","","5","0","748","11.5%","23","w","8246.68","8246.68","1964.46","1964.46","1353.32","611.14","0.0","0.0","0.0","Jul-2019","323.37","Aug-2019","Jul-2019","0","","1","Individual","","","","0","0","748","0","0","0","0","44","0","","0","3","748","12","6500","0","0","1","3","150","3452","17.8","0","0","181","100","13","13","0","16","","3","","0","1","1","2","2","16","5","7","1","5","0","0","0","0","95.5","0","0","0","6500","748","4200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","2500","2500","2500"," 36 months"," 13.56%","84.92","C","C1","Chef","10+ years","RENT","55000","Not Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","109xx","NY","18.24","0","Apr-2001","1","","45","9","1","4341","10.3%","34","w","0.00","0.00","2652.7659856095","2652.77","2500.00","152.77","0.0","0.0","0.0","May-2019","2315.91","","Jul-2019","0","","1","Individual","","","","0","0","16901","2","2","1","2","2","12560","69","2","7","2137","28","42000","1","11","2","9","1878","34360","5.9","0","0","140","212","1","1","0","1","","2","","0","2","5","3","3","16","7","18","5","9","0","0","0","3","100","0","1","0","60124","16901","36500","18124","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [90]:
import pandas as pd
df=pd.read_csv('LoanStats_2018Q4.csv', skiprows=1, skipfooter=1)
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

(128413, 144)

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                    NaN              NaN
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [91]:
#Convert the term column from string to integer.
df['term'].str.extract('(\d+)',expand=False)

0          36
1          36
2          36
3          60
4          36
5          60
6          36
7          36
8          60
9          60
10         60
11         60
12         60
13         60
14         36
15         36
16         36
17         60
18         36
19         36
20         60
21         60
22         36
23         60
24         60
25         36
26         36
27         36
28         36
29         60
         ...
128383     36
128384     36
128385     36
128386     36
128387     60
128388     36
128389     36
128390     36
128391     36
128392     36
128393     36
128394     36
128395     36
128396     60
128397     60
128398     60
128399     36
128400     60
128401     36
128402     60
128403     36
128404     60
128405     36
128406     36
128407     36
128408     36
128409     36
128410     36
128411     36
128412    NaN
Name: term, Length: 128413, dtype: object

In [0]:
import pandas as pd
import numpy as np
df['term'] = df['term'].replace(np.nan, 0)

In [0]:
#Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is 
df['loan_status_is_great'] = False
df.loc[df['loan_status'] == 'Current','loan_status_is_great'] = True
df.loc[df['loan_status'] == 'Fully Paid','loan_status_is_great'] = True

In [0]:
import pandas as pd
import numpy as np
df['loan_status_is_great'] = df['loan_status_is_great'].replace(np.nan, 0)

In [95]:
df.isnull().sum()

id                                            128412
member_id                                     128413
loan_amnt                                          1
funded_amnt                                        1
funded_amnt_inv                                    1
term                                               0
int_rate                                           1
installment                                        1
grade                                              1
sub_grade                                          1
emp_title                                      20948
emp_length                                     11705
home_ownership                                     1
annual_inc                                         1
verification_status                                1
issue_d                                            1
loan_status                                        1
pymnt_plan                                         1
url                                           128413
desc                                          128413
purpose                                            1
title                                              1
zip_code                                           1
addr_state                                         1
dti                                              238
delinq_2yrs                                        1
earliest_cr_line                                   1
inq_last_6mths                                     1
mths_since_last_delinq                         72197
mths_since_last_record                        112963
                                               ...
sec_app_open_acc                              111631
sec_app_revol_util                            111889
sec_app_open_act_il                           111631
sec_app_num_rev_accts                         111631
sec_app_chargeoff_within_12_mths              111631
sec_app_collections_12_mths_ex_med            111631
sec_app_mths_since_last_major_derog           123259
hardship_flag                                      1
hardship_type                                 128410
hardship_reason                               128410
hardship_status                               128410
deferral_term                                 128410
hardship_amount                               128410
hardship_start_date                           128410
hardship_end_date                             128410
payment_plan_start_date                       128410
hardship_length                               128410
hardship_dpd                                  128410
hardship_loan_status                          128410
orig_projected_additional_accrued_interest    128410
hardship_payoff_balance_amount                128410
hardship_last_payment_amount                  128410
debt_settlement_flag                               1
debt_settlement_flag_date                     128351
settlement_status                             128351
settlement_date                               128351
settlement_amount                             128351
settlement_percentage                         128351
settlement_term                               128351
loan_status_is_great                               0
Length: 145, dtype: int64

In [96]:
#Make last_pymnt_d_month and last_pymnt_d_year columns.
df['last_pymnt_d_month'] = 0 #df['last_pymnt_d_month'].fillna('0').astype(int)
df['last_pymnt_d_year'] = 0 #df['last-pymnt_d_year'].fillna('0').astype(int) 
df.head()

    id  member_id  ...  last_pymnt_d_month  last_pymnt_d_year
0  NaN        NaN  ...                   0                  0
1  NaN        NaN  ...                   0                  0
2  NaN        NaN  ...                   0                  0
3  NaN        NaN  ...                   0                  0
4  NaN        NaN  ...                   0                  0

[5 rows x 147 columns]

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01