<a href="https://colab.research.google.com/github/brucebra000/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/Copy_of_LS_DS_114_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [14]:
##### Begin Working Here #####
import pandas as pd
import numpy as np

!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
!unzip LoanStats_2018Q4.csv.zip
!head LoanStats_2018Q4.csv

--2019-09-13 01:48:53--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.4’

LoanStats_2018Q4.cs     [                <=> ]  21.58M   912KB/s    in 24s

2019-09-13 01:49:18 (908 KB/s) - ‘LoanStats_2018Q4.csv.zip.4’ saved [22631049]

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 36 months"," 10.33%","324.23","B","B1","","< 1 year","MORTGAGE","280000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","974xx","OR","6.15","2","Jan-1996","0","18","","14","0","9082","38%","23","w","8289.30","8289.30","2261.0","2261.00","1710.70","550.30","0.0","0.0","0.0","Jul-2019","324.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","671","246828","1","3","2","3","1","48552","62","1","3","4923","46","23900","2","7","1","7","17631","11897","43.1","0","0","158","275","11","1","1","11","","11","","0","3","4","7","7","10","9","11","4","14","0","0","0","4","91.3","28.6","0","0","367828","61364","20900","54912","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 23.40%","155.68","E","E1","Security","3 years","RENT","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","070xx","NJ","26.33","0","Sep-2006","4","59","","15","0","5199","19.2%","20","w","3423.38","3423.38","1081.96","1081.96","576.62","505.34","0.0","0.0","0.0","Jul-2019","155.68","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","66926","5","4","3","4","5","61727","86","6","11","1353","68","27100","4","0","4","15","4462","20174","7.9","0","0","147","118","2","2","0","2","","0","","0","5","7","9","9","8","11","12","7","15","0","0","0","9","95","0","0","0","98655","66926","21900","71555","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 17.97%","180.69","D","D1","Administrative","6 years","MORTGAGE","59280","Source Verified","Dec-2018","Late (31-120 days)","n","","","debt_consolidation","Debt consolidation","490xx","MI","10.51","0","Apr-2011","0","","","8","0","4599","19.1%","13","w","4456.17","4456.17","895.96","895.96","543.83","352.13","0.0","0.0","0.0","Jun-2019","180.69","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","110299","0","1","0","2","14","7150","72","0","2","0","35","24100","1","5","0","4","18383","13800","0","0","0","87","92","15","14","2","77","","14","","0","0","3","3","3","4","6","7","3","8","0","0","0","0","100","0","0","0","136927","11749","13800","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 60 months"," 20.89%","620.81","D","D4","Operator","5 years","RENT","68107","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","672xx","KS","0.52","0","Feb-1997","0","","","5","0","976","13%","10","w","21353.16","21353.16","4307.45","4307.45","1646.84","2660.61","0.0","0.0","0.0","Jul-2019","620.81","Sep-2019","Aug-2019","1","","1","Individual","","","","0","2693","976","0","0","0","0","36","0","","3","4","0","13","7500","2","2","4","4","195","3300","0","0","0","237","262","10","10","0","10","","9","","0","0","1","3","4","3","5","7","1","5","0","0","0","3","100","0","0","0","7500","976","3300","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 23.40%","311.35","E","E1","Manager","10+ years","OWN","43000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","357xx","AL","33.24","0","Jan-1995","0","","107","8","1","9019","81.3%","16","w","6846.83","6846.83","2163.85","2163.85","1153.17","1010.68","0.0","0.0","0.0","Jul-2019","311.35","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","169223","0","3","2","2","7","22059","69","0","0","2174","72","11100","1","1","1","2","21153","126","94.5","0","0","148","287","44","7","1","51","","7","","0","1","4","1","2","8","4","7","4","8","0","0","0","2","100","100","1","0","199744","31078","2300","32206","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","32075","32075","32075"," 60 months"," 11.80%","710.26","B","B4","Nursing Supervisor","10+ years","MORTGAGE","150000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","231xx","VA","22.21","0","Aug-2005","0","","","17","0","19077","32%","24","w","29228.12","29228.12","4940.28","4940.28","2846.88","2093.40","0.0","0.0","0.0","Jul-2019","710.26","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","272667","1","4","1","1","9","37558","47","1","1","3910","41","59600","1","2","0","3","16039","10446","47.8","0","0","160","70","4","4","2","27","","14","","0","4","10","4","4","8","12","14","10","17","0","0","0","2","100","50","0","0","360433","56635","20000","80125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","9600","9600","9600"," 36 months"," 12.98%","323.37","B","B5","","n/a","MORTGAGE","35704","Not Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","401xx","KY","0.84","0","Nov-2003","0","69","","5","0","748","11.5%","23","w","8012.51","8012.51","2287.83","2287.83","1587.49","700.34","0.0","0.0","0.0","Aug-2019","323.37","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","748","0","0","0","0","44","0","","0","3","748","12","6500","0","0","1","3","150","3452","17.8","0","0","181","100","13","13","0","16","","3","","0","1","1","2","2","16","5","7","1","5","0","0","0","0","95.5","0","0","0","6500","748","4200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 18.94%","777.23","D","D2","Postmaster ","10+ years","MORTGAGE","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","713xx","LA","26.52","0","Jun-1987","0","71","75","13","1","12315","24.2%","44","w","19969.40","19969.40","12893.26","12893.26","10030.60","2862.66","0.0","0.0","0.0","Jul-2019","777.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1208","321915","4","4","2","3","3","87153","88","4","5","998","57","50800","2","15","2","10","24763","13761","8.3","0","0","163","378","4","3","3","4","","4","","0","2","4","4","9","27","8","14","4","13","0","0","0","6","95","0","1","0","372872","99468","15000","94072","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [21]:
df = pd.read_csv('LoanStats_2018Q4.csv', header = 1, skipfooter = 2, engine = 'python')
df.head()

   id  member_id  ...  settlement_percentage  settlement_term
0 NaN        NaN  ...                    NaN              NaN
1 NaN        NaN  ...                    NaN              NaN
2 NaN        NaN  ...                    NaN              NaN
3 NaN        NaN  ...                    NaN              NaN
4 NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [22]:
#Changing term into an integer
df['term']

0          36 months
1          36 months
2          36 months
3          60 months
4          36 months
5          60 months
6          36 months
7          60 months
8          36 months
9          60 months
10         60 months
11         60 months
12         60 months
13         60 months
14         36 months
15         36 months
16         36 months
17         60 months
18         60 months
19         60 months
20         36 months
21         36 months
22         36 months
23         36 months
24         60 months
25         36 months
26         36 months
27         60 months
28         36 months
29         36 months
             ...
128382     60 months
128383     36 months
128384     36 months
128385     36 months
128386     60 months
128387     36 months
128388     36 months
128389     36 months
128390     36 months
128391     36 months
128392     36 months
128393     36 months
128394     36 months
128395     36 months
128396     60 months
128397     60 months
128398     60 months
128399     36 months
128400     60 months
128401     36 months
128402     60 months
128403     36 months
128404     36 months
128405     60 months
128406     36 months
128407     36 months
128408     36 months
128409     36 months
128410     36 months
128411     36 months
Name: term, Length: 128412, dtype: object

In [27]:
def term_to_int(x):
  return int(x[:-7])

df['term'] = df['term'].apply(term_to_int)
df.head()

   id  member_id  ...  settlement_percentage  settlement_term
0 NaN        NaN  ...                    NaN              NaN
1 NaN        NaN  ...                    NaN              NaN
2 NaN        NaN  ...                    NaN              NaN
3 NaN        NaN  ...                    NaN              NaN
4 NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [40]:
#Creating loan_status_is_great
df['loan_status_is_great'] = df['loan_status'].str.contains('Current') | df['loan_status'].str.contains('Fully Paid')
def bool_to_int(x):
  if x == True:
    return int(1)
  else:
    return int(0)
df['loan_status_is_great'] = df['loan_status_is_great'].apply(bool_to_int)
df.head()

   id  member_id  ...  settlement_term  loan_status_is_great
0 NaN        NaN  ...              NaN                     1
1 NaN        NaN  ...              NaN                     1
2 NaN        NaN  ...              NaN                     0
3 NaN        NaN  ...              NaN                     1
4 NaN        NaN  ...              NaN                     1

[5 rows x 145 columns]

In [42]:
#Creating last_pymnt_d_month and last_pymnt_d_year
df.head(20)

    id  member_id  ...  settlement_term  loan_status_is_great
0  NaN        NaN  ...              NaN                     1
1  NaN        NaN  ...              NaN                     1
2  NaN        NaN  ...              NaN                     0
3  NaN        NaN  ...              NaN                     1
4  NaN        NaN  ...              NaN                     1
5  NaN        NaN  ...              NaN                     1
6  NaN        NaN  ...              NaN                     1
7  NaN        NaN  ...              NaN                     1
8  NaN        NaN  ...              NaN                     1
9  NaN        NaN  ...              NaN                     1
10 NaN        NaN  ...              NaN                     1
11 NaN        NaN  ...              NaN                     1
12 NaN        NaN  ...              NaN                     1
13 NaN        NaN  ...              NaN                     1
14 NaN        NaN  ...              NaN                     1
15 NaN        NaN  ...              NaN                     1
16 NaN        NaN  ...              NaN                     1
17 NaN        NaN  ...              NaN                     1
18 NaN        NaN  ...              NaN                     1
19 NaN        NaN  ...              NaN                     1

[20 rows x 145 columns]

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01