<a href="https://colab.research.google.com/github/ewuerfel66/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/EricWuerfel_LS_DS5_Assignment_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from statistics import median, mean

In [3]:
!curl https://archive.ics.uci.edu/ml/machine-learning-databases/bridges/bridges.data.version1

E1,M,3,1818,HIGHWAY,?,2,N,THROUGH,WOOD,SHORT,S,WOOD
E2,A,25,1819,HIGHWAY,1037,2,N,THROUGH,WOOD,SHORT,S,WOOD
E3,A,39,1829,AQUEDUCT,?,1,N,THROUGH,WOOD,?,S,WOOD
E5,A,29,1837,HIGHWAY,1000,2,N,THROUGH,WOOD,SHORT,S,WOOD
E6,M,23,1838,HIGHWAY,?,2,N,THROUGH,WOOD,?,S,WOOD
E7,A,27,1840,HIGHWAY,990,2,N,THROUGH,WOOD,MEDIUM,S,WOOD
E8,A,28,1844,AQUEDUCT,1000,1,N,THROUGH,IRON,SHORT,S,SUSPEN
E9,M,3,1846,HIGHWAY,1500,2,N,THROUGH,IRON,SHORT,S,SUSPEN
E10,A,39,1848,AQUEDUCT,?,1,N,DECK,WOOD,?,S,WOOD
E11,A,29,1851,HIGHWAY,1000,2,N,THROUGH,WOOD,MEDIUM,S,WOOD
E12,A,39,1853,RR,?,2,N,DECK,WOOD,?,S,WOOD
E14,M,6,1856,HIGHWAY,1200,2,N,THROUGH,WOOD,MEDIUM,S,WOOD
E13,A,33,1856,HIGHWAY,?,2,N,THROUGH,WOOD,?,S,WOOD
E15,A,28,1857,RR,?,2,N,THROUGH,WOOD,?,S,WOOD
E16,A,25,1859,HIGHWAY,1030,2,N,THROUGH,IRON,MEDIUM,S-F,SUSPEN
E17,M,4,1863,RR,1000,2,N,THROUGH,IRON,MEDIUM,?,SIMPLE-T
E18,A,28,1864,RR,1200,2,N,THROUGH,IRON,SHORT,S,SIMPLE-T
E19,A,29,1866,HIGHWAY,1000,2,N,THROUGH,WOOD,MEDIUM,S,WOOD
E20,A,32,1870,HIGHWAY,1000,2,N,THROUGH,WOOD,MEDIUM,S,WOOD
E21,M,16,1874,RR,?,2,?,THROUGH,IRON,?,?,SIMPLE-T
E23,M,1,1876,HIGHWAY,1245,?,?,THROUGH,STEEL,LONG,F,SUSPEN
E22,A,24,1876,HIGHWAY,1200,4,G,THROUGH,WOOD,SHORT,S,WOOD
E24,O,45,1878,RR,?,2,G,?,STEEL,?,?,SIMPLE-T
E25,M,10,1882,RR,?,2,G,?,STEEL,?,?,SIMPLE-T
E27,A,39,1883,RR,?,2,G,THROUGH,STEEL,?,F,SIMPLE-T
E26,M,12,1883,RR,1150,2,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
E30,A,31,1884,RR,?,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E29,A,26,1884,HIGHWAY,1080,2,G,THROUGH,STEEL,MEDIUM,?,SUSPEN
E28,M,3,1884,HIGHWAY,1000,2,G,THROUGH,STEEL,MEDIUM,S,ARCH
E32,A,30,1887,HIGHWAY,?,2,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
E31,M,8,1887,RR,1161,2,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
E34,O,41,1888,RR,4558,2,G,THROUGH,STEEL,LONG,F,SIMPLE-T
E33,M,19,1889,HIGHWAY,1120,?,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
E36,O,45,1890,HIGHWAY,?,2,G,THROUGH,IRON,SHORT,F,SIMPLE-T
E35,A,27,1890,HIGHWAY,1000,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E38,M,17,1891,HIGHWAY,?,2,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
E37,M,18,1891,RR,1350,2,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
E39,A,25,1892,HIGHWAY,?,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E4,A,27,1892,AQUEDUCT,1092,1,N,THROUGH,WOOD,SHORT,S,WOOD
E40,M,22,1893,HIGHWAY,?,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E41,M,11,1894,HIGHWAY,?,2,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
E42,M,9,1895,HIGHWAY,2367,2,G,THROUGH,STEEL,LONG,F,SIMPLE-T
E44,O,48,1896,HIGHWAY,?,2,G,THROUGH,STEEL,LONG,F,SUSPEN
E43,M,7,1896,HIGHWAY,1040,2,G,THROUGH,STEEL,LONG,F,ARCH
E46,A,37,1897,RR,4000,2,G,DECK,STEEL,LONG,F,SIMPLE-T
E45,M,14,1897,RR,2264,?,G,THROUGH,STEEL,?,F,SIMPLE-T
E47,M,15,1898,RR,2000,2,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
E58,A,33,1900,HIGHWAY,1200,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E48,A,38,1900,HIGHWAY,2000,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E94,M,13,1901,RR,?,2,G,THROUGH,STEEL,LONG,F,SIMPLE-T
E49,A,34,1902,HIGHWAY,1850,2,G,THROUGH,STEEL,MEDIUM,F,CANTILEV
E95,M,16,1903,RR,1300,2,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
E87,A,35,1903,RR,3000,2,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
E51,M,6,1903,RR,1417,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E50,M,21,1903,RR,1154,?,G,THROUGH,STEEL,LONG,F,SIMPLE-T
E89,M,4,1904,RR,1200,2,G,THROUGH,STEEL,MEDIUM,S-F,SIMPLE-T
E53,A,28,1904,RR,965,4,G,THROUGH,STEEL,MEDIUM,S-F,SIMPLE-T
E52,M,2,1904,RR,1504,?,G,THROUGH,STEEL,LONG,F,CANTILEV
E54,Y,?,1908,HIGHWAY,1240,?,G,?,STEEL,MEDIUM,F,SIMPLE-T
E56,M,23,1909,HIGHWAY,?,?,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E55,A,36,1909,HIGHWAY,1730,2,G,THROUGH,STEEL,LONG,F,SIMPLE-T
E57,O,49,1910,RR,1620,2,G,THROUGH,STEEL,LONG,F,CANTILEV
E59,O,43,1911,HIGHWAY,1652,2,G,THROUGH,STEEL,LONG,F,CANTILEV
E107,A,39,1914,RR,?,?,G,?,STEEL,?,F,NIL
E92,M,10,1914,RR,2210,?,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E61,O,41,1915,RR,2822,2,G,THROUGH,STEEL,LONG,F,SIMPLE-T
E60,A,24,1915,HIGHWAY,1000,4,G,THROUGH,STEEL,LONG,F,SIMPLE-T
E62,A,37,1918,RR,2300,2,N,DECK,STEEL,LONG,F,CONT-T
E63,A,31,1920,RR,2122,2,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E65,A,30,1921,WALK,?,?,G,THROUGH,STEEL,?,F,SUSPEN
E64,A,29,1923,HIGHWAY,885,4,G,THROUGH,STEEL,MEDIUM,F,ARCH
E66,A,32,1924,HIGHWAY,2365,4,G,THROUGH,STEEL,MEDIUM,S,ARCH
E70,A,27,1926,HIGHWAY,860,4,G,THROUGH,STEEL,MEDIUM,S-F,SUSPEN
E69,A,26,1926,HIGHWAY,884,4,G,THROUGH,STEEL,MEDIUM,S-F,SUSPEN
E101,O,46,1927,HIGHWAY,1770,2,G,THROUGH,STEEL,LONG,S-F,CANTILEV
E73,A,38,1927,HIGHWAY,1508,?,G,THROUGH,STEEL,MEDIUM,S,ARCH
E72,M,5,1927,HIGHWAY,2663,4,N,DECK,STEEL,MEDIUM,S-F,CANTILEV
E67,M,1,1927,HIGHWAY,1330,4,G,THROUGH,STEEL,LONG,F,CANTILEV
E75,A,30,1928,HIGHWAY,2678,4,G,DECK,STEEL,MEDIUM,F,ARCH
E74,M,20,1928,HIGHWAY,2220,2,G,DECK,STEEL,MEDIUM,S-F,CANTILEV
E71,A,25,1928,HIGHWAY,860,4,G,THROUGH,STEEL,MEDIUM,S-F,SUSPEN
E68,M,17,1928,HIGHWAY,2250,2,G,THROUGH,STEEL,MEDIUM,S,SIMPLE-T
E78,O,40,1931,HIGHWAY,1365,4,G,THROUGH,STEEL,LONG,F,ARCH
E77,O,42,1931,HIGHWAY,1450,4,N,THROUGH,STEEL,LONG,F,ARCH
E76,M,6,1931,HIGHWAY,1500,4,G,THROUGH,STEEL,LONG,F,SUSPEN
E93,M,11,1937,HIGHWAY,1690,4,N,DECK,STEEL,LONG,S-F,CONT-T
E79,A,34,1939,HIGHWAY,1800,4,G,DECK,STEEL,MEDIUM,F,CANTILEV
E108,A,39.5,1945,HIGHWAY,1060,4,G,DECK,STEEL,MEDIUM,S-F,CONT-T
E107N,A,39.7,1945,RR,840,2,G,THROUGH,STEEL,MEDIUM,S-F,SIMPLE-T
E105,A,38.5,1945,HIGHWAY,1710,2,N,DECK,STEEL,MEDIUM,S-F,CONT-T
E103,O,48,1945,HIGHWAY,2160,2,G,THROUGH,STEEL,LONG,F,CANTILEV
E97,Y,52,1945,HIGHWAY,?,?,G,THROUGH,STEEL,MEDIUM,S,ARCH
E96,Y,51,1945,RR,?,?,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
E99,M,23,1950,HIGHWAY,1320,2,G,THROUGH,STEEL,MEDIUM,S-F,SIMPLE-T
E98,M,22,1951,HIGHWAY,900,4,G,THROUGH,STEEL,MEDIUM,F,CONT-T
E81,M,14,1951,HIGHWAY,2423,4,G,DECK,STEEL,LONG,F,CONT-T
E80,M,19,1951,HIGHWAY,1031,4,G,THROUGH,STEEL,LONG,F,CANTILEV
E88,A,37,1955,HIGHWAY,2300,4,N,DECK,STEEL,LONG,F,CONT-T
E82,O,42,1955,HIGHWAY,804,?,G,THROUGH,STEEL,?,F,SIMPLE-T
E102,O,47,1959,HIGHWAY,1700,2,G,THROUGH,STEEL,LONG,F,CONT-T
E83,M,1,1959,HIGHWAY,1000,6,G,THROUGH,STEEL,LONG,F,ARCH
E86,A,33,1961,HIGHWAY,980,4,G,DECK,STEEL,MEDIUM,S-F,CONT-T
E85,M,9,1962,HIGHWAY,2213,4,G,DECK,STEEL,LONG,F,CONT-T
E84,A,24,1969,HIGHWAY,870,6,G,THROUGH,STEEL,MEDIUM,F,ARCH
E91,O,44,1975,HIGHWAY,3756,6,G,THROUGH,STEEL,LONG,F,ARCH
E90,M,7,1978,HIGHWAY,950,6,G,THROUGH,STEEL,LONG,F,ARCH
E100,O,43,1982,HIGHWAY,?,?,G,?,?,?,F,?
E109,A,28,1986,HIGHWAY,?,?,G,?,?,?,F,?

It looks like the NaN values are imputed as '?'s.

What data types do we have?

In [32]:
df.dtypes

IDENTIF       object
RIVER         object
LOCATION      object
ERECTED        int64
PURPOSE       object
LENGTH        object
LANES         object
CLEAR         object
TORD          object
MATERIAL      object
SPAN          object
REL_LENGTH    object
TYPE          object
dtype: object

Let's **add it to a data frame**

In [26]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/bridges/bridges.data.version1', header = None)
df.columns = ['IDENTIF', 'RIVER', 'LOCATION', 'ERECTED', 'PURPOSE', 'LENGTH', 'LANES', 'CLEAR', 'TORD', 'MATERIAL', 'SPAN', 'REL_LENGTH', 'TYPE']
df.head()

  IDENTIF RIVER LOCATION  ERECTED  ...  MATERIAL   SPAN REL_LENGTH  TYPE
0      E1     M        3     1818  ...      WOOD  SHORT          S  WOOD
1      E2     A       25     1819  ...      WOOD  SHORT          S  WOOD
2      E3     A       39     1829  ...      WOOD      ?          S  WOOD
3      E5     A       29     1837  ...      WOOD  SHORT          S  WOOD
4      E6     M       23     1838  ...      WOOD      ?          S  WOOD

[5 rows x 13 columns]

**change '?'s to NaN**

In [27]:
nan_df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/bridges/bridges.data.version1', header = None, na_values='?')
nan_df.columns = ['IDENTIF', 'RIVER', 'LOCATION', 'ERECTED', 'PURPOSE', 'LENGTH', 'LANES', 'CLEAR', 'TORD', 'MATERIAL', 'SPAN', 'REL_LENGTH', 'TYPE']
nan_df.head()

  IDENTIF RIVER  LOCATION  ERECTED  ...  MATERIAL   SPAN  REL_LENGTH  TYPE
0      E1     M       3.0     1818  ...      WOOD  SHORT           S  WOOD
1      E2     A      25.0     1819  ...      WOOD  SHORT           S  WOOD
2      E3     A      39.0     1829  ...      WOOD    NaN           S  WOOD
3      E5     A      29.0     1837  ...      WOOD  SHORT           S  WOOD
4      E6     M      23.0     1838  ...      WOOD    NaN           S  WOOD

[5 rows x 13 columns]

In [28]:
nan_df.isna().sum()

IDENTIF        0
RIVER          0
LOCATION       1
ERECTED        0
PURPOSE        0
LENGTH        27
LANES         16
CLEAR          2
TORD           6
MATERIAL       2
SPAN          16
REL_LENGTH     5
TYPE           2
dtype: int64

**Fill in NaNs**

Which ones could we use ffill for . . . LOCATION, CLEAR, T-OR-D, MATERIAL, SPAN, REL-LENGTH, TYPE

In [29]:
ffilled_df = nan_df.copy()
ffilled_df.head(20)

   IDENTIF RIVER  LOCATION    ...       SPAN REL_LENGTH      TYPE
0       E1     M       3.0    ...      SHORT          S      WOOD
1       E2     A      25.0    ...      SHORT          S      WOOD
2       E3     A      39.0    ...        NaN          S      WOOD
3       E5     A      29.0    ...      SHORT          S      WOOD
4       E6     M      23.0    ...        NaN          S      WOOD
5       E7     A      27.0    ...     MEDIUM          S      WOOD
6       E8     A      28.0    ...      SHORT          S    SUSPEN
7       E9     M       3.0    ...      SHORT          S    SUSPEN
8      E10     A      39.0    ...        NaN          S      WOOD
9      E11     A      29.0    ...     MEDIUM          S      WOOD
10     E12     A      39.0    ...        NaN          S      WOOD
11     E14     M       6.0    ...     MEDIUM          S      WOOD
12     E13     A      33.0    ...        NaN          S      WOOD
13     E15     A      28.0    ...        NaN          S      WOOD
14     E16     A      25.0    ...     MEDIUM        S-F    SUSPEN
15     E17     M       4.0    ...     MEDIUM        NaN  SIMPLE-T
16     E18     A      28.0    ...      SHORT          S  SIMPLE-T
17     E19     A      29.0    ...     MEDIUM          S      WOOD
18     E20     A      32.0    ...     MEDIUM          S      WOOD
19     E21     M      16.0    ...        NaN        NaN  SIMPLE-T

[20 rows x 13 columns]

In [30]:
ffilled_df.CLEAR = ffilled_df.CLEAR.fillna(method='ffill')
ffilled_df.TORD = ffilled_df.TORD.fillna(method='ffill')
ffilled_df.MATERIAL = ffilled_df.MATERIAL.fillna(method='ffill')
ffilled_df.SPAN = ffilled_df.SPAN.fillna(method='ffill')
ffilled_df.REL_LENGTH = ffilled_df.REL_LENGTH.fillna(method='ffill')
ffilled_df.TYPE = ffilled_df.TYPE.fillna(method='ffill')
ffilled_df.LOCATION = ffilled_df.LOCATION.fillna(method='ffill')
ffilled_df.head()

  IDENTIF RIVER  LOCATION  ERECTED  ...  MATERIAL   SPAN  REL_LENGTH  TYPE
0      E1     M       3.0     1818  ...      WOOD  SHORT           S  WOOD
1      E2     A      25.0     1819  ...      WOOD  SHORT           S  WOOD
2      E3     A      39.0     1829  ...      WOOD  SHORT           S  WOOD
3      E5     A      29.0     1837  ...      WOOD  SHORT           S  WOOD
4      E6     M      23.0     1838  ...      WOOD  SHORT           S  WOOD

[5 rows x 13 columns]

LANES and LENGTH can be filled by the median

In [34]:
clean_LANES = df.LANES.dropna()
print(clean_LANES)

#median_LANES = median(df.LANES.dropna())
#median_LENGTH = median(df.LENGTH.dropna())

0      2
1      2
2      1
3      2
4      2
5      2
6      1
7      2
8      1
9      2
10     2
11     2
12     2
13     2
14     2
15     2
16     2
17     2
18     2
19     2
20     ?
21     4
22     2
23     2
24     2
25     2
26     2
27     2
28     2
29     2
      ..
78     4
79     2
80     4
81     2
82     4
83     4
84     4
85     4
86     4
87     4
88     2
89     2
90     2
91     ?
92     ?
93     2
94     4
95     4
96     4
97     4
98     ?
99     2
100    6
101    4
102    4
103    6
104    6
105    6
106    ?
107    ?
Name: LANES, Length: 108, dtype: object