<a href="https://colab.research.google.com/github/mseryy01/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/LS_DS_114_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# ASSIGNMENT

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.

- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2019-09-05 22:01:19--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.2’

LoanStats_2018Q4.cs     [        <=>         ]  21.58M  1.70MB/s    in 13s

2019-09-05 22:01:32 (1.69 MB/s) - ‘LoanStats_2018Q4.csv.zip.2’ saved [22631049]

In [0]:
!unzip LoanStats_2018Q4.csv

Archive:  LoanStats_2018Q4.csv
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [0]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","10000","10000","10000"," 36 months"," 10.33%","324.23","B","B1","","< 1 year","MORTGAGE","280000","Not Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","974xx","OR","6.15","2","Jan-1996","0","18","","14","0","9082","38%","23","w","8289.30","8289.30","2261.0","2261.00","1710.70","550.30","0.0","0.0","0.0","Jul-2019","324.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","671","246828","1","3","2","3","1","48552","62","1","3","4923","46","23900","2","7","1","7","17631","11897","43.1","0","0","158","275","11","1","1","11","","11","","0","3","4","7","7","10","9","11","4","14","0","0","0","4","91.3","28.6","0","0","367828","61364","20900","54912","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","4000","4000","4000"," 36 months"," 23.40%","155.68","E","E1","Security","3 years","RENT","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","070xx","NJ","26.33","0","Sep-2006","4","59","","15","0","5199","19.2%","20","w","3423.38","3423.38","1081.96","1081.96","576.62","505.34","0.0","0.0","0.0","Jul-2019","155.68","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","66926","5","4","3","4","5","61727","86","6","11","1353","68","27100","4","0","4","15","4462","20174","7.9","0","0","147","118","2","2","0","2","","0","","0","5","7","9","9","8","11","12","7","15","0","0","0","9","95","0","0","0","98655","66926","21900","71555","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 17.97%","180.69","D","D1","Administrative","6 years","MORTGAGE","59280","Source Verified","Dec-2018","Late (31-120 days)","n","","","debt_consolidation","Debt consolidation","490xx","MI","10.51","0","Apr-2011","0","","","8","0","4599","19.1%","13","w","4456.17","4456.17","895.96","895.96","543.83","352.13","0.0","0.0","0.0","Jun-2019","180.69","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","110299","0","1","0","2","14","7150","72","0","2","0","35","24100","1","5","0","4","18383","13800","0","0","0","87","92","15","14","2","77","","14","","0","0","3","3","3","4","6","7","3","8","0","0","0","0","100","0","0","0","136927","11749","13800","10000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 60 months"," 20.89%","620.81","D","D4","Operator","5 years","RENT","68107","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","672xx","KS","0.52","0","Feb-1997","0","","","5","0","976","13%","10","w","21353.16","21353.16","4307.45","4307.45","1646.84","2660.61","0.0","0.0","0.0","Jul-2019","620.81","Sep-2019","Aug-2019","1","","1","Individual","","","","0","2693","976","0","0","0","0","36","0","","3","4","0","13","7500","2","2","4","4","195","3300","0","0","0","237","262","10","10","0","10","","9","","0","0","1","3","4","3","5","7","1","5","0","0","0","3","100","0","0","0","7500","976","3300","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","8000","8000","8000"," 36 months"," 23.40%","311.35","E","E1","Manager","10+ years","OWN","43000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","357xx","AL","33.24","0","Jan-1995","0","","107","8","1","9019","81.3%","16","w","6846.83","6846.83","2163.85","2163.85","1153.17","1010.68","0.0","0.0","0.0","Jul-2019","311.35","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","169223","0","3","2","2","7","22059","69","0","0","2174","72","11100","1","1","1","2","21153","126","94.5","0","0","148","287","44","7","1","51","","7","","0","1","4","1","2","8","4","7","4","8","0","0","0","2","100","100","1","0","199744","31078","2300","32206","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","32075","32075","32075"," 60 months"," 11.80%","710.26","B","B4","Nursing Supervisor","10+ years","MORTGAGE","150000","Not Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","231xx","VA","22.21","0","Aug-2005","0","","","17","0","19077","32%","24","w","29228.12","29228.12","4940.28","4940.28","2846.88","2093.40","0.0","0.0","0.0","Jul-2019","710.26","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","272667","1","4","1","1","9","37558","47","1","1","3910","41","59600","1","2","0","3","16039","10446","47.8","0","0","160","70","4","4","2","27","","14","","0","4","10","4","4","8","12","14","10","17","0","0","0","2","100","50","0","0","360433","56635","20000","80125","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","9600","9600","9600"," 36 months"," 12.98%","323.37","B","B5","","n/a","MORTGAGE","35704","Not Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","401xx","KY","0.84","0","Nov-2003","0","69","","5","0","748","11.5%","23","w","8012.51","8012.51","2287.83","2287.83","1587.49","700.34","0.0","0.0","0.0","Aug-2019","323.37","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","748","0","0","0","0","44","0","","0","3","748","12","6500","0","0","1","3","150","3452","17.8","0","0","181","100","13","13","0","16","","3","","0","1","1","2","2","16","5","7","1","5","0","0","0","0","95.5","0","0","0","6500","748","4200","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","30000","30000","30000"," 60 months"," 18.94%","777.23","D","D2","Postmaster ","10+ years","MORTGAGE","90000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","713xx","LA","26.52","0","Jun-1987","0","71","75","13","1","12315","24.2%","44","w","19969.40","19969.40","12893.26","12893.26","10030.60","2862.66","0.0","0.0","0.0","Jul-2019","777.23","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1208","321915","4","4","2","3","3","87153","88","4","5","998","57","50800","2","15","2","10","24763","13761","8.3","0","0","163","378","4","3","3","4","","4","","0","2","4","4","9","27","8","14","4","13","0","0","0","6","95","0","1","0","372872","99468","15000","94072","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [0]:
!tail LoanStats_2018Q4.csv

"","","5600","5600","5600"," 36 months"," 13.56%","190.21","C","C1","","n/a","RENT","15600","Not Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","836xx","ID","15.31","0","Aug-2012","0","","97","9","1","5996","34.5%","11","w","4264.17","4264.17","1891.55","1891.55","1335.83","555.72","0.0","0.0","0.0","Aug-2019","190.21","Sep-2019","Aug-2019","0","","1","Individual","","","","0","0","5996","0","0","0","1","20","0","","0","2","3017","35","17400","1","0","0","3","750","4689","45.5","0","0","20","73","13","13","0","13","","20","","0","3","5","4","4","1","9","10","5","9","0","0","0","0","100","25","1","0","17400","5996","8600","0","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","23000","23000","23000"," 36 months"," 15.02%","797.53","C","C3","Tax Consultant","10+ years","MORTGAGE","75000","Source Verified","Oct-2018","Charged Off","n","","","debt_consolidation","Debt consolidation","352xx","AL","20.95","1","Aug-1985","2","22","","12","0","22465","43.6%","28","w","0.00","0.00","1547.08","1547.08","1025.67","521.41","0.0","0.0","0.0","Dec-2018","797.53","","Nov-2018","0","","1","Individual","","","","0","0","259658","4","2","3","3","6","18149","86","4","6","12843","56","51500","2","2","5","11","21638","26321","44.1","0","0","12","397","4","4","6","5","22","4","22","0","4","5","7","14","3","9","19","5","12","0","0","0","7","96.4","14.3","0","0","296500","40614","47100","21000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 15.02%","346.76","C","C3","security guard","5 years","MORTGAGE","38000","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","443xx","OH","13.16","3","Jul-1982","0","6","","11","0","5634","37.1%","16","w","7655.00","7655.00","3459.26","3459.26","2345.00","1114.26","0.0","0.0","0.0","Aug-2019","346.76","Sep-2019","Aug-2019","0","","1","Individual","","","","0","155","77424","0","1","0","0","34","200","10","1","1","1866","42","15200","2","0","0","2","7039","4537","50.1","0","0","34","434","11","11","3","11","6","17","6","0","3","5","5","6","1","8","11","5","11","0","0","0","1","73.3","40","0","0","91403","9323","9100","2000","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","5000","5000","5000"," 36 months"," 13.56%","169.83","C","C1","Payoff Clerk","10+ years","MORTGAGE","35360","Not Verified","Oct-2018","Current","n","","","debt_consolidation","Debt consolidation","381xx","TN","11.3","1","Jun-2006","0","21","","9","0","2597","27.3%","15","f","3807.30","3807.30","1694.53","1694.53","1192.70","501.83","0.0","0.0","0.0","Aug-2019","169.83","Sep-2019","Aug-2019","0","","1","Individual","","","","0","1413","69785","0","2","0","1","16","2379","40","3","4","1826","32","9500","0","0","1","5","8723","1174","60.9","0","0","147","85","9","9","2","10","21","9","21","0","1","3","2","2","6","6","7","3","9","0","0","0","3","92.9","50","0","0","93908","4976","3000","6028","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","9750"," 36 months"," 11.06%","327.68","B","B3","","n/a","RENT","44400","Source Verified","Oct-2018","Current","n","","","credit_card","Credit card refinancing","980xx","WA","11.78","0","Oct-2008","2","40","","15","0","6269","13.1%","25","f","7544.75","7356.13","3261.44","3179.90","2455.25","806.19","0.0","0.0","0.0","Aug-2019","327.68","Sep-2019","Aug-2019","0","53","1","Individual","","","","0","520","16440","3","1","1","1","2","10171","100","2","5","404","28","47700","0","3","5","6","1265","20037","2.3","0","0","61","119","1","1","0","1","","1","40","1","2","4","6","8","3","14","22","4","15","0","0","0","3","92","0","0","0","57871","16440","20500","10171","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10000","10000","10000"," 36 months"," 16.91%","356.08","C","C5","Key Accounts Manager","2 years","RENT","80000","Not Verified","Oct-2018","Current","n","","","other","Other","021xx","MA","17.72","1","Sep-2006","0","14","","17","0","1942","30.8%","31","w","7706.67","7706.67","3551.41","3551.41","2293.33","1258.08","0.0","0.0","0.0","Aug-2019","356.08","Sep-2019","Aug-2019","0","25","1","Individual","","","","0","0","59194","0","15","1","1","12","57252","85","0","0","1942","80","6300","0","5","0","1","3482","2058","48.5","0","0","144","142","40","12","0","131","30","","30","3","1","1","1","5","22","2","9","1","17","0","0","0","1","74.2","0","0","0","73669","59194","4000","67369","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""


Total amount funded in policy code 1: 2050909275
Total amount funded in policy code 2: 820109297

In [0]:
import pandas as pd
pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)
df=pd.read_csv('LoanStats_2018Q4.csv', header=1, na_values=['n/a'],skipfooter=2)
df.head(20)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.000000,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.960000,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.960000,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.450000,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.850000,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,32075,32075,32075.0,60 months,11.80%,710.26,B,B4,Nursing Supervisor,10+ years,MORTGAGE,150000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,231xx,VA,22.21,0,Aug-2005,0,NaN,NaN,17,0,19077,32%,24,w,29228.12,29228.12,4940.280000,4940.28,2846.88,2093.40,0.0,0.0,0.0,Jul-2019,710.26,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,272667,1,4,1,1,9.0,37558,47.0,1,1,3910,41.0,59600,1,2,0,3,16039.0,10446.0,47.8,0,0,160.0,70,4,4,2,27.0,NaN,14.0,NaN,0,4,10,4,4,8,12,14,10,17,0.0,0,0,2,100.0,50.0,0,0,360433,56635,20000,80125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,9600,9600,9600.0,36 months,12.98%,323.37,B,B5,NaN,NaN,MORTGAGE,35704.0,Not Verified,Dec-2018,Current,n,NaN,NaN,home_improvement,Home improvement,401xx,KY,0.84,0,Nov-2003,0,69.0,NaN,5,0,748,11.5%,23,w,8012.51,8012.51,2287.830000,2287.83,1587.49,700.34,0.0,0.0,0.0,Aug-2019,323.37,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,748,0,0,0,0,44.0,0,NaN,0,3,748,12.0,6500,0,0,1,3,150.0,3452.0,17.8,0,0,181.0,100,13,13,0,16.0,NaN,3.0,NaN,0,1,1,2,2,16,5,7,1,5,0.0,0,0,0,95.5,0.0,0,0,6500,748,4200,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,30000,30000,30000.0,60 months,18.94%,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0,Jun-1987,0,71.0,75.0,13,1,12315,24.2%,44,w,19969.40,19969.40,12893.260000,12893.26,10030.60,2862.66,0.0,0.0,0.0,Jul-2019,777.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,1208,321915,4,4,2,3,3.0,87153,88.0,4,5,998,57.0,50800,2,15,2,10,24763.0,13761.0,8.3,0,0,163.0,378,4,3,3,4.0,NaN,4.0,NaN,0,2,4,4,9,27,8,14,4,13,0.0,0,0,6,95.0,0.0,1,0,372872,99468,15000,94072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,2500,2500,2500.0,36 months,13.56%,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0,Apr-2001,1,NaN,45.0,9,1,4341,10.3%,34,w,0.00,0.00,2652.765986,2652.77,2500.00,152.77,0.0,0.0,0.0,May-2019,2315.91,NaN,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,16901,2,2,1,2,2.0,12560,69.0,2,7,2137,28.0,42000,1,11,2,9,1878.0,34360.0,5.9,0,0,140.0,212,1,1,0,1.0,NaN,2.0,NaN,0,2,5,3,3,16,7,18,5,9,0.0,0,0,3,100.0,0.0,1,0,60124,16901,36500,18124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,12000,12000,12000.0,60 months,13.56%,276.49,C,C1,NaN,< 1 year,MORTGAGE,40000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,180xx,PA,19.23,0,Aug-2005,2,NaN,NaN,8,0,23195,55.5%,9,w,10979.70,10979.70,1921.870000,1921.87,1020.30,901.57,0.0,0.0,0.0,Jul-2019,276.49,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,32462,1,1,1,1,4.0,9267,103.0,2,2,9747,64.0,41800,1,0,3,3,4058.0,16601.0,54.9,0,0,4.0,149,9,4,1,10.0,NaN,4.0,NaN,0,5,6,5,5,1,7,7,6,8,0.0,0,0,3,100.0,60.0,0,0,50800,32462,36800,9000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,10000,10000,10000.0,60 months,19.92%,264.50,D,D3,Material Handler,10+ years,MORTGAGE,80000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,648xx,MO,20.67,0,Apr-2005,0,37.0,NaN,11,0,13198,73.7%,19,w,9275.20,9275.20,1834.900000,1834.90,724.80,1110.10,0.0,0.0,0.0,Jul-2019,264.50,Sep-2019,Aug-2019,0,37.0,1,Individual,NaN,NaN,NaN,0,116,110120,0,2,0,1,15.0,24408,70.0,1,1,6521,72.0,17900,0,0,1,2,10011.0,779.0,90.3,0,0,148.0,164,11,11,1,149.0,37.0,11.0,37.0,0,2,8,2,4,6,8,12,8,11,0.0,0,0,1,84.2,50.0,0,0,170230,37606,8000,55030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,16000,16000,16000.0,60 months,17.97%,406.04,D,D1,Instructional Coordinator,5 years,MORTGAGE,51000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,284xx,NC,21.91,0,Oct-2005,1,52.0,NaN,11,0,7326,24.8%,27,w,14781.25,14781.25,2818.320000,2818.32,1218.75,1599.57,0.0,0.0,0.0,Jul-2019,406.04,Sep-2019,Aug-2019,0,52.0,1,Individual,NaN,NaN,NaN,0,0,39339,3,8,2,2,2.0,32013,83.0,1,1,3881,58.0,29500,0,0,1,3,3576.0,22174.0,24.8,0,0,123.0,158,6,2,0,6.0,52.0,4.0,52.0,6,2,2,3,6,21,3,6,2,11,0.0,0,0,3,77.8,0.0,0,0,67924,39339,29500,38424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,16000,16000,16000.0,60 months,26.31%,481.99,E,E4,Financial Relationship Associate,< 1 year,RENT,33000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,290xx,SC,33.62,0,Sep-2010,1,NaN,NaN,17,0,22872,65.5%,22,w,15019.01,15019.01,3338.850000,3338.85,980.99,2357.86,0.0,0.0,0.0,Jul-2019,481.99,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,29869,1,1,0,1,24.0,6997,65.0,1,1,2703,65.0,34900,0,3,1,2,1757.0,4596.0,66.9,0,0,29.0,99,2,2,0,2.0,NaN,3.0,NaN,0,6,11,9,13,2,16,20,11,17,0.0,0,0,1,100.0,55.6,0,0,45709,29869,13900,10809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,15000,15000,14975.0,60 months,14.47%,352.69,C,C2,NaN,NaN,MORTGAGE,30000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,756xx,TX,41.60,0,Oct-1999,0,NaN,NaN,20,0,20049,37.2%,30,f,13753.20,13730.27,2450.740000,2446.66,1246.80,1203.94,0.0,0.0,0.0,Jul-2019,352.69,Sep-2019,Aug-2019,0,NaN,1,Joint App,55000.0,34.95,Source Verified,0,0,65496,1,1,0,1,16.0,4458,31.0,1,1,3616,36.0,53900,0,2,0,2,3275.0,2545.0,74.3,0,0,149.0,230,6,6,1,31.0,NaN,NaN,NaN,0,4,13,4,5,8,18,21,13,20,0.0,0,0,1,100.0,50.0,0,0,118790,24507,9900,14490,29704.0,Oct-1999,0.0,0.0,16.0,48.8,0.0,15.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,13000,13000,13000.0,36 months,23.40%,505.95,E,E1,Sale Representative,2 years,MORTGAGE,90000.0,Verified,Dec-2018,Current,n,NaN,NaN,other,Other,191xx,PA,39.73,0,May-2007,0,NaN,NaN,14,0,52013,83.1%,20,w,11126.05,11126.05,3516.300000,3516.30,1873.95,1642.35,0.0,0.0,0.0,Jul-2019,505.95,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,87876,1,7,1,3,1.0,35863,48.0,0,1,18037,64.0,62600,2,0,1,4,6277.0,9503.0,83.8,0,0,131.0,139,16,1,0,16.0,NaN,10.0,NaN,0,6,7,6,7,11,7,9,7,14,0.0,0,0,1,100.0,66.7,0,0,137276,87876,58600,74676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,9600,9600,9600.0,36 months,23.40%,373.62,E,E1,driver coordinator,9 years,RENT,65000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,265xx,WV,23.01,1,Sep-2003,0,16.0,NaN,12,0,10678,37.5%,20,f,8298.34,8298.34,2596.620000,2596.62,1301.66,1294.96,0.0,0.0,0.0,Aug-2019,373.62,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,66,24165,0,2,0,0,43.0,13487,33.0,1,1,2264,35.0,28500,0,0,0,1,2014.0,232.0,96.9,0,0,183.0,92,12,12,0,27.0,NaN,15.0,30.0,0,7,9,7,8,8,10,12,9,12,0.0,0,0,1,90.0,85.7,0,0,68902,24165,7600,40402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,3500,3500,3500.0,36 months,20.89%,131.67,D,D4,gas attendant,10+ years,MORTGAGE,40000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,car,Car financing,078xx,NJ,9.09,0,Oct-2004,1,24.0,NaN,4,0,1944,33.5%,18,w,3004.80,3004.80,915.600000,915.60,495.20,420.40,0.0,0.0,0.0,Aug-2019,131.67,Sep-2019,Aug-2019,0,48.0,1,Joint App,59500.0,10.59,Source Verified,0,0,189794,1,1,1,1,7.0,24958,100.0,2,2,1317,87.0,5800,1,0,3,3,47449.0,3683.0,26.3,0,0,150.0,170,1,1,4,8.0,48.0,1.0,48.0,2,1,2,1,8,3,2,11,2,4,0.0,0,0,3,38.9,0.0,0,0,217000,26902,5000,25000,6902.0,May-2003,0.0,3.0,6.0,47.9,0.0,21.0,0.0,0.0,46.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,25000,25000,25000.0,60 months,16.91%,620.11,C,C5,Processor,10+ years,MORTGAGE,23878.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,453xx,OH,6.26,0,Oct-2010,0,NaN,NaN,4,0,3044,54.4%,8,w,23044.13,23044.13,4305.540000,4305.54,1955.87,2349.67,0.0,0.0,0.0,Jul-2019,620.11,Sep-2019,Aug-2019,0,NaN,1,Joint App,64793.0,18.91,Not Verified,0,0,79660,0,0,0,0,47.0,0,NaN,0,0,1044,54.0,5600,0,0,0,0,19915.0,0.0,104.4,0,0,90.0,98,27,27,2,84.0,NaN,NaN,NaN,0,1,3,1,1,2,3,4,3,4,0.0,0,0,0,100.0,100.0,0,0,92334,3044,1000,0,24654.0,Aug-2003,0.0,2.0,9.0,78.9,1.0,12.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,16000,16000,16000.0,60 months,20.89%,431.87,D,D4,Neonatal Nurse Practitioner,4 years,MORTGAGE,120000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,720xx,AR,27.57,1,Jul-2005,0,8.0,NaN,13,0,18826,82.2%,37,w,14868.93,14868.93,2995.240000,2995.24,1131.07,1864.17,0.0,0.0,0.0,Jul-2019,431.87,Sep-2019,Aug-2019,0,35.0,1,Individual,NaN,NaN,NaN,0,0,434239,1,6,1,4,4.0,247928,90.0,1,1,9439,87.0,22900,6,1,2,5,33403.0,430.0,96.8,0,0,136.0,146,12,4,2,12.0,48.0,4.0,8.0,2,2,4,2,5,24,6,10,4,13,0.0,0,0,2,86.5,100.0,0,0,444217,266754,13500,239338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,13000,13000,13000.0,60 months,14.47%,305.67,C,C2,Stationary Engineer,10+ years,MORTGAGE,75000.0,Not Verified,Dec-2018,Fully Paid,n,NaN,NaN,debt_consolidation,Debt consolidation,741xx,OK,26.16,0,Feb-2001,1,NaN,NaN,9,0,15551,58.2%,13,w,0.00,0.00,13499.621880,13499.62,13000.00,499.62,0.0,0.0,0.0,Apr-2019,12903.96,NaN,Apr-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,131400,0,5,1,4,10.0,35369,70.0,0,0,13287,66.0,26700,2,0,1,4,14600.0,11149.0,58.2,0,0,159.0,214,81,10,1,81.0,NaN,5.0,NaN,0,3,3,3,3,8,3,4,3,9,0.0,0,0,1,100.0,33.3,0,0,176598,50920,26700,50898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
list(df.columns)

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [0]:
df.shape

(128412, 144)

In [0]:
# List columns with total of missing values. Ascending order is default so have to reverse it

df.isnull().sum().sort_values(ascending=False)

id                                            128412
desc                                          128412
member_id                                     128412
url                                           128412
orig_projected_additional_accrued_interest    128386
hardship_type                                 128385
hardship_last_payment_amount                  128385
hardship_payoff_balance_amount                128385
hardship_reason                               128385
hardship_loan_status                          128385
hardship_dpd                                  128385
hardship_length                               128385
payment_plan_start_date                       128385
hardship_end_date                             128385
hardship_start_date                           128385
hardship_amount                               128385
deferral_term                                 128385
hardship_status                               128385
settlement_percentage                         128301
settlement_term                               128301
settlement_status                             128301
settlement_amount                             128301
settlement_date                               128301
debt_settlement_flag_date                     128301
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
sec_app_collections_12_mths_ex_med            111630
dti_joint                                     111630
annual_inc_joint                              111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
mths_since_recent_bc_dlq                      103243
mths_since_last_major_derog                    99232
mths_since_recent_revol_delinq                 91630
mths_since_last_delinq                         72196
emp_title                                      20947
il_util                                        20274
next_pymnt_d                                   16123
mths_since_recent_inq                          16047
emp_length                                     11704
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
num_tl_120dpd_2m                                2859
bc_util                                         1754
percent_bc_gt_75                                1692
bc_open_to_buy                                  1691
mths_since_recent_bc                            1591
dti                                              237
last_pymnt_d                                     159
revol_util                                       156
all_util                                          37
avg_cur_bal                                       13
last_credit_pull_d                                 1
int_rate                                           0
initial_list_status                                0
out_prncp                                          0
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
total_rec_prncp                                    0
purpose                                            0
total_rec_int                                      0
total_acc                                          0
funded_amnt_inv                                    0
funded_amnt                                        0
total_rec_late_fee                                 0
recoveries                                         0
loan_amnt                                          0
collection_recovery_fee                            0
term                                               0
revol_bal                                          0
installment                                        0
pymnt_plan                                         0
loan_status                                        0
title                                              0
zip_code                                           0
addr_state                                         0
issue_d                                            0
delinq_2yrs                                        0
earliest_cr_line                                   0
verification_status                                0
annual_inc                                         0
inq_last_6mths                                     0
home_ownership                                     0
sub_grade                                          0
grade                                              0
open_acc                                           0
pub_rec                                            0
debt_settlement_flag                               0
open_il_12m                                        0
last_pymnt_amnt                                    0
num_sats                                           0
num_accts_ever_120_pd                              0
num_actv_bc_tl                                     0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_tl_30dpd                                       0
collections_12_mths_ex_med                         0
num_tl_90g_dpd_24m                                 0
num_tl_op_past_12m                                 0
pct_tl_nvr_dlq                                     0
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_old_rev_tl_op                               0
policy_code                                        0
application_type                                   0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
hardship_flag                                      0
open_il_24m                                        0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
total_cu_tl                                        0
inq_last_12m                                       0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
inq_fi                                             0
dtype: int64

In [0]:
# Remove columns from the list

df=df.drop(columns=['id','member_id','desc','url'])
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,10000,10000,10000.0,36 months,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,4000,4000,4000.0,36 months,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,5000,5000,5000.0,36 months,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,23000,23000,23000.0,60 months,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,8000,8000,8000.0,36 months,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
df.isnull().sum().sort_values(ascending=False)

orig_projected_additional_accrued_interest    128386
hardship_loan_status                          128385
hardship_dpd                                  128385
hardship_reason                               128385
hardship_status                               128385
deferral_term                                 128385
hardship_amount                               128385
hardship_start_date                           128385
hardship_end_date                             128385
payment_plan_start_date                       128385
hardship_length                               128385
hardship_type                                 128385
hardship_payoff_balance_amount                128385
hardship_last_payment_amount                  128385
settlement_percentage                         128301
debt_settlement_flag_date                     128301
settlement_status                             128301
settlement_date                               128301
settlement_amount                             128301
settlement_term                               128301
sec_app_mths_since_last_major_derog           123258
verification_status_joint                     113564
mths_since_last_record                        112962
sec_app_revol_util                            111888
annual_inc_joint                              111630
sec_app_collections_12_mths_ex_med            111630
dti_joint                                     111630
revol_bal_joint                               111630
sec_app_earliest_cr_line                      111630
sec_app_inq_last_6mths                        111630
sec_app_mort_acc                              111630
sec_app_open_acc                              111630
sec_app_open_act_il                           111630
sec_app_num_rev_accts                         111630
sec_app_chargeoff_within_12_mths              111630
mths_since_recent_bc_dlq                      103243
mths_since_last_major_derog                    99232
mths_since_recent_revol_delinq                 91630
mths_since_last_delinq                         72196
emp_title                                      20947
il_util                                        20274
next_pymnt_d                                   16123
mths_since_recent_inq                          16047
emp_length                                     11704
mo_sin_old_il_acct                              4478
mths_since_rcnt_il                              4478
num_tl_120dpd_2m                                2859
bc_util                                         1754
percent_bc_gt_75                                1692
bc_open_to_buy                                  1691
mths_since_recent_bc                            1591
dti                                              237
last_pymnt_d                                     159
revol_util                                       156
all_util                                          37
avg_cur_bal                                       13
last_credit_pull_d                                 1
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
out_prncp                                          0
total_rec_prncp                                    0
total_rec_late_fee                                 0
initial_list_status                                0
recoveries                                         0
total_acc                                          0
collection_recovery_fee                            0
last_pymnt_amnt                                    0
total_rec_int                                      0
loan_status                                        0
revol_bal                                          0
verification_status                                0
funded_amnt                                        0
funded_amnt_inv                                    0
term                                               0
int_rate                                           0
installment                                        0
grade                                              0
sub_grade                                          0
home_ownership                                     0
annual_inc                                         0
issue_d                                            0
pub_rec                                            0
pymnt_plan                                         0
purpose                                            0
title                                              0
zip_code                                           0
addr_state                                         0
delinq_2yrs                                        0
earliest_cr_line                                   0
inq_last_6mths                                     0
open_acc                                           0
collections_12_mths_ex_med                         0
inq_last_12m                                       0
policy_code                                        0
num_tl_90g_dpd_24m                                 0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_sats                                           0
num_tl_30dpd                                       0
num_tl_op_past_12m                                 0
application_type                                   0
pct_tl_nvr_dlq                                     0
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
hardship_flag                                      0
debt_settlement_flag                               0
num_actv_bc_tl                                     0
num_accts_ever_120_pd                              0
mort_acc                                           0
mo_sin_rcnt_tl                                     0
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
open_il_12m                                        0
open_il_24m                                        0
total_bal_il                                       0
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
total_rev_hi_lim                                   0
inq_fi                                             0
total_cu_tl                                        0
acc_open_past_24mths                               0
chargeoff_within_12_mths                           0
delinq_amnt                                        0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
loan_amnt                                          0
dtype: int64

In [0]:
# Pull 'term' column
df['term']

0          36 months
1          36 months
2          36 months
3          60 months
4          36 months
5          60 months
6          36 months
7          60 months
8          36 months
9          60 months
10         60 months
11         60 months
12         60 months
13         60 months
14         36 months
15         36 months
16         36 months
17         60 months
18         60 months
19         60 months
20         36 months
21         36 months
22         36 months
23         36 months
24         60 months
25         36 months
26         36 months
27         60 months
28         36 months
29         36 months
30         36 months
31         36 months
32         36 months
33         36 months
34         36 months
35         36 months
36         36 months
37         36 months
38         60 months
39         36 months
40         36 months
41         36 months
42         60 months
43         60 months
44         36 months
45         36 months
46         60 months
47         36 months
48         60 months
49         36 months
50         36 months
51         36 months
52         36 months
53         60 months
54         36 months
55         36 months
56         60 months
57         36 months
58         60 months
59         36 months
60         60 months
61         36 months
62         36 months
63         36 months
64         60 months
65         36 months
66         60 months
67         36 months
68         36 months
69         36 months
70         36 months
71         36 months
72         36 months
73         36 months
74         60 months
75         36 months
76         60 months
77         60 months
78         60 months
79         36 months
80         36 months
81         36 months
82         36 months
83         36 months
84         36 months
85         60 months
86         36 months
87         60 months
88         60 months
89         60 months
90         36 months
91         36 months
92         60 months
93         36 months
94         36 months
95         36 months
96         36 months
97         36 months
98         36 months
99         36 months
100        36 months
101        60 months
102        36 months
103        36 months
104        60 months
105        36 months
106        36 months
107        36 months
108        36 months
109        36 months
110        60 months
111        60 months
112        36 months
113        36 months
114        36 months
115        36 months
116        36 months
117        36 months
118        36 months
119        36 months
120        60 months
121        60 months
122        36 months
123        36 months
124        36 months
125        60 months
126        60 months
127        36 months
128        60 months
129        36 months
130        60 months
131        60 months
132        60 months
133        60 months
134        36 months
135        60 months
136        60 months
137        36 months
138        60 months
139        36 months
140        60 months
141        36 months
142        60 months
143        60 months
144        60 months
145        36 months
146        36 months
147        60 months
148        60 months
149        36 months
150        60 months
151        60 months
152        36 months
153        36 months
154        36 months
155        36 months
156        60 months
157        60 months
158        60 months
159        36 months
160        60 months
161        36 months
162        36 months
163        60 months
164        36 months
165        36 months
166        36 months
167        60 months
168        36 months
169        36 months
170        36 months
171        36 months
172        60 months
173        36 months
174        36 months
175        36 months
176        60 months
177        60 months
178        36 months
179        60 months
180        36 months
181        36 months
182        36 months
183        36 months
184        36 months
185        36 months
186        36 months
187        36 months
188        36 months
189        36 months
190        60 months
191        36 months
192        36 months
193        36 months
194        36 months
195        60 months
196        60 months
197        36 months
198        36 months
199        60 months
200        60 months
201        36 months
202        36 months
203        36 months
204        36 months
205        36 months
206        60 months
207        36 months
208        36 months
209        36 months
210        60 months
211        36 months
212        36 months
213        36 months
214        36 months
215        36 months
216        36 months
217        36 months
218        36 months
219        60 months
220        36 months
221        60 months
222        36 months
223        60 months
224        60 months
225        36 months
226        60 months
227        36 months
228        60 months
229        36 months
230        60 months
231        36 months
232        36 months
233        36 months
234        36 months
235        60 months
236        60 months
237        36 months
238        60 months
239        36 months
240        60 months
241        36 months
242        36 months
243        36 months
244        36 months
245        36 months
246        60 months
247        36 months
248        36 months
249        60 months
             ...
128162     60 months
128163     36 months
128164     36 months
128165     36 months
128166     60 months
128167     36 months
128168     36 months
128169     36 months
128170     36 months
128171     36 months
128172     36 months
128173     36 months
128174     36 months
128175     36 months
128176     36 months
128177     36 months
128178     36 months
128179     60 months
128180     36 months
128181     36 months
128182     60 months
128183     60 months
128184     36 months
128185     36 months
128186     36 months
128187     60 months
128188     60 months
128189     60 months
128190     36 months
128191     36 months
128192     60 months
128193     60 months
128194     36 months
128195     60 months
128196     36 months
128197     36 months
128198     36 months
128199     36 months
128200     36 months
128201     36 months
128202     36 months
128203     36 months
128204     36 months
128205     36 months
128206     36 months
128207     36 months
128208     60 months
128209     36 months
128210     36 months
128211     36 months
128212     36 months
128213     60 months
128214     36 months
128215     36 months
128216     36 months
128217     36 months
128218     60 months
128219     36 months
128220     36 months
128221     36 months
128222     60 months
128223     36 months
128224     36 months
128225     36 months
128226     36 months
128227     36 months
128228     36 months
128229     60 months
128230     36 months
128231     36 months
128232     36 months
128233     36 months
128234     36 months
128235     36 months
128236     36 months
128237     36 months
128238     36 months
128239     60 months
128240     36 months
128241     60 months
128242     36 months
128243     36 months
128244     36 months
128245     36 months
128246     36 months
128247     36 months
128248     36 months
128249     36 months
128250     36 months
128251     36 months
128252     60 months
128253     36 months
128254     36 months
128255     60 months
128256     60 months
128257     60 months
128258     36 months
128259     36 months
128260     36 months
128261     36 months
128262     60 months
128263     36 months
128264     36 months
128265     36 months
128266     36 months
128267     36 months
128268     60 months
128269     60 months
128270     36 months
128271     36 months
128272     36 months
128273     60 months
128274     36 months
128275     36 months
128276     36 months
128277     60 months
128278     36 months
128279     36 months
128280     36 months
128281     36 months
128282     36 months
128283     36 months
128284     36 months
128285     36 months
128286     36 months
128287     36 months
128288     36 months
128289     36 months
128290     36 months
128291     36 months
128292     36 months
128293     60 months
128294     36 months
128295     36 months
128296     36 months
128297     36 months
128298     36 months
128299     60 months
128300     36 months
128301     36 months
128302     36 months
128303     36 months
128304     36 months
128305     36 months
128306     60 months
128307     36 months
128308     36 months
128309     36 months
128310     60 months
128311     36 months
128312     60 months
128313     60 months
128314     60 months
128315     36 months
128316     36 months
128317     60 months
128318     36 months
128319     36 months
128320     36 months
128321     60 months
128322     36 months
128323     36 months
128324     60 months
128325     36 months
128326     36 months
128327     36 months
128328     36 months
128329     36 months
128330     60 months
128331     60 months
128332     36 months
128333     36 months
128334     36 months
128335     36 months
128336     36 months
128337     60 months
128338     36 months
128339     36 months
128340     36 months
128341     60 months
128342     36 months
128343     36 months
128344     60 months
128345     36 months
128346     36 months
128347     60 months
128348     60 months
128349     36 months
128350     36 months
128351     36 months
128352     36 months
128353     36 months
128354     36 months
128355     60 months
128356     36 months
128357     36 months
128358     36 months
128359     36 months
128360     36 months
128361     60 months
128362     36 months
128363     60 months
128364     36 months
128365     36 months
128366     36 months
128367     36 months
128368     36 months
128369     36 months
128370     36 months
128371     36 months
128372     60 months
128373     60 months
128374     60 months
128375     36 months
128376     60 months
128377     36 months
128378     36 months
128379     60 months
128380     60 months
128381     36 months
128382     60 months
128383     36 months
128384     36 months
128385     36 months
128386     60 months
128387     36 months
128388     36 months
128389     36 months
128390     36 months
128391     36 months
128392     36 months
128393     36 months
128394     36 months
128395     36 months
128396     60 months
128397     60 months
128398     60 months
128399     36 months
128400     60 months
128401     36 months
128402     60 months
128403     36 months
128404     36 months
128405     60 months
128406     36 months
128407     36 months
128408     36 months
128409     36 months
128410     36 months
128411     36 months
Name: term, Length: 128412, dtype: object

In [0]:
df.dtypes

loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                       object
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                     int64
earliest_cr_line                               object
inq_last_6mths                                  int64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                        int64
pub_rec                                         int64
revol_bal                                       int64
revol_util                                     object
total_acc                                       int64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                      int64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                  int64
tot_coll_amt                                    int64
tot_cur_bal                                     int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
mths_since_rcnt_il                            float64
total_bal_il                                    int64
il_util                                       float64
open_rv_12m                                     int64
open_rv_24m                                     int64
max_bal_bc                                      int64
all_util                                      float64
total_rev_hi_lim                                int64
inq_fi                                          int64
total_cu_tl                                     int64
inq_last_12m                                    int64
acc_open_past_24mths                            int64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
delinq_amnt                                     int64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                            int64
tax_liens                                       int64
tot_hi_cred_lim                                 int64
total_bal_ex_mort                               int64
total_bc_limit                                  int64
total_il_high_credit_limit                      int64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
dtype: object

In [0]:
# Remove 'months' and remove space
term='36 months'
term.strip('months')[:-1]

'36'

In [0]:
type(term.strip('months')[:-1])

str

In [0]:
# Convert to float
float(term.strip('months')[:-1])

36.0

In [0]:
type(float(term.strip('months')[:-1]))

float

In [0]:
# Create function that works on any column
def remove_months_to_float(string):
  return float(string.strip('months')[:-1])

remove_months_to_float(term)

36.0

In [0]:
df['term']=df['term'].apply(remove_months_to_float)
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,10000,10000,10000.0,36.0,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,Jul-2019,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,4000,4000,4000.0,36.0,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,Jul-2019,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,5000,5000,5000.0,36.0,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,Jun-2019,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,23000,23000,23000.0,60.0,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,Jul-2019,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,8000,8000,8000.0,36.0,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,Jul-2019,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
df.dtypes

loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                          float64
int_rate                                       object
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                     int64
earliest_cr_line                               object
inq_last_6mths                                  int64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                        int64
pub_rec                                         int64
revol_bal                                       int64
revol_util                                     object
total_acc                                       int64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                      int64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                  int64
tot_coll_amt                                    int64
tot_cur_bal                                     int64
open_acc_6m                                     int64
open_act_il                                     int64
open_il_12m                                     int64
open_il_24m                                     int64
mths_since_rcnt_il                            float64
total_bal_il                                    int64
il_util                                       float64
open_rv_12m                                     int64
open_rv_24m                                     int64
max_bal_bc                                      int64
all_util                                      float64
total_rev_hi_lim                                int64
inq_fi                                          int64
total_cu_tl                                     int64
inq_last_12m                                    int64
acc_open_past_24mths                            int64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                        int64
delinq_amnt                                     int64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                            int64
mo_sin_rcnt_rev_tl_op                           int64
mo_sin_rcnt_tl                                  int64
mort_acc                                        int64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                           int64
num_actv_bc_tl                                  int64
num_actv_rev_tl                                 int64
num_bc_sats                                     int64
num_bc_tl                                       int64
num_il_tl                                       int64
num_op_rev_tl                                   int64
num_rev_accts                                   int64
num_rev_tl_bal_gt_0                             int64
num_sats                                        int64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                    int64
num_tl_90g_dpd_24m                              int64
num_tl_op_past_12m                              int64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                            int64
tax_liens                                       int64
tot_hi_cred_lim                                 int64
total_bal_ex_mort                               int64
total_bc_limit                                  int64
total_il_high_credit_limit                      int64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
loan_status_is_great                             bool
dtype: object

In [0]:
# Does 'loan_status' column has any missing values
df['loan_status'].isnull().sum()

0

In [0]:
# Look up all loan status parameters
df['loan_status'].value_counts()

Current               108584
Fully Paid             13929
Late (31-120 days)      2291
Charged Off             2194
In Grace Period          849
Late (16-30 days)        560
Default                    5
Name: loan_status, dtype: int64

In [0]:
#Create 'loan_status_is_great' column where 'Current' and 'Fully Paid' status marked as True
df['loan_status_is_great'] = True
df['loan_status_is_great']= df['loan_status'].str.contains('Current','Fully Paid')
df['loan_status_is_great']

0          True
1          True
2         False
3          True
4          True
5          True
6          True
7          True
8         False
9          True
10         True
11         True
12         True
13         True
14         True
15         True
16         True
17         True
18         True
19        False
20         True
21         True
22         True
23         True
24         True
25         True
26         True
27         True
28         True
29         True
30         True
31         True
32         True
33         True
34         True
35        False
36        False
37         True
38         True
39         True
40         True
41         True
42         True
43         True
44         True
45         True
46         True
47         True
48         True
49         True
50         True
51         True
52         True
53         True
54         True
55         True
56         True
57         True
58        False
59         True
60         True
61         True
62         True
63         True
64         True
65         True
66        False
67        False
68         True
69        False
70         True
71         True
72         True
73         True
74         True
75         True
76        False
77         True
78         True
79         True
80         True
81        False
82        False
83         True
84         True
85         True
86        False
87         True
88         True
89         True
90         True
91         True
92         True
93         True
94         True
95         True
96         True
97         True
98        False
99         True
100        True
101        True
102        True
103        True
104        True
105        True
106        True
107       False
108        True
109        True
110        True
111        True
112       False
113        True
114        True
115        True
116        True
117        True
118       False
119        True
120        True
121        True
122        True
123        True
124        True
125        True
126        True
127        True
128        True
129        True
130        True
131        True
132        True
133        True
134        True
135       False
136        True
137        True
138       False
139       False
140        True
141        True
142        True
143        True
144       False
145        True
146        True
147        True
148        True
149        True
150        True
151       False
152        True
153        True
154        True
155        True
156        True
157       False
158        True
159        True
160        True
161        True
162        True
163        True
164        True
165        True
166       False
167        True
168        True
169        True
170        True
171        True
172        True
173        True
174        True
175        True
176        True
177        True
178       False
179        True
180        True
181       False
182        True
183        True
184        True
185       False
186       False
187       False
188        True
189        True
190        True
191        True
192       False
193        True
194        True
195        True
196        True
197        True
198        True
199       False
200       False
201        True
202        True
203        True
204        True
205        True
206        True
207        True
208        True
209        True
210        True
211       False
212        True
213       False
214        True
215        True
216       False
217        True
218       False
219        True
220       False
221       False
222        True
223        True
224        True
225        True
226        True
227        True
228        True
229        True
230       False
231        True
232        True
233        True
234        True
235        True
236        True
237        True
238        True
239        True
240        True
241        True
242        True
243        True
244        True
245        True
246       False
247        True
248        True
249        True
          ...
128162     True
128163     True
128164     True
128165    False
128166     True
128167     True
128168     True
128169     True
128170     True
128171     True
128172     True
128173     True
128174     True
128175     True
128176     True
128177     True
128178     True
128179    False
128180     True
128181     True
128182     True
128183     True
128184     True
128185     True
128186     True
128187     True
128188     True
128189     True
128190     True
128191     True
128192     True
128193    False
128194     True
128195     True
128196    False
128197     True
128198     True
128199     True
128200     True
128201     True
128202     True
128203    False
128204     True
128205     True
128206     True
128207     True
128208     True
128209     True
128210     True
128211     True
128212     True
128213     True
128214    False
128215     True
128216     True
128217     True
128218     True
128219     True
128220     True
128221     True
128222     True
128223     True
128224     True
128225    False
128226     True
128227    False
128228     True
128229     True
128230     True
128231     True
128232     True
128233     True
128234     True
128235     True
128236     True
128237     True
128238    False
128239     True
128240     True
128241     True
128242    False
128243    False
128244    False
128245    False
128246     True
128247    False
128248     True
128249     True
128250     True
128251     True
128252     True
128253     True
128254     True
128255     True
128256     True
128257     True
128258     True
128259     True
128260     True
128261     True
128262    False
128263     True
128264     True
128265     True
128266     True
128267     True
128268    False
128269     True
128270     True
128271     True
128272    False
128273     True
128274    False
128275     True
128276     True
128277     True
128278     True
128279     True
128280    False
128281     True
128282     True
128283    False
128284     True
128285     True
128286     True
128287     True
128288     True
128289     True
128290     True
128291     True
128292     True
128293    False
128294     True
128295     True
128296     True
128297     True
128298     True
128299     True
128300     True
128301     True
128302     True
128303     True
128304     True
128305     True
128306     True
128307     True
128308    False
128309    False
128310     True
128311     True
128312     True
128313     True
128314    False
128315     True
128316     True
128317     True
128318     True
128319    False
128320    False
128321     True
128322     True
128323     True
128324     True
128325     True
128326    False
128327    False
128328     True
128329     True
128330     True
128331     True
128332     True
128333     True
128334     True
128335     True
128336     True
128337    False
128338     True
128339     True
128340     True
128341     True
128342     True
128343     True
128344     True
128345     True
128346     True
128347     True
128348     True
128349     True
128350    False
128351    False
128352     True
128353     True
128354     True
128355     True
128356     True
128357     True
128358    False
128359     True
128360     True
128361     True
128362     True
128363     True
128364     True
128365     True
128366     True
128367     True
128368     True
128369     True
128370     True
128371    False
128372     True
128373     True
128374    False
128375     True
128376     True
128377     True
128378     True
128379     True
128380     True
128381     True
128382     True
128383     True
128384     True
128385     True
128386     True
128387     True
128388     True
128389    False
128390    False
128391    False
128392     True
128393     True
128394     True
128395     True
128396     True
128397    False
128398     True
128399     True
128400     True
128401     True
128402     True
128403     True
128404    False
128405     True
128406     True
128407    False
128408     True
128409     True
128410     True
128411     True
Name: loan_status_is_great, Length: 128412, dtype: bool

In [0]:
# Since True/False correspond to 1/0 convert to integer to reflect it

df['loan_status_is_great'] = df['loan_status_is_great'].astype(int)
df['loan_status_is_great']

0         1
1         1
2         0
3         1
4         1
5         1
6         1
7         1
8         0
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        0
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
30        1
31        1
32        1
33        1
34        1
35        0
36        0
37        1
38        1
39        1
40        1
41        1
42        1
43        1
44        1
45        1
46        1
47        1
48        1
49        1
50        1
51        1
52        1
53        1
54        1
55        1
56        1
57        1
58        0
59        1
60        1
61        1
62        1
63        1
64        1
65        1
66        0
67        0
68        1
69        0
70        1
71        1
72        1
73        1
74        1
75        1
76        0
77        1
78        1
79        1
80        1
81        0
82        0
83        1
84        1
85        1
86        0
87        1
88        1
89        1
90        1
91        1
92        1
93        1
94        1
95        1
96        1
97        1
98        0
99        1
100       1
101       1
102       1
103       1
104       1
105       1
106       1
107       0
108       1
109       1
110       1
111       1
112       0
113       1
114       1
115       1
116       1
117       1
118       0
119       1
120       1
121       1
122       1
123       1
124       1
125       1
126       1
127       1
128       1
129       1
130       1
131       1
132       1
133       1
134       1
135       0
136       1
137       1
138       0
139       0
140       1
141       1
142       1
143       1
144       0
145       1
146       1
147       1
148       1
149       1
150       1
151       0
152       1
153       1
154       1
155       1
156       1
157       0
158       1
159       1
160       1
161       1
162       1
163       1
164       1
165       1
166       0
167       1
168       1
169       1
170       1
171       1
172       1
173       1
174       1
175       1
176       1
177       1
178       0
179       1
180       1
181       0
182       1
183       1
184       1
185       0
186       0
187       0
188       1
189       1
190       1
191       1
192       0
193       1
194       1
195       1
196       1
197       1
198       1
199       0
200       0
201       1
202       1
203       1
204       1
205       1
206       1
207       1
208       1
209       1
210       1
211       0
212       1
213       0
214       1
215       1
216       0
217       1
218       0
219       1
220       0
221       0
222       1
223       1
224       1
225       1
226       1
227       1
228       1
229       1
230       0
231       1
232       1
233       1
234       1
235       1
236       1
237       1
238       1
239       1
240       1
241       1
242       1
243       1
244       1
245       1
246       0
247       1
248       1
249       1
         ..
128162    1
128163    1
128164    1
128165    0
128166    1
128167    1
128168    1
128169    1
128170    1
128171    1
128172    1
128173    1
128174    1
128175    1
128176    1
128177    1
128178    1
128179    0
128180    1
128181    1
128182    1
128183    1
128184    1
128185    1
128186    1
128187    1
128188    1
128189    1
128190    1
128191    1
128192    1
128193    0
128194    1
128195    1
128196    0
128197    1
128198    1
128199    1
128200    1
128201    1
128202    1
128203    0
128204    1
128205    1
128206    1
128207    1
128208    1
128209    1
128210    1
128211    1
128212    1
128213    1
128214    0
128215    1
128216    1
128217    1
128218    1
128219    1
128220    1
128221    1
128222    1
128223    1
128224    1
128225    0
128226    1
128227    0
128228    1
128229    1
128230    1
128231    1
128232    1
128233    1
128234    1
128235    1
128236    1
128237    1
128238    0
128239    1
128240    1
128241    1
128242    0
128243    0
128244    0
128245    0
128246    1
128247    0
128248    1
128249    1
128250    1
128251    1
128252    1
128253    1
128254    1
128255    1
128256    1
128257    1
128258    1
128259    1
128260    1
128261    1
128262    0
128263    1
128264    1
128265    1
128266    1
128267    1
128268    0
128269    1
128270    1
128271    1
128272    0
128273    1
128274    0
128275    1
128276    1
128277    1
128278    1
128279    1
128280    0
128281    1
128282    1
128283    0
128284    1
128285    1
128286    1
128287    1
128288    1
128289    1
128290    1
128291    1
128292    1
128293    0
128294    1
128295    1
128296    1
128297    1
128298    1
128299    1
128300    1
128301    1
128302    1
128303    1
128304    1
128305    1
128306    1
128307    1
128308    0
128309    0
128310    1
128311    1
128312    1
128313    1
128314    0
128315    1
128316    1
128317    1
128318    1
128319    0
128320    0
128321    1
128322    1
128323    1
128324    1
128325    1
128326    0
128327    0
128328    1
128329    1
128330    1
128331    1
128332    1
128333    1
128334    1
128335    1
128336    1
128337    0
128338    1
128339    1
128340    1
128341    1
128342    1
128343    1
128344    1
128345    1
128346    1
128347    1
128348    1
128349    1
128350    0
128351    0
128352    1
128353    1
128354    1
128355    1
128356    1
128357    1
128358    0
128359    1
128360    1
128361    1
128362    1
128363    1
128364    1
128365    1
128366    1
128367    1
128368    1
128369    1
128370    1
128371    0
128372    1
128373    1
128374    0
128375    1
128376    1
128377    1
128378    1
128379    1
128380    1
128381    1
128382    1
128383    1
128384    1
128385    1
128386    1
128387    1
128388    1
128389    0
128390    0
128391    0
128392    1
128393    1
128394    1
128395    1
128396    1
128397    0
128398    1
128399    1
128400    1
128401    1
128402    1
128403    1
128404    0
128405    1
128406    1
128407    0
128408    1
128409    1
128410    1
128411    1
Name: loan_status_is_great, Length: 128412, dtype: int64

In [141]:

df['last_pymnt_d']

0         Jul-2019
1         Jul-2019
2         Jun-2019
3         Jul-2019
4         Jul-2019
5         Jul-2019
6         Aug-2019
7         Jul-2019
8         May-2019
9         Jul-2019
10        Jul-2019
11        Jul-2019
12        Jul-2019
13        Jul-2019
14        Jul-2019
15        Aug-2019
16        Aug-2019
17        Jul-2019
18        Jul-2019
19        Apr-2019
20        Jul-2019
21        Jul-2019
22        Jul-2019
23        Jul-2019
24        Jul-2019
25        Jul-2019
26        Jul-2019
27        Jul-2019
28        Jul-2019
29        Jul-2019
30        Jul-2019
31        Aug-2019
32        Jul-2019
33        Jul-2019
34        Jul-2019
35        Jul-2019
36        Apr-2019
37        Jul-2019
38        Jul-2019
39        Jul-2019
40        Jul-2019
41        Jul-2019
42        Jul-2019
43        Jul-2019
44        Jul-2019
45        Jul-2019
46        Jul-2019
47        Aug-2019
48        Aug-2019
49        Jul-2019
50        Jul-2019
51        Jul-2019
52        Jul-2019
53        Jul-2019
54        Jul-2019
55        Jul-2019
56        Jul-2019
57        Jul-2019
58        Apr-2019
59        Jul-2019
60        Jul-2019
61        Jul-2019
62        Aug-2019
63        Jul-2019
64        Jul-2019
65        Jul-2019
66        Apr-2019
67        May-2019
68        Jul-2019
69        May-2019
70        Aug-2019
71        Jul-2019
72        Aug-2019
73        Jul-2019
74        Jul-2019
75        Aug-2019
76        Apr-2019
77        Aug-2019
78        Jul-2019
79        Jul-2019
80        Jul-2019
81        Feb-2019
82        Jul-2019
83        Jul-2019
84        Jul-2019
85        Jul-2019
86        Jul-2019
87        Jul-2019
88        Jul-2019
89        Aug-2019
90        Jul-2019
91        Aug-2019
92        Jul-2019
93        Aug-2019
94        Aug-2019
95        Aug-2019
96        Jul-2019
97        Aug-2019
98        Feb-2019
99        Jul-2019
100       Jul-2019
101       Jul-2019
102       Aug-2019
103       Aug-2019
104       Jul-2019
105       Aug-2019
106       Jul-2019
107       Jul-2019
108       Jul-2019
109       Jul-2019
110       Jul-2019
111       Jul-2019
112       Apr-2019
113       Jul-2019
114       Jul-2019
115       Aug-2019
116       Jul-2019
117       Jul-2019
118       Feb-2019
119       Jul-2019
120       Aug-2019
121       Jul-2019
122       Jul-2019
123       Jul-2019
124       Jul-2019
125       Jul-2019
126       Jul-2019
127       Jul-2019
128       Jul-2019
129       Aug-2019
130       Jul-2019
131       Jul-2019
132       Jul-2019
133       Jul-2019
134       Jul-2019
135       Apr-2019
136       Jul-2019
137       Jul-2019
138       May-2019
139       Feb-2019
140       Aug-2019
141       Jul-2019
142       Jul-2019
143       Jul-2019
144       Apr-2019
145       Jul-2019
146       Jul-2019
147       Aug-2019
148       Jul-2019
149       Jul-2019
150       Jul-2019
151       Jul-2019
152       Aug-2019
153       Jul-2019
154       Jul-2019
155       Aug-2019
156       Aug-2019
157       Apr-2019
158       Aug-2019
159       Jul-2019
160       Jul-2019
161       Aug-2019
162       Jul-2019
163       Aug-2019
164       Jul-2019
165       Jul-2019
166       Jul-2019
167       Jul-2019
168       Jul-2019
169       Aug-2019
170       Jul-2019
171       Jul-2019
172       Jul-2019
173       Jul-2019
174       Jul-2019
175       Jul-2019
176       Jul-2019
177       Jul-2019
178       Apr-2019
179       Jul-2019
180       Jul-2019
181       Jan-2019
182       Aug-2019
183       Aug-2019
184       Jul-2019
185       May-2019
186       Jul-2019
187       Apr-2019
188       Jul-2019
189       Jul-2019
190       Jul-2019
191       Aug-2019
192       Apr-2019
193       Jul-2019
194       Aug-2019
195       Jul-2019
196       Jul-2019
197       Jul-2019
198       Jul-2019
199       Jul-2019
200       May-2019
201       Jul-2019
202       Jul-2019
203       Jul-2019
204       Jul-2019
205       Jul-2019
206       Aug-2019
207       Jul-2019
208       Jul-2019
209       Aug-2019
210       Jul-2019
211       Jun-2019
212       Jul-2019
213       Apr-2019
214       Aug-2019
215       Jul-2019
216       May-2019
217       Jul-2019
218       Jul-2019
219       Jul-2019
220       Apr-2019
221       Apr-2019
222       Jul-2019
223       Jul-2019
224       Jul-2019
225       Aug-2019
226       Aug-2019
227       Jul-2019
228       Aug-2019
229       Jul-2019
230       Feb-2019
231       Aug-2019
232       Jul-2019
233       Jul-2019
234       Aug-2019
235       Aug-2019
236       Jul-2019
237       Jul-2019
238       Jul-2019
239       Jul-2019
240       Jul-2019
241       Aug-2019
242       Jul-2019
243       Jul-2019
244       Jul-2019
245       Aug-2019
246       May-2019
247       Jul-2019
248       Jul-2019
249       Jul-2019
            ...
128162    Aug-2019
128163    Aug-2019
128164    Aug-2019
128165    Jan-2019
128166    Aug-2019
128167    Aug-2019
128168    Aug-2019
128169    Aug-2019
128170    Aug-2019
128171    Aug-2019
128172    Aug-2019
128173    Aug-2019
128174    Aug-2019
128175    Aug-2019
128176    Aug-2019
128177    Aug-2019
128178    Aug-2019
128179    May-2019
128180    Aug-2019
128181    Aug-2019
128182    Aug-2019
128183    Aug-2019
128184    Aug-2019
128185    Aug-2019
128186    Aug-2019
128187    Aug-2019
128188    Aug-2019
128189    Aug-2019
128190    Aug-2019
128191    Aug-2019
128192    Aug-2019
128193    Aug-2019
128194    Aug-2019
128195    Aug-2019
128196         NaN
128197    Aug-2019
128198    Aug-2019
128199    Aug-2019
128200    Aug-2019
128201    Aug-2019
128202    Aug-2019
128203    Dec-2018
128204    Aug-2019
128205    Aug-2019
128206    Aug-2019
128207    Aug-2019
128208    Aug-2019
128209    Aug-2019
128210    Aug-2019
128211    Aug-2019
128212    Aug-2019
128213    Aug-2019
128214    Jun-2019
128215    Aug-2019
128216    Aug-2019
128217    Aug-2019
128218    Aug-2019
128219    Aug-2019
128220    Aug-2019
128221    Aug-2019
128222    Aug-2019
128223    Aug-2019
128224    Aug-2019
128225    Jul-2019
128226    Aug-2019
128227    Jul-2019
128228    Aug-2019
128229    Aug-2019
128230    Aug-2019
128231    Aug-2019
128232    Aug-2019
128233    Aug-2019
128234    Aug-2019
128235    Aug-2019
128236    Aug-2019
128237    Aug-2019
128238    Aug-2019
128239    Aug-2019
128240    Aug-2019
128241    Aug-2019
128242    Mar-2019
128243    Jun-2019
128244    Mar-2019
128245    Apr-2019
128246    Aug-2019
128247    Jan-2019
128248    Aug-2019
128249    Aug-2019
128250    Aug-2019
128251    Aug-2019
128252    Aug-2019
128253    Aug-2019
128254    Aug-2019
128255    Aug-2019
128256    Aug-2019
128257    Aug-2019
128258    Aug-2019
128259    Aug-2019
128260    Aug-2019
128261    Aug-2019
128262    Feb-2019
128263    Aug-2019
128264    Aug-2019
128265    Aug-2019
128266    Aug-2019
128267    Aug-2019
128268    May-2019
128269    Aug-2019
128270    Aug-2019
128271    Aug-2019
128272    Nov-2018
128273    Aug-2019
128274    Mar-2019
128275    Aug-2019
128276    Aug-2019
128277    Aug-2019
128278    Aug-2019
128279    Aug-2019
128280    May-2019
128281    Aug-2019
128282    Aug-2019
128283    Feb-2019
128284    Aug-2019
128285    Aug-2019
128286    Aug-2019
128287    Aug-2019
128288    Aug-2019
128289    Aug-2019
128290    Aug-2019
128291    Aug-2019
128292    Aug-2019
128293    Jan-2019
128294    Aug-2019
128295    Aug-2019
128296    Aug-2019
128297    Aug-2019
128298    Aug-2019
128299    Aug-2019
128300    Aug-2019
128301    Aug-2019
128302    Aug-2019
128303    Aug-2019
128304    Aug-2019
128305    Aug-2019
128306    Aug-2019
128307    Aug-2019
128308    Apr-2019
128309    Mar-2019
128310    Aug-2019
128311    Aug-2019
128312    Aug-2019
128313    Aug-2019
128314    Apr-2019
128315    Aug-2019
128316    Aug-2019
128317    Aug-2019
128318    Aug-2019
128319    Apr-2019
128320    Mar-2019
128321    Aug-2019
128322    Aug-2019
128323    Aug-2019
128324    Aug-2019
128325    Aug-2019
128326    Apr-2019
128327    Oct-2018
128328    Aug-2019
128329    Aug-2019
128330    Aug-2019
128331    Aug-2019
128332    Aug-2019
128333    Aug-2019
128334    Aug-2019
128335    Aug-2019
128336    Aug-2019
128337         NaN
128338    Aug-2019
128339    Aug-2019
128340    Aug-2019
128341    Aug-2019
128342    Aug-2019
128343    Aug-2019
128344    Aug-2019
128345    Aug-2019
128346    Aug-2019
128347    Aug-2019
128348    Aug-2019
128349    Aug-2019
128350    Mar-2019
128351    Jul-2019
128352    Aug-2019
128353    Aug-2019
128354    Aug-2019
128355    Sep-2019
128356    Aug-2019
128357    Aug-2019
128358    May-2019
128359    Aug-2019
128360    Aug-2019
128361    Sep-2019
128362    Aug-2019
128363    Aug-2019
128364    Aug-2019
128365    Aug-2019
128366    Aug-2019
128367    Jul-2019
128368    Aug-2019
128369    Aug-2019
128370    Aug-2019
128371    Nov-2018
128372    Aug-2019
128373    Aug-2019
128374    May-2019
128375    Aug-2019
128376    Aug-2019
128377    Aug-2019
128378    Aug-2019
128379    Aug-2019
128380    Aug-2019
128381    Aug-2019
128382    Aug-2019
128383    Aug-2019
128384    Aug-2019
128385    Aug-2019
128386    Aug-2019
128387    Aug-2019
128388    Aug-2019
128389    Mar-2019
128390    Jun-2019
128391    Jan-2019
128392    Aug-2019
128393    Aug-2019
128394    Aug-2019
128395    Aug-2019
128396    Aug-2019
128397    Aug-2019
128398    Aug-2019
128399    Aug-2019
128400    Aug-2019
128401    Aug-2019
128402    Aug-2019
128403    Aug-2019
128404    Apr-2019
128405    Aug-2019
128406    Aug-2019
128407    Dec-2018
128408    Aug-2019
128409    Aug-2019
128410    Aug-2019
128411    Aug-2019
Name: last_pymnt_d, Length: 128412, dtype: object

In [0]:
# Convert to datetime format

df['last_pymnt_d']=pd.to_datetime(df['last_pymnt_d'], infer_datetime_format=True)

In [143]:
df.dtypes

loan_amnt                                              int64
funded_amnt                                            int64
funded_amnt_inv                                      float64
term                                                 float64
int_rate                                              object
installment                                          float64
grade                                                 object
sub_grade                                             object
emp_title                                             object
emp_length                                            object
home_ownership                                        object
annual_inc                                           float64
verification_status                                   object
issue_d                                               object
loan_status                                           object
pymnt_plan                                            object
purpose                                               object
title                                                 object
zip_code                                              object
addr_state                                            object
dti                                                  float64
delinq_2yrs                                            int64
earliest_cr_line                                      object
inq_last_6mths                                         int64
mths_since_last_delinq                               float64
mths_since_last_record                               float64
open_acc                                               int64
pub_rec                                                int64
revol_bal                                              int64
revol_util                                            object
total_acc                                              int64
initial_list_status                                   object
out_prncp                                            float64
out_prncp_inv                                        float64
total_pymnt                                          float64
total_pymnt_inv                                      float64
total_rec_prncp                                      float64
total_rec_int                                        float64
total_rec_late_fee                                   float64
recoveries                                           float64
collection_recovery_fee                              float64
last_pymnt_d                                  datetime64[ns]
last_pymnt_amnt                                      float64
next_pymnt_d                                          object
last_credit_pull_d                                    object
collections_12_mths_ex_med                             int64
mths_since_last_major_derog                          float64
policy_code                                            int64
application_type                                      object
annual_inc_joint                                     float64
dti_joint                                            float64
verification_status_joint                             object
acc_now_delinq                                         int64
tot_coll_amt                                           int64
tot_cur_bal                                            int64
open_acc_6m                                            int64
open_act_il                                            int64
open_il_12m                                            int64
open_il_24m                                            int64
mths_since_rcnt_il                                   float64
total_bal_il                                           int64
il_util                                              float64
open_rv_12m                                            int64
open_rv_24m                                            int64
max_bal_bc                                             int64
all_util                                             float64
total_rev_hi_lim                                       int64
inq_fi                                                 int64
total_cu_tl                                            int64
inq_last_12m                                           int64
acc_open_past_24mths                                   int64
avg_cur_bal                                          float64
bc_open_to_buy                                       float64
bc_util                                              float64
chargeoff_within_12_mths                               int64
delinq_amnt                                            int64
mo_sin_old_il_acct                                   float64
mo_sin_old_rev_tl_op                                   int64
mo_sin_rcnt_rev_tl_op                                  int64
mo_sin_rcnt_tl                                         int64
mort_acc                                               int64
mths_since_recent_bc                                 float64
mths_since_recent_bc_dlq                             float64
mths_since_recent_inq                                float64
mths_since_recent_revol_delinq                       float64
num_accts_ever_120_pd                                  int64
num_actv_bc_tl                                         int64
num_actv_rev_tl                                        int64
num_bc_sats                                            int64
num_bc_tl                                              int64
num_il_tl                                              int64
num_op_rev_tl                                          int64
num_rev_accts                                          int64
num_rev_tl_bal_gt_0                                    int64
num_sats                                               int64
num_tl_120dpd_2m                                     float64
num_tl_30dpd                                           int64
num_tl_90g_dpd_24m                                     int64
num_tl_op_past_12m                                     int64
pct_tl_nvr_dlq                                       float64
percent_bc_gt_75                                     float64
pub_rec_bankruptcies                                   int64
tax_liens                                              int64
tot_hi_cred_lim                                        int64
total_bal_ex_mort                                      int64
total_bc_limit                                         int64
total_il_high_credit_limit                             int64
revol_bal_joint                                      float64
sec_app_earliest_cr_line                              object
sec_app_inq_last_6mths                               float64
sec_app_mort_acc                                     float64
sec_app_open_acc                                     float64
sec_app_revol_util                                   float64
sec_app_open_act_il                                  float64
sec_app_num_rev_accts                                float64
sec_app_chargeoff_within_12_mths                     float64
sec_app_collections_12_mths_ex_med                   float64
sec_app_mths_since_last_major_derog                  float64
hardship_flag                                         object
hardship_type                                         object
hardship_reason                                       object
hardship_status                                       object
deferral_term                                        float64
hardship_amount                                      float64
hardship_start_date                                   object
hardship_end_date                                     object
payment_plan_start_date                               object
hardship_length                                      float64
hardship_dpd                                         float64
hardship_loan_status                                  object
orig_projected_additional_accrued_interest           float64
hardship_payoff_balance_amount                       float64
hardship_last_payment_amount                         float64
debt_settlement_flag                                  object
debt_settlement_flag_date                             object
settlement_status                                     object
settlement_date                                       object
settlement_amount                                    float64
settlement_percentage                                float64
settlement_term                                      float64
loan_status_is_great                                    bool
dtype: object

In [144]:
df['last_pymnt_d'].head().values

array(['2019-07-01T00:00:00.000000000', '2019-07-01T00:00:00.000000000',
       '2019-06-01T00:00:00.000000000', '2019-07-01T00:00:00.000000000',
       '2019-07-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [146]:
df['last_pymnt_d'].dt.year

0         2019.0
1         2019.0
2         2019.0
3         2019.0
4         2019.0
5         2019.0
6         2019.0
7         2019.0
8         2019.0
9         2019.0
10        2019.0
11        2019.0
12        2019.0
13        2019.0
14        2019.0
15        2019.0
16        2019.0
17        2019.0
18        2019.0
19        2019.0
20        2019.0
21        2019.0
22        2019.0
23        2019.0
24        2019.0
25        2019.0
26        2019.0
27        2019.0
28        2019.0
29        2019.0
30        2019.0
31        2019.0
32        2019.0
33        2019.0
34        2019.0
35        2019.0
36        2019.0
37        2019.0
38        2019.0
39        2019.0
40        2019.0
41        2019.0
42        2019.0
43        2019.0
44        2019.0
45        2019.0
46        2019.0
47        2019.0
48        2019.0
49        2019.0
50        2019.0
51        2019.0
52        2019.0
53        2019.0
54        2019.0
55        2019.0
56        2019.0
57        2019.0
58        2019.0
59        2019.0
60        2019.0
61        2019.0
62        2019.0
63        2019.0
64        2019.0
65        2019.0
66        2019.0
67        2019.0
68        2019.0
69        2019.0
70        2019.0
71        2019.0
72        2019.0
73        2019.0
74        2019.0
75        2019.0
76        2019.0
77        2019.0
78        2019.0
79        2019.0
80        2019.0
81        2019.0
82        2019.0
83        2019.0
84        2019.0
85        2019.0
86        2019.0
87        2019.0
88        2019.0
89        2019.0
90        2019.0
91        2019.0
92        2019.0
93        2019.0
94        2019.0
95        2019.0
96        2019.0
97        2019.0
98        2019.0
99        2019.0
100       2019.0
101       2019.0
102       2019.0
103       2019.0
104       2019.0
105       2019.0
106       2019.0
107       2019.0
108       2019.0
109       2019.0
110       2019.0
111       2019.0
112       2019.0
113       2019.0
114       2019.0
115       2019.0
116       2019.0
117       2019.0
118       2019.0
119       2019.0
120       2019.0
121       2019.0
122       2019.0
123       2019.0
124       2019.0
125       2019.0
126       2019.0
127       2019.0
128       2019.0
129       2019.0
130       2019.0
131       2019.0
132       2019.0
133       2019.0
134       2019.0
135       2019.0
136       2019.0
137       2019.0
138       2019.0
139       2019.0
140       2019.0
141       2019.0
142       2019.0
143       2019.0
144       2019.0
145       2019.0
146       2019.0
147       2019.0
148       2019.0
149       2019.0
150       2019.0
151       2019.0
152       2019.0
153       2019.0
154       2019.0
155       2019.0
156       2019.0
157       2019.0
158       2019.0
159       2019.0
160       2019.0
161       2019.0
162       2019.0
163       2019.0
164       2019.0
165       2019.0
166       2019.0
167       2019.0
168       2019.0
169       2019.0
170       2019.0
171       2019.0
172       2019.0
173       2019.0
174       2019.0
175       2019.0
176       2019.0
177       2019.0
178       2019.0
179       2019.0
180       2019.0
181       2019.0
182       2019.0
183       2019.0
184       2019.0
185       2019.0
186       2019.0
187       2019.0
188       2019.0
189       2019.0
190       2019.0
191       2019.0
192       2019.0
193       2019.0
194       2019.0
195       2019.0
196       2019.0
197       2019.0
198       2019.0
199       2019.0
200       2019.0
201       2019.0
202       2019.0
203       2019.0
204       2019.0
205       2019.0
206       2019.0
207       2019.0
208       2019.0
209       2019.0
210       2019.0
211       2019.0
212       2019.0
213       2019.0
214       2019.0
215       2019.0
216       2019.0
217       2019.0
218       2019.0
219       2019.0
220       2019.0
221       2019.0
222       2019.0
223       2019.0
224       2019.0
225       2019.0
226       2019.0
227       2019.0
228       2019.0
229       2019.0
230       2019.0
231       2019.0
232       2019.0
233       2019.0
234       2019.0
235       2019.0
236       2019.0
237       2019.0
238       2019.0
239       2019.0
240       2019.0
241       2019.0
242       2019.0
243       2019.0
244       2019.0
245       2019.0
246       2019.0
247       2019.0
248       2019.0
249       2019.0
           ...
128162    2019.0
128163    2019.0
128164    2019.0
128165    2019.0
128166    2019.0
128167    2019.0
128168    2019.0
128169    2019.0
128170    2019.0
128171    2019.0
128172    2019.0
128173    2019.0
128174    2019.0
128175    2019.0
128176    2019.0
128177    2019.0
128178    2019.0
128179    2019.0
128180    2019.0
128181    2019.0
128182    2019.0
128183    2019.0
128184    2019.0
128185    2019.0
128186    2019.0
128187    2019.0
128188    2019.0
128189    2019.0
128190    2019.0
128191    2019.0
128192    2019.0
128193    2019.0
128194    2019.0
128195    2019.0
128196       NaN
128197    2019.0
128198    2019.0
128199    2019.0
128200    2019.0
128201    2019.0
128202    2019.0
128203    2018.0
128204    2019.0
128205    2019.0
128206    2019.0
128207    2019.0
128208    2019.0
128209    2019.0
128210    2019.0
128211    2019.0
128212    2019.0
128213    2019.0
128214    2019.0
128215    2019.0
128216    2019.0
128217    2019.0
128218    2019.0
128219    2019.0
128220    2019.0
128221    2019.0
128222    2019.0
128223    2019.0
128224    2019.0
128225    2019.0
128226    2019.0
128227    2019.0
128228    2019.0
128229    2019.0
128230    2019.0
128231    2019.0
128232    2019.0
128233    2019.0
128234    2019.0
128235    2019.0
128236    2019.0
128237    2019.0
128238    2019.0
128239    2019.0
128240    2019.0
128241    2019.0
128242    2019.0
128243    2019.0
128244    2019.0
128245    2019.0
128246    2019.0
128247    2019.0
128248    2019.0
128249    2019.0
128250    2019.0
128251    2019.0
128252    2019.0
128253    2019.0
128254    2019.0
128255    2019.0
128256    2019.0
128257    2019.0
128258    2019.0
128259    2019.0
128260    2019.0
128261    2019.0
128262    2019.0
128263    2019.0
128264    2019.0
128265    2019.0
128266    2019.0
128267    2019.0
128268    2019.0
128269    2019.0
128270    2019.0
128271    2019.0
128272    2018.0
128273    2019.0
128274    2019.0
128275    2019.0
128276    2019.0
128277    2019.0
128278    2019.0
128279    2019.0
128280    2019.0
128281    2019.0
128282    2019.0
128283    2019.0
128284    2019.0
128285    2019.0
128286    2019.0
128287    2019.0
128288    2019.0
128289    2019.0
128290    2019.0
128291    2019.0
128292    2019.0
128293    2019.0
128294    2019.0
128295    2019.0
128296    2019.0
128297    2019.0
128298    2019.0
128299    2019.0
128300    2019.0
128301    2019.0
128302    2019.0
128303    2019.0
128304    2019.0
128305    2019.0
128306    2019.0
128307    2019.0
128308    2019.0
128309    2019.0
128310    2019.0
128311    2019.0
128312    2019.0
128313    2019.0
128314    2019.0
128315    2019.0
128316    2019.0
128317    2019.0
128318    2019.0
128319    2019.0
128320    2019.0
128321    2019.0
128322    2019.0
128323    2019.0
128324    2019.0
128325    2019.0
128326    2019.0
128327    2018.0
128328    2019.0
128329    2019.0
128330    2019.0
128331    2019.0
128332    2019.0
128333    2019.0
128334    2019.0
128335    2019.0
128336    2019.0
128337       NaN
128338    2019.0
128339    2019.0
128340    2019.0
128341    2019.0
128342    2019.0
128343    2019.0
128344    2019.0
128345    2019.0
128346    2019.0
128347    2019.0
128348    2019.0
128349    2019.0
128350    2019.0
128351    2019.0
128352    2019.0
128353    2019.0
128354    2019.0
128355    2019.0
128356    2019.0
128357    2019.0
128358    2019.0
128359    2019.0
128360    2019.0
128361    2019.0
128362    2019.0
128363    2019.0
128364    2019.0
128365    2019.0
128366    2019.0
128367    2019.0
128368    2019.0
128369    2019.0
128370    2019.0
128371    2018.0
128372    2019.0
128373    2019.0
128374    2019.0
128375    2019.0
128376    2019.0
128377    2019.0
128378    2019.0
128379    2019.0
128380    2019.0
128381    2019.0
128382    2019.0
128383    2019.0
128384    2019.0
128385    2019.0
128386    2019.0
128387    2019.0
128388    2019.0
128389    2019.0
128390    2019.0
128391    2019.0
128392    2019.0
128393    2019.0
128394    2019.0
128395    2019.0
128396    2019.0
128397    2019.0
128398    2019.0
128399    2019.0
128400    2019.0
128401    2019.0
128402    2019.0
128403    2019.0
128404    2019.0
128405    2019.0
128406    2019.0
128407    2018.0
128408    2019.0
128409    2019.0
128410    2019.0
128411    2019.0
Name: last_pymnt_d, Length: 128412, dtype: float64

In [0]:
df['last_pymnt_d_month']= df['last_pymnt_d'].dt.month

In [0]:
df['last_pymnt_d_year']= df['last_pymnt_d'].dt.year

In [0]:
df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,loan_status_is_great,last_pymnt_d_month,last_pymnt_d_year
0,10000,10000,10000.0,36.0,10.33%,324.23,B,B1,NaN,< 1 year,MORTGAGE,280000.0,Not Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,974xx,OR,6.15,2,Jan-1996,0,18.0,NaN,14,0,9082,38%,23,w,8289.30,8289.30,2261.00,2261.00,1710.70,550.30,0.0,0.0,0.0,2019-07-01,324.23,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,671,246828,1,3,2,3,1.0,48552,62.0,1,3,4923,46.0,23900,2,7,1,7,17631.0,11897.0,43.1,0,0,158.0,275,11,1,1,11.0,NaN,11.0,NaN,0,3,4,7,7,10,9,11,4,14,0.0,0,0,4,91.3,28.6,0,0,367828,61364,20900,54912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0
1,4000,4000,4000.0,36.0,23.40%,155.68,E,E1,Security,3 years,RENT,90000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,070xx,NJ,26.33,0,Sep-2006,4,59.0,NaN,15,0,5199,19.2%,20,w,3423.38,3423.38,1081.96,1081.96,576.62,505.34,0.0,0.0,0.0,2019-07-01,155.68,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,66926,5,4,3,4,5.0,61727,86.0,6,11,1353,68.0,27100,4,0,4,15,4462.0,20174.0,7.9,0,0,147.0,118,2,2,0,2.0,NaN,0.0,NaN,0,5,7,9,9,8,11,12,7,15,0.0,0,0,9,95.0,0.0,0,0,98655,66926,21900,71555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0
2,5000,5000,5000.0,36.0,17.97%,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Late (31-120 days),n,debt_consolidation,Debt consolidation,490xx,MI,10.51,0,Apr-2011,0,NaN,NaN,8,0,4599,19.1%,13,w,4456.17,4456.17,895.96,895.96,543.83,352.13,0.0,0.0,0.0,2019-06-01,180.69,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,110299,0,1,0,2,14.0,7150,72.0,0,2,0,35.0,24100,1,5,0,4,18383.0,13800.0,0.0,0,0,87.0,92,15,14,2,77.0,NaN,14.0,NaN,0,0,3,3,3,4,6,7,3,8,0.0,0,0,0,100.0,0.0,0,0,136927,11749,13800,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,0,6.0,2019.0
3,23000,23000,23000.0,60.0,20.89%,620.81,D,D4,Operator,5 years,RENT,68107.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,672xx,KS,0.52,0,Feb-1997,0,NaN,NaN,5,0,976,13%,10,w,21353.16,21353.16,4307.45,4307.45,1646.84,2660.61,0.0,0.0,0.0,2019-07-01,620.81,Sep-2019,Aug-2019,1,NaN,1,Individual,NaN,NaN,NaN,0,2693,976,0,0,0,0,36.0,0,NaN,3,4,0,13.0,7500,2,2,4,4,195.0,3300.0,0.0,0,0,237.0,262,10,10,0,10.0,NaN,9.0,NaN,0,0,1,3,4,3,5,7,1,5,0.0,0,0,3,100.0,0.0,0,0,7500,976,3300,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0
4,8000,8000,8000.0,36.0,23.40%,311.35,E,E1,Manager,10+ years,OWN,43000.0,Source Verified,Dec-2018,Current,n,debt_consolidation,Debt consolidation,357xx,AL,33.24,0,Jan-1995,0,NaN,107.0,8,1,9019,81.3%,16,w,6846.83,6846.83,2163.85,2163.85,1153.17,1010.68,0.0,0.0,0.0,2019-07-01,311.35,Sep-2019,Aug-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,169223,0,3,2,2,7.0,22059,69.0,0,0,2174,72.0,11100,1,1,1,2,21153.0,126.0,94.5,0,0,148.0,287,44,7,1,51.0,NaN,7.0,NaN,0,1,4,1,2,8,4,7,4,8,0.0,0,0,2,100.0,100.0,1,0,199744,31078,2300,32206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,1,7.0,2019.0

# STRETCH OPTIONS

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01