<a href="https://colab.research.google.com/github/alxanderpierre/DS-Unit-1-Sprint-1-Dealing-With-Data/blob/master/Pierre_Nelson_LS_DS_112_Loading_Data_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice Loading Datasets

This assignment is purposely semi-open-ended you will be asked to load datasets both from github and also from CSV files from the [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php). 

Remember that the UCI datasets may not have a file type of `.csv` so it's important that you learn as much as you can about the dataset before you try and load it. See if you can look at the raw text of the file either locally, on github, using the `!curl` shell command, or in some other way before you try and read it in as a dataframe, this will help you catch what would otherwise be unforseen problems.

## 1) Load a dataset from Github (via its *RAW* URL)

Pick a dataset from the following repository and load it into Google Colab. Make sure that the headers are what you would expect and check to see if missing values have been encoded as NaN values:

<https://github.com/ryanleeallred/datasets>

In [0]:
# TODO your work here!
# And note you should write comments, descriptions, and add new
# code and text blocks as needed

In [0]:
import pandas as pd

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/Cancer_Cells.csv', dropna=)

In [6]:
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [8]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [10]:
df.shape

(569, 33)

In [18]:
df = df.dropna(axis='columns')
df.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [21]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

## 2) Load a dataset from your local machine
Download a dataset from the [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php) and then upload the file to Google Colab either using the files tab in the left-hand sidebar or by importing `files` from `google.colab` The following link will be a useful resource if you can't remember the syntax: <https://towardsdatascience.com/3-ways-to-load-csv-files-into-colab-7c14fcbdcb92>

While you are free to try and load any dataset from the UCI repository, I strongly suggest starting with one of the most popular datasets like those that are featured on the right-hand side of the home page. 

Some datasets on UCI will have challenges associated with importing them far beyond what we have exposed you to in class today, so if you run into a dataset that you don't know how to deal with, struggle with it for a little bit, but ultimately feel free to simply choose a different one. 

- Make sure that your file has correct headers, and the same number of rows and columns as is specified on the UCI page. If your dataset doesn't have headers use the parameters of the `read_csv` function to add them. Likewise make sure that missing values are encoded as `NaN`.

In [0]:
from google.colab import files

In [44]:
upload = files.upload()

Saving wine.data to wine.data

In [0]:
columns_header = ['Alcohol','Malic acid','Ash','Alcalinity of ash ', 'Magnesium',
	                 'Total phenols','Flavanoids','Nonflavanoid phenols',
                   'Proanthocyanins','Color intensity','Hue', 
                   'OD280/OD315 of diluted wines', 	'Proline',]
 	
wine_data = pd.read_csv("wine.data", names=columns_header, na_values='NaN')

In [51]:
wine_data.head()

   Alcohol  Malic acid   Ash  ...   Hue  OD280/OD315 of diluted wines  Proline
1    14.23        1.71  2.43  ...  1.04                          3.92     1065
1    13.20        1.78  2.14  ...  1.05                          3.40     1050
1    13.16        2.36  2.67  ...  1.03                          3.17     1185
1    14.37        1.95  2.50  ...  0.86                          3.45     1480
1    13.24        2.59  2.87  ...  1.04                          2.93      735

[5 rows x 13 columns]

In [0]:
# TODO your work here!
# And note you should write comments, descriptions, and add new
# code and text blocks as needed

## 3) Load a dataset from UCI using `!wget`

"Shell Out" and try loading a file directly into your google colab's memory using the `!wget` command and then read it in with `read_csv`.

With this file we'll do a bit more to it.

- Read it in, fix any problems with the header as make sure missing values are encoded as `NaN`.
- Use the `.fillna()` method to fill any missing values. 
 - [.fillna() documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html)
- Create one of each of the following plots using the Pandas plotting functionality:
 - Scatterplot
 - Histogram
 - Density Plot

In [22]:
!wget https://raw.githubusercontent.com/ryanleeallred/datasets/master/car_regression.csv

--2019-08-06 21:55:01--  https://raw.githubusercontent.com/ryanleeallred/datasets/master/car_regression.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 263167 (257K) [text/plain]
Saving to: ‘car_regression.csv’

car_regression.csv  100%[===================>] 257.00K  --.-KB/s    in 0.03s

2019-08-06 21:55:02 (8.39 MB/s) - ‘car_regression.csv’ saved [263167/263167]

In [0]:
car_data_frame = pd.read_csv('car_regression.csv')

In [27]:
car_data_frame.isnull().sum()

make            0
price           0
body            0
mileage         0
engV            0
engType         0
registration    0
year            0
drive           0
dtype: int64

In [0]:
# Lets try another on that has some NaN values.

In [28]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data

--2019-08-06 22:00:42--  https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3974305 (3.8M) [application/x-httpd-php]
Saving to: ‘adult.data’

adult.data          100%[===================>]   3.79M  15.7MB/s    in 0.2s

2019-08-06 22:00:42 (15.7 MB/s) - ‘adult.data’ saved [3974305/3974305]

In [0]:
columns_header = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 
                 'marital-status', 'occupation', 'relationship', 'race', 'sex', 
                 'capital-gain', 'capital-loss', 'hours-per-week', 
                 'native-country', 'income']
adult_data = pd.read_csv('adult.data', names=columns_header, na_values=' ?')

In [38]:
adult_data.head(20)

    age          workclass  fnlwgt  ... hours-per-week  native-country  income
0    39          State-gov   77516  ...             40   United-States   <=50K
1    50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2    38            Private  215646  ...             40   United-States   <=50K
3    53            Private  234721  ...             40   United-States   <=50K
4    28            Private  338409  ...             40            Cuba   <=50K
5    37            Private  284582  ...             40   United-States   <=50K
6    49            Private  160187  ...             16         Jamaica   <=50K
7    52   Self-emp-not-inc  209642  ...             45   United-States    >50K
8    31            Private   45781  ...             50   United-States    >50K
9    42            Private  159449  ...             40   United-States    >50K
10   37            Private  280464  ...             80   United-States    >50K
11   30          State-gov  141297  ...             40           India    >50K
12   23            Private  122272  ...             30   United-States   <=50K
13   32            Private  205019  ...             50   United-States   <=50K
14   40            Private  121772  ...             40             NaN    >50K
15   34            Private  245487  ...             45          Mexico   <=50K
16   25   Self-emp-not-inc  176756  ...             35   United-States   <=50K
17   32            Private  186824  ...             40   United-States   <=50K
18   38            Private   28887  ...             50   United-States   <=50K
19   43   Self-emp-not-inc  292175  ...             45   United-States    >50K

[20 rows x 15 columns]

In [40]:
adult_data.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [41]:

df.fillna(method='ffill')

           id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
5      843786         M  ...          0.3985                  0.12440
6      844359         M  ...          0.3063                  0.08368
7    84458202         M  ...          0.3196                  0.11510
8      844981         M  ...          0.4378                  0.10720
9    84501001         M  ...          0.4366                  0.20750
10     845636         M  ...          0.2948                  0.08452
11   84610002         M  ...          0.3792                  0.10480
12     846226         M  ...          0.3176                  0.10230
13     846381         M  ...          0.2809                  0.06287
14   84667401         M  ...          0.3596                  0.14310
15   84799002         M  ...          0.4218                  0.13410
16     848406         M  ...          0.3029                  0.08216
17   84862001         M  ...          0.3706                  0.11420
18     849014         M  ...          0.2768                  0.07615
19    8510426         B  ...          0.2977                  0.07259
20    8510653         B  ...          0.3184                  0.08183
21    8510824         B  ...          0.2450                  0.07773
22    8511133         M  ...          0.4667                  0.09946
23     851509         M  ...          0.2822                  0.07526
24     852552         M  ...          0.3613                  0.09564
25     852631         M  ...          0.4066                  0.10590
26     852763         M  ...          0.4264                  0.12750
27     852781         M  ...          0.2341                  0.07421
28     852973         M  ...          0.4027                  0.09876
29     853201         M  ...          0.2756                  0.07919
..        ...       ...  ...             ...                      ...
539    921362         B  ...          0.2790                  0.10660
540    921385         B  ...          0.2329                  0.08134
541    921386         B  ...          0.3187                  0.10230
542    921644         B  ...          0.2722                  0.06956
543    922296         B  ...          0.2473                  0.06443
544    922297         B  ...          0.2249                  0.08492
545    922576         B  ...          0.2642                  0.06953
546    922577         B  ...          0.2681                  0.07399
547    922840         B  ...          0.2691                  0.09479
548    923169         B  ...          0.2552                  0.07920
549    923465         B  ...          0.3059                  0.07626
550    923748         B  ...          0.2458                  0.06592
551    923780         B  ...          0.3169                  0.08032
552    924084         B  ...          0.2407                  0.06484
553    924342         B  ...          0.2435                  0.07393
554    924632         B  ...          0.2372                  0.07242
555    924934         B  ...          0.2226                  0.08283
556    924964         B  ...          0.2262                  0.06742
557    925236         B  ...          0.2475                  0.06969
558    925277         B  ...          0.2258                  0.08004
559    925291         B  ...          0.2112                  0.08732
560    925292         B  ...          0.2250                  0.08321
561    925311         B  ...          0.1566                  0.05905
562    925622         M  ...          0.4089                  0.14090
563    926125         M  ...          0.2929                  0.09873
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]

## Stretch Goals - Other types and sources of data

Not all data comes in a nice single file - for example, image classification involves handling lots of image files. You still will probably want labels for them, so you may have tabular data in addition to the image blobs - and the images may be reduced in resolution and even fit in a regular csv as a bunch of numbers.

If you're interested in natural language processing and analyzing text, that is another example where, while it can be put in a csv, you may end up loading much larger raw data and generating features that can then be thought of in a more standard tabular fashion.

Overall you will in the course of learning data science deal with loading data in a variety of ways. Another common way to get data is from a database - most modern applications are backed by one or more databases, which you can query to get data to analyze. We'll cover this more in our data engineering unit.

How does data get in the database? Most applications generate logs - text files with lots and lots of records of each use of the application. Databases are often populated based on these files, but in some situations you may directly analyze log files. The usual way to do this is with command line (Unix) tools - command lines are intimidating, so don't expect to learn them all at once, but depending on your interests it can be useful to practice.

One last major source of data is APIs: https://github.com/toddmotto/public-apis

API stands for Application Programming Interface, and while originally meant e.g. the way an application interfaced with the GUI or other aspects of an operating system, now it largely refers to online services that let you query and retrieve data. You can essentially think of most of them as "somebody else's database" - you have (usually limited) access.

*Stretch goal* - research one of the above extended forms of data/data loading. See if you can get a basic example working in a notebook. Image, text, or (public) APIs are probably more tractable - databases are interesting, but there aren't many publicly accessible and they require a great deal of setup.