<a href="https://colab.research.google.com/github/cheddur93/DS-Sprint-01-Dealing-With-Data/blob/master/ChadOwen_module1-afirstlookatdata/LS_DS_111_A_First_Look_at_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lambda School Data Science - A First Look at Data

## Lecture - let's explore Python DS libraries and examples!

The Python Data Science ecosystem is huge. You've seen some of the big pieces - pandas, scikit-learn, matplotlib. What parts do you want to see more of?

In [0]:
# TODO - we'll be doing this live, taking requests
# and reproducing what it is to look up and learn things
1 + 1

2

## Assignment - now it's your turn

Pick at least one Python DS library, and using documentation/examples reproduce in this notebook something cool. It's OK if you don't fully understand it or get it 100% working, but do put in effort and look things up.

In [10]:
# TODO - your code here
# Use what we did live in lecture as an example
import pandas as pd
import numpy as np
import datetime as dt 

import matplotlib.pyplot as plt 
from matplotlib import cm 
plt.style.use('ggplot')

%matplotlib inline

from __future__ import division

nfl = pd.read_csv('https://raw.githubusercontent.com/ryurko/nflscrapR-data/master/play_by_play_data/regular_season/reg_pbp_2009.csv');
nfl.head(255)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (42,166,167,174,175,178,179,182,183,188,189,190,191,203,204,205,231,232,233,238,240,241) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
5,162,2009091000,PIT,TEN,TEN,away,PIT,TEN,98.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
6,183,2009091000,PIT,TEN,TEN,away,PIT,TEN,98.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
7,207,2009091000,PIT,TEN,TEN,away,PIT,TEN,94.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
8,228,2009091000,PIT,TEN,TEN,away,PIT,TEN,96.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
9,253,2009091000,PIT,TEN,PIT,home,TEN,TEN,43.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
10,277,2009091000,PIT,TEN,PIT,home,TEN,TEN,40.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
11,301,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
12,322,2009091000,PIT,TEN,PIT,home,TEN,TEN,31.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
13,346,2009091000,PIT,TEN,PIT,home,TEN,TEN,22.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
14,365,2009091000,PIT,TEN,PIT,home,TEN,TEN,41.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
15,393,2009091000,PIT,TEN,TEN,away,PIT,TEN,89.0,2009-09-10,...,00-0022119,T.Polamalu,15.0,0,NaN,Unnecessary Roughness,0.0,0.0,0.0,0.0
16,425,2009091000,PIT,TEN,TEN,away,PIT,PIT,42.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
17,449,2009091000,PIT,TEN,TEN,away,PIT,PIT,22.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
18,470,2009091000,PIT,TEN,TEN,away,PIT,PIT,19.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
19,496,2009091000,PIT,TEN,TEN,away,PIT,PIT,19.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
20,522,2009091000,PIT,TEN,TEN,away,PIT,PIT,19.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
21,542,2009091000,PIT,TEN,PIT,home,TEN,PIT,73.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
22,563,2009091000,PIT,TEN,PIT,home,TEN,PIT,72.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
23,584,2009091000,PIT,TEN,PIT,home,TEN,PIT,70.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
24,603,2009091000,PIT,TEN,PIT,home,TEN,PIT,79.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
25,622,2009091000,PIT,TEN,TEN,away,PIT,TEN,74.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
26,646,2009091000,PIT,TEN,TEN,away,PIT,TEN,64.0,2009-09-10,...,00-0023548,D.Stewart,5.0,0,NaN,Illegal Formation,0.0,0.0,0.0,0.0
27,681,2009091000,PIT,TEN,TEN,away,PIT,TEN,69.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
28,705,2009091000,PIT,TEN,TEN,away,PIT,TEN,60.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
29,726,2009091000,PIT,TEN,TEN,away,PIT,TEN,57.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,1155,2009091304,CLE,MIN,CLE,home,MIN,MIN,39.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
226,1176,2009091304,CLE,MIN,CLE,home,MIN,MIN,34.0,2009-09-13,...,00-0024263,C.Griffin,28.0,0,NaN,Defensive Pass Interference,0.0,0.0,0.0,0.0
227,1208,2009091304,CLE,MIN,CLE,home,MIN,MIN,6.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
228,1315,2009091304,CLE,MIN,CLE,home,MIN,MIN,3.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
229,1344,2009091304,CLE,MIN,CLE,home,MIN,MIN,1.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
230,1369,2009091304,CLE,MIN,CLE,home,MIN,MIN,2.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
231,1388,2009091304,CLE,MIN,MIN,away,CLE,CLE,30.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
232,1402,2009091304,CLE,MIN,MIN,away,CLE,MIN,80.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
233,1426,2009091304,CLE,MIN,MIN,away,CLE,MIN,71.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
234,1447,2009091304,CLE,MIN,MIN,away,CLE,MIN,71.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
235,1468,2009091304,CLE,MIN,MIN,away,CLE,MIN,71.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
236,1490,2009091304,CLE,MIN,CLE,home,MIN,CLE,58.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
237,1512,2009091304,CLE,MIN,CLE,home,MIN,CLE,58.0,2009-09-13,...,00-0023438,B.Edwards,5.0,0,NaN,False Start,0.0,0.0,0.0,0.0
238,1535,2009091304,CLE,MIN,CLE,home,MIN,CLE,63.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
239,1556,2009091304,CLE,MIN,CLE,home,MIN,CLE,64.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
240,1577,2009091304,CLE,MIN,CLE,home,MIN,CLE,53.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
241,1596,2009091304,CLE,MIN,MIN,away,CLE,MIN,85.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
242,1618,2009091304,CLE,MIN,MIN,away,CLE,MIN,85.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
243,1637,2009091304,CLE,MIN,NaN,NaN,NaN,MIN,NaN,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
244,1654,2009091304,CLE,MIN,MIN,away,CLE,MIN,91.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
245,1678,2009091304,CLE,MIN,MIN,away,CLE,MIN,91.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
246,1695,2009091304,CLE,MIN,MIN,away,CLE,MIN,81.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
247,1747,2009091304,CLE,MIN,MIN,away,CLE,CLE,30.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
248,1769,2009091304,CLE,MIN,MIN,away,CLE,MIN,74.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
249,1791,2009091304,CLE,MIN,MIN,away,CLE,MIN,74.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
250,1820,2009091304,CLE,MIN,MIN,away,CLE,MIN,66.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
251,1842,2009091304,CLE,MIN,MIN,away,CLE,MIN,66.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
252,1860,2009091304,CLE,MIN,CLE,home,MIN,CLE,61.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
253,1882,2009091304,CLE,MIN,CLE,home,MIN,CLE,61.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
254,1906,2009091304,CLE,MIN,CLE,home,MIN,CLE,59.0,2009-09-13,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0

### Assignment questions

After you've worked on some code, answer the following questions in this text block:

1.  Describe in a paragraph of text what you did and why, as if you were writing an email to somebody interested but nontechnical.
  
  -- I wrote a function to determine if a company is profitable. All you need to do is input revenues and expenses... although basic, we could carryout this function to make it more dynamic, analyzing an entire P&L spreadsheet --
  
  -- I loaded in NFL data from 2 different games using an open source csv --
  
2.  What was the most challenging part of what you did?

  -- I was struggling to retrieve and evaluate a key from a dictionary --
  
  -- Trying to come up with x and y values to display --

3.  What was the most interesting thing you learned?

  -- How to properly define a function, include if/else, and retrieve info from a dictionary --
  
  -- There are a lot of different variables you can compare from just one NFL game --

4.  What area would you like to explore with more time?

  -- I'm going to explore Linear regression models based on NFL player/team data, and see if I can recreate one --

  -- Effective comparable variables --

## Stretch goals and resources

Following are *optional* things for you to take a look at. Focus on the above assignment first, and make sure to commit and push your changes to GitHub (and since this is the first assignment of the sprint, open a PR as well).

- [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/)
- [scikit-learn documentation](http://scikit-learn.org/stable/documentation.html)
- [matplotlib documentation](https://matplotlib.org/contents.html)
- [Awesome Data Science](https://github.com/bulutyazilim/awesome-datascience) - a list of many types of DS resources

Stretch goals:

- Find and read blogs, walkthroughs, and other examples of people working through cool things with data science - and share with your classmates!
- Write a blog post (Medium is a popular place to publish) introducing yourself as somebody learning data science, and talking about what you've learned already and what you're excited to learn more about

In [40]:
grow_mart = {'name':"Grow Mart",'founded': 1973, 'revenue': 265, 'expense': 183}
plant_depot = {'name': "Plant Depot",'founded': 1973, 'revenue': 302, 'expense': 240}
trees_r_us = {'name': "Trees R Us",'founded': 1985, 'revenue': 123, 'expense': 130}

def is_profitable(company):
  if company['revenue'] - company['expense'] > 0:
     print(company['name'], "is profitable")
  else :
     print(company['name'], "is operating at a loss")

is_profitable(trees_r_us)

Trees R Us is operating at a loss